### ISSUE TITLE
dynamically added module shall inform tha debuggur

### ISSUE THREAD

**Issue by talbergs** [cerebral/cerebral#1001]
Say, this is a signal that dynamically creates module if module not there
Then populates it's state..
```js
classifyThatPayload,
when(state`${props`modulePath`}`), {
  true: [],
  false: [
    c=> c.controller.addModule(c.props.modulePath, thatModuleFactory({name: c.props.moduleId})),
  ],
},
set(props`modulePath`, props`data`)
```
.. so that fresh module works, and gets maintained, but - debugger does not reflect it's state.

also `controller.removeModule` shall maintain debugger state tree

**Comment by MartanLV** [comment]
> ![](https://s3-us-west-2.amazonaws.com/s.cdpn.io/44216/cat_hungry.png)

**Comment by Guria** [comment]
@christianalfoni

**Comment by christianalfoni** [comment]
This needs to be solved adding a new payload handler to debugger here:

https://github.com/cerebral/cerebral-debugger/blob/master/src/app/sequences.js#L33

And we need to send a new type of devtools message. Take a look at how init works:

https://github.com/cerebral/cerebral/blob/next/packages/node_modules/cerebral/src/devtools/index.js#L163

A new type of message giving the state of the module added is needed. The new devtools method can be called from here:

https://github.com/cerebral/cerebral/blob/next/packages/node_modules/cerebral/src/BaseController.js#L266

**Comment by christianalfoni** [comment]
Housekeeping!
