### ISSUE TITLE
Suport for Inferno functional component lifecycle events

### ISSUE THREAD

**Issue by marano** [cerebral/cerebral#1002]
Currently, if I pass a lifecycle event prop to a functional component (wrapped by cerebral `connect`) it will break saying that a functional lifecycle event is not supported when using a class component. That is because cerebral wraps my functional component with a class component. I expect to be able to pass functional lifecycle events to my component even when wrapped by cerebral `connect`.

**Comment by christianalfoni** [comment]
This needs to be fixed in the inferno package. Efforts on this is being done on PR: https://github.com/cerebral/cerebral/pull/1267. Please review support for completely functional components

**Comment by christianalfoni** [comment]
Housekeeping!
