### ISSUE TITLE
Extending debounce operator

### ISSUE THREAD

**Issue by user1736** [cerebral/cerebral#1008]
Hi there!
It'll be really nice if you add ``maxWait`` option to the ``debounce`` operator, like in [_.debounce](https://lodash.com/docs/4.17.4#debounce)

Use case here is quite simple: I've got search input with server powered suggest, so I have to send requests each time user performs some input, but UX of this feature would be really bad if suggest options came only after user had finished his input. 

Also there's a serious lack of documentation on ``debounce``.

**Comment by henri-hulski** [comment]
The documentation for `debounce` is at http://cerebraljs.com/docs/api/operators.html#debounce. 

If you call the signal on `onchange`, it should work as intended.

**Comment by Guria** [comment]
I agree. Documentation here can't be called completely straight forward. We should consider improving it with better explanation.

**Comment by henri-hulski** [comment]
Here an example from auth-boilerplate for a [component](https://github.com/yacoma/auth-boilerplate/blob/master/client/components/Admin/Search.js#L18) and the corresponding [signal]( https://github.com/yacoma/auth-boilerplate/blob/master/client/modules/admin/signals/searchsubmitted.js) which uses debounce.

**Comment by user1736** [comment]
I, probably, didn't make myself clear. Let's see.

I have something like this in my code:

```
export const searchChanged = [
    set(state`searchFilter`, props`value`),
    debounce(500), {
        continue: [
           //httpStuff
        ],
        discard: []
    }
];
```

So, while I typing, http request won't be sent until I finally finish my input, so I won't get any hints based on my input from server. 
It doesn't look like suggest-input, huh?

**Comment by henri-hulski** [comment]
When you look at the component I linked above this is exactly the same. 

I use
```js 
onChange={(e, { value }) => searchSubmitted({ value })}
```

So the signal is called after every typing and when not getting anymore input within half a second (defined in debounce) it will query the server.

**Comment by henri-hulski** [comment]
Or do you want to get a suggest-input even if the user doesn't make a break while typing?
But why use `debounce` in that case? Maybe just `wait` if you want an initial break before suggest-input.

**Comment by Guria** [comment]
@henri nope. It still requires debounce. But with option not to delay more than maxWait param. Believe, lodash has it for reason

**Comment by henri-hulski** [comment]
@Guria Hmm lodash has no wait operator ...
So what is the reason?

**Comment by henri-hulski** [comment]
@Guria There is the throttle function which is actually a shortcut for using debounce with setting [maxWait to the debounce parameter](https://github.com/lodash/lodash/blob/4.8.0-npm/throttle.js#L59-L63).

**Comment by henri-hulski** [comment]
So if we want to add the `maxWait` parameter to `debounce` we could remove the `wait` operator or implement it using `debounce` with `maxWait`.

**Comment by user1736** [comment]
I've checked ``wait`` documentation [here](http://cerebraljs.com/docs/api/operators.html#wait) and it doesn't seem to solve my issue.

I've prepared example of desired behaviour with only `React` and `_.debounce` [here](https://www.webpackbin.com/bins/-Kq-1DEEGYw3crI3f84M)

Can you provide example with the same behaviour using `wait` operator?

btw `Redux` also have `maxWait` option in debounce extension, check this [package](https://www.npmjs.com/package/redux-debounce)

**Comment by christianalfoni** [comment]
@user1736 So sorry for late response here. I just got my head over water and doing an effort to get help with issues. I think this sounds like a wise thing to do as both underscore and redux has it. This can be fixed here:

https://github.com/cerebral/cerebral/blob/next/packages/node_modules/function-tree/src/factories/debounce.js

Using redux-debounce as reference:
https://www.npmjs.com/package/redux-debounce

Maybe we could just use that package.

**Comment by christianalfoni** [comment]
Housekeeping!
