### ISSUE TITLE
Crossbrowser support (documentation)

### ISSUE THREAD

**Issue by jeroenverfallie** [cerebral/cerebral#101]
I just made cerabral + cerebral-router work in IE9 and above, while this may not need to be supported by cerebral itself, here's some guideance.

### Cerebral

Async actions make use of Promises, so you need a Promise polyfill like https://github.com/jakearchibald/es6-promise
Or just include the Babel polyfill. 

CustomEvent will throw errors in IE, you can use the polyfill provided on MDN:

```jsx
(function () {
  function CustomEvent ( event, params ) {
    params = params || { bubbles: false, cancelable: false, detail: undefined };
    var evt = document.createEvent( 'CustomEvent' );
    evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
    return evt;
   }

  CustomEvent.prototype = window.Event.prototype;

  window.CustomEvent = CustomEvent;
})();
```

### Cerebral router

Because cerebral-router and dependencies make use of the HTML5 history api, you'll need a polyfill for that, like https://github.com/devote/HTML5-History-API

#### Unfortunatly window.location can't be overriden, so, you'll need to modify cerebral-router, addressbar and url-mapper by adding this line on the top..
```jsx
var location = window.history.location || window.location;
```

@christianalfoni is there anything we can do so you don't need a "fork" of these files, but keeping it clean?

And finally, cerebral-router makes use of `location.origin` so you'll need to provide a polyfill for that.
```jsx
if (!window.history.location.origin) {
  window.history.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
}
```

This will make cerebral & cerebral-router work fine in IE9 and above, as far as I have tested with my apps.

If you find other things, you could add them in a comment.

**Comment by saulshanabrook** [comment]
It might be nice to have some in browser selenium based tests. I have used [zuul](https://github.com/defunctzombie/zuul) before and it works pretty well. Saucelabs will give you five free machines for an open source project.

**Comment by christianalfoni** [comment]
Okay, I will make changes to cerebral-router to make this work and update website with needed polyfills, thanks!

**Comment by christianalfoni** [comment]
Hi there,

I am confused by one thing. Does IE9 have both window.location and window.history.location? Could we write the origin fix like this?:

```js

var location = window.history.location || window.location;

if (!location.origin) {
  location.origin = location.protocol + "//" + location.hostname + (location.port ? ':' + location.port: '');
}
```

**Comment by jeroenverfallie** [comment]
@christianalfoni it is actually the polyfill that adds `window.history.location` because `window.location` is immutable in IE.

**Comment by Guria** [comment]
@jeroenverfallie please review https://github.com/christianalfoni/cerebral-router/commit/2a3a77b949ca6d67df6c106a1091cee6170a02bf
and test it

**Comment by jeroenverfallie** [comment]
@Guria Tested and working.

**Comment by christianalfoni** [comment]
This is on website now
