### ISSUE TITLE
http: per-request options disregarded due to mergeWith bug

### ISSUE THREAD

**Issue by fvgoto** [cerebral/cerebral#1011]
### Problem
Provider options set while controller instantiation with `HttpProvider({...})` can not be overridden to **falsy** value on a per-request basis using third argument (`"Custom request" options` in the docu) to the action or factory.
This hits notably `withCredentials: false` and `baseUrl: ''` (but also killing some headers).

### More detailed usecase
```javascript
// app-wide http provider default options (e.g. for our API)
const controller = Controller({
  providers: [
    HttpProvider({
      baseUrl: 'http://ourdomain.tld/api',
      withCredentials: true,
    }),
  ],
  //modules: ....
})
```
```javascript
// particular action fetching some third party data (e.g. not our API)
function someGetAction ({http}) {
  return http.get('https://thirdparty.tld/public.json', {}, {
      baseUrl: '',
      withCredentials: false,
  })
}
```
This results in:
- request URL being:  "http://ourdomain.tld/apihttps://thirdparty.tld/public.json"
- and still sending cookies, which would trigger browser's CORS protection on cross-site (when fixing URL)
Thus both options, `baseUrl` and `withCredentials`, specified in the action are not honored, since they are falsy.

### Bug location
The bug resides in [utils.js#L42-L43](https://github.com/cerebral/cerebral/blob/42ad607d500c5af4be8cebff42201f7a0d3e07fb/packages/node_modules/%40cerebral/http/src/utils.js#L42-L43):
```javascript
export function mergeWith(optionsA, optionsB) {
  return Object.keys(optionsB).reduce((newOptions, key) => {
    if (!newOptions[key]) {   //<============================
      newOptions[key] = optionsB[key]
    } else if (key === 'headers') {
      newOptions[key] = mergeWith(newOptions[key], optionsB[key] || {})
    }
    return newOptions
  }, optionsA)
}
```
Called from [index.js#L105](https://github.com/cerebral/cerebral/blob/42ad607d500c5af4be8cebff42201f7a0d3e07fb/packages/node_modules/%40cerebral/http/src/index.js#L105) with _action options_ (A) and _module (provider) options_ (B):
```
updateOptions(newOptions) {
          moduleOptions = mergeWith(newOptions, moduleOptions)
},
```

Thus, if `newOptions.withCredentials = false`, whereas `moduleOptions.withCredentials = true`, the merged options has still `withCredentials = true`, which does not reflect, what is wanted in per-request options (`newOptions`)!

### Solution hint
I'm not quite sure what [utils.js#L42](https://github.com/cerebral/cerebral/blob/42ad607d500c5af4be8cebff42201f7a0d3e07fb/packages/node_modules/%40cerebral/http/src/utils.js#L42) is about...
- Either it probably should be something like `hasOwnProperty`
- or refactor mergeWith to start with `moduleOptions` and overwrite with properties from `newOptions`.

### Meta
- recommended tags: `http`, `bug`
- linked issue: #940: http provider needs test

**Comment by christianalfoni** [comment]
@fvgoto Thanks for an amazing issue, just beating myself up for this insanely late response. It has just been a bit too much for me to follow up for the last months. Open source and having a kid does not exactly go hand in hand :)

Yes, I agree, it needs a proper check. For example a simple `!(key in newOptions)` should suffice. This is where to fix it: https://github.com/cerebral/cerebral/blob/b61fd360bbc1d92bfdbb3405fe9e7d0498594eb6/packages/node_modules/%40cerebral/http/src/utils.js#L42

**Comment by christianalfoni** [comment]
Housekeeping!
