### ISSUE TITLE
Operator: deepMerge

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral#1013]
How do you feel about a new operator that recursively merges an object?

@garth I think this is your baby?

**Comment by garth** [comment]
It was my baby when operators was a separate package, but since it was merged it all got changed.

I don't see a problem with creating deep merge operator, shouldn't be too hard.

**Comment by maxfrigge** [comment]
No.. shouldn't be hard to implement. Would it be ok for the core though, or would you rather keep it lean?

**Comment by christianalfoni** [comment]
This can be added by looking at current merge: https://github.com/cerebral/cerebral/blob/b61fd360bbc1d92bfdbb3405fe9e7d0498594eb6/packages/node_modules/cerebral/src/operators/merge.js. Should be a new operator named `deepMerge`, please add tests.

**Comment by christianalfoni** [comment]
Housekeeping!
