### ISSUE TITLE
state.set fails with 'Cannot assign to read only property ...'

### ISSUE THREAD

**Issue by sladiri** [cerebral/cerebral#1014]
The error is: `Cannot assign to read only property 'foo' of object '#<Object>'`

I created this PR with a failing test case: https://github.com/cerebral/cerebral/pull/998

**Comment by eugene1g** [comment]
Same error and reported in Chrome with `Uncaught Error: Cerebral - The Signal "xxx" with action "yyy" has an error: Cannot define property __CerebralState, object is not extensible`
Showed up after updating from beta-3 to 2.0

**Comment by naturalethic** [comment]
https://github.com/cerebral/cerebral/pull/1015

**Comment by Guria** [comment]
Should be fixed with #1018 
Will be in next release
