### ISSUE TITLE
Chrome warning "[Violation] 'setTimeout' handler took Xms"

### ISSUE THREAD

**Issue by sladiri** [cerebral/cerebral#1030]
Line 34 in State.js currently uses setTimeout, which may replaced with a more performant mechanism to avoid the warning? There might be other places where a *setTimeout* without actual timeout might be replaced.
```js
        asyncTimeout = setTimeout(function () {
          return context.controller.flush();
        });
```
There is a Polyfill, which provides the *setImmediate* API as an alternative. https://github.com/YuzuJS/setImmediate 
It could be either used as is, since *setImmediate* is not implemented in many environments. Or Cerebral could implement one of the Polyfill's "tricks" on its own.

**Comment by christianalfoni** [comment]
Ah, I see! Though this might be related to sending data to the devtools. Stringifying is most likely the heavy lift running `flush`. Have you seen this issue in production? If not we can rather make the devtools code run a bit differently so it does not affect the flush, causing concerns :)

**Comment by christianalfoni** [comment]
Closing this for now, please reopen if still an issue :)
