### ISSUE TITLE
repo-cooker: run for PR and report evaluated versions

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#1046]
Would be great to have some report from travis in comments. Like which packages were affected and which versions would be released if merged.

**Comment by Guria** [comment]
cc @gaspard

**Comment by christianalfoni** [comment]
We can run the release script on PRs. This can be fixed here:

https://github.com/cerebral/cerebral/blob/b61fd360bbc1d92bfdbb3405fe9e7d0498594eb6/.travis.yml#L37

Just add a new `if` checking for pull request and run release script without the `-- --publish` arg

**Comment by christianalfoni** [comment]
Housekeeping!
