### ISSUE TITLE
<a> tag #hash links do not trigger signals in IE11

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#1077]
#hash routing in IE11 does not call signals when clicking on `<a href="#/myroute">` tags.

Calling signal directly does work and the url updates correctly.

**Comment by garth** [comment]
I have done some investigation. Address bar seems to be working, the events fire and the router is called. if I log out the url in `onUrlChange` in router.js then I get this after clicking on a <a> tag with a #url:

Edge:
```
url changed null
url changed /checkout/payment/payment
```

IE11:
```
url changed null
```

The event is fired twice in Edge where only the url is parsed the second time and only once in IE11.

**Comment by garth** [comment]
If it's of any use to anyone, here's a helper control that that normally outputs <a href... or <a onClick... for IE to work around this issue.

```js
const Link = connect(
    {
        browserName: state`useragent.browser.name`,
        routeSignal: signal`${props`signalName`}`
    },
    ({ signalName, routeSignal, signalProps, browserName, children }) =>
        <a
            {...(browserName === 'IE'
                ? {
                      onClick: (e) => {
                          e.preventDefault();
                          routeSignal(signalProps);
                      }
                  }
                : { href: router.getSignalUrl(signalName, signalProps) })}
        >
            {children}
        </a>
);
```

you call it and pass in the signalName and signalProps:
```js
<Link signalName="routed" signalProps={{ page: 'home' }}>Home</Link>
```

**Comment by christianalfoni** [comment]
This would be an `addressbar` issue. Please have a look at this repo: https://github.com/cerebral/addressbar/blob/master/index.js to find a workaround

**Comment by christianalfoni** [comment]
Housekeeping!
