### ISSUE TITLE
Let actions define a specific starting point on the state tree

### ISSUE THREAD

**Issue by tnrich** [cerebral/cerebral#108]
This would hopefully help with composability of submodules and separation of concerns.

Most of the time an action is really concerned with a teeny portion of the state. For example, a hypothetical setSelectionLayer action might be concerned with the following piece of info on the tree: ['editorState', 'selectionLayer']. The setSelectionLayer action doesn't really care about the first part of the path 'editorState' so it seems unnecessary to have to include it for that action. It also makes the action more brittle, what if now we want to nest the 'editorState' so it is no longer the top level of the tree, so now it's ['designEditor','editorState', 'selectionLayer'], now all the gets and sets within setSelectionLayer (and there might be several of them) need to be updated.
It would be nice if there were a nice pattern to set a 'top node' that the action will be concerned with, and then when the action gets nested or something changes in the path above it, only one place in the code would need to be changed.

@christianalfoni's proposed solution is to allow actions to specify a starting point on the state tree. The syntax would look like:

```
function myAction (input, state, output) {
  state.get('myValue'); // ['foo', 'bar', 'myValue']
}

myAction.path = ['foo', 'bar'];
```

**Comment by garth** [comment]
Sounds like a good idea, but if the purpose is to be able to reuse the same actions across different areas of the tree, might it be better to define via a wrapper or via the signal?

```js
controller.signal('usersChanged',
  chroot(['users'],
   setIsLoading,
   saveAction,
   unsetIsLoading
  )
);

controller.signal('accountsChanged',
  chroot(['accounts'],
   setIsLoading,
   saveAction,
   unsetIsLoading
  )
);
```

**Comment by tnrich** [comment]
Hey @garth, that does indeed seem like a more composable solution. Do you think that would be harder to implement? @christianalfoni, thoughts?

**Comment by christianalfoni** [comment]
Hm, hm... As we talked about on the gitter channel we can not mutate the actions as they are reusable. So the current suggestions can not be implemented. There was a suggestion on passing in paths to modules. So:

```js
function myAction (input, state, output, {paths}) {
  state.set([...paths.ADMIN, 'user', 'name'], 'foo');
}
```

Have to think about this some more :-)

**Comment by Guria** [comment]
part of modules api
