### ISSUE TITLE
http: possible problems with several request to same url

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#1124]
In our app we have something like long polling. It's usual situation when 2 or more requests on the same endpoint could coexist. I seems that @cerebral/http might have some problems with such situations.

See:
https://github.com/cerebral/cerebral/blob/b61fd360bbc1d92bfdbb3405fe9e7d0498594eb6/packages/node_modules/%40cerebral/http/src/index.js#L22

**Comment by christianalfoni** [comment]
This could be fixed by using an array instead and when aborting using `http.abort`, `shifting` off the first item in the array.

**Comment by christianalfoni** [comment]
Housekeeping!
