### ISSUE TITLE
http: undocumented options onRequest and onResponse

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#1130]
https://github.com/cerebral/cerebral/blob/b61fd360bbc1d92bfdbb3405fe9e7d0498594eb6/packages/node_modules/%40cerebral/http/src/DEFAULT_OPTIONS.js#L11

**Comment by christianalfoni** [comment]
This can be fixed here: https://github.com/cerebral/cerebral/tree/next/packages/node_modules/%40cerebral/http

**Comment by christianalfoni** [comment]
Housekeeping!
