### ISSUE TITLE
support defaults for input values

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#114]
We can use ES6 syntax to provide input defaults but it doesn't work with type checking:
```js
function setSmth({ smth = 'default' }, state) {
    state.set(['smth'], smth);
}

setSmth.input = {
    smth: String
};

export default setSmth;
```

It will throw an error if `input.smth` is `undefined`.

Proposed solution is to define default inputs like:
```js
setSmth.defaultInput = {
    smth: 'default'
}
```

**Comment by christianalfoni** [comment]
I think this looks good!

**Comment by christianalfoni** [comment]
I believe this is in? :-)
