### ISSUE TITLE
Router throws when url contains a query parameter with an underscore

### ISSUE THREAD

**Issue by oliverox** [cerebral/cerebral#1172]
Steps to reproduce:

- set up a simple router like so:
```
const router = Router({
  routes: [
    {
      path: '/',
      signal: 'routeToHome'
    },
  ]
});
```
- Accessing the page by opening the browser to `/` should run the signal `routeToHome` successfully.

- Accessing the page by opening the browser to `/?loc=en_US` crashes the router.

It seems the issue is located here : https://github.com/cerebral/url-mapper/blob/master/compileRoute.js#L26
The `queryString` generated is not a valid URLON string (especially when there is an `_` in the query parameter). URLON expects underscores to be escaped like so: `/_`. This could be a quick fix, but I'm not sure if it's the right solution. I'll let you guys discuss: @Guria @christianalfoni

**Comment by Guria** [comment]
Ok, I am on my way to make better URLON parser that will escape special chars only when really needed:

![image](https://user-images.githubusercontent.com/36270/32725069-1f641816-c88d-11e7-9755-e488340691a1.png)

Will be part of next major router release

**Comment by Guria** [comment]
Though it still required to escape underscores in key:

![image](https://user-images.githubusercontent.com/36270/32725662-68669b7c-c88f-11e7-8dfc-67da5eb7a1a0.png)

**Comment by Guria** [comment]
Though it still required to escape underscore in key:

![image](https://user-images.githubusercontent.com/36270/32725684-7e7153da-c88f-11e7-88ab-ed282959c60b.png)

**Comment by Guria** [comment]
I will consider changing prefix to indicate objects. Need some to think and prove if it works.

**Comment by christianalfoni** [comment]
Housekeeping!
