### ISSUE TITLE
The computed experiment

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#118]
Hi there,

I have been pondering on this idea. There is a concept of facets/monkeys with Baobab. It is really great as it allows us to compute state. The first thing that comes to mind is relational state, where a message might reference its author by id. You want some way to create a message with the actual author, but without duplicating data. A facet/monkey fixes this.

The question is... where does this computing actually fit into the architecture? If we think of it in three layers:

- MODEL
- CONTROLLER
- VIEW

Now with monkeys they are put very close to the MODEL (state). In other solution they are put very close to the VIEW (components). But maybe this actually fits in with the layer in between?

So the theory here is:

- We want our state store to just be state. We do not care about how state should be displayed, only that we have state
- We do not want to create logic for displaying data in the VIEW. The reason is simple. It clutters the the VIEW, making them smarter than they need to be and it can be problematic to reuse the logic

### Welcome computed state

So computed state is controlled by Cerebral. Think of them liker organizers for bringing state from your state store to your components.

```js
const model = Model({
  messages: {},
  displayedMessages: []
});

const controller = Controller(model);

controller.compute({
  displayedMessages: function (get, ids) {
    return ids.map((id) => get(['messages', id]));
  }
});

export default controller;
```
What I like about this structure is that it reflects the flow. First you define all state. Then you create the controller and "on the other side" you define what will happen when you grab certain state paths.

This is basically it. The computed tree uses the same "shape" as the state tree. So nested values needs to be nested the same way in the computed tree. An error will be thrown if things do not match.

You do not have to think about using this in any special way. Just grab the state as you normally do and Cerebral takes care of the rest.

### How it works
The computed function knows the value it is hooked on to in the state tree. So when you grab state from *displayedMessages* the state value `[]` will be passed to the computed function, a long with a `get` function. Just write the code you need, grab the state you want and do not think about anything else.

The function knows what state you grab so if any of it changes, it will rerun itself the next time something in the UI needs it. The same goes for the value inside the state store that it uses. If you do a state mutation on it, the function will know to run itself again the next time something needs it. If there are no changes a cached value will be returned.

### Yet to come...
1. Dynamically create computed state using `state.compute()`
2. Pass computed states to the debugger. I was thinking of a dropdown displaying all paths that are computed. When selecting one it logs out the current computed state

### How to test
1. Clone master repo
2. `npm install`
3. Use typically: `import Controller from './../../cerebral/src/index.js'` in your project
4. Or try with the demo, `npm run demo`

**Comment by Yomguithereal** [comment]
Bringing @jacomyal to the discussion.

**Comment by Guria** [comment]
`controller.get(path)` fails if `controller.compute()` didn't called

**Comment by Guria** [comment]
debugger dumps only stored values without computed ones

**Comment by Guria** [comment]
add method to get stored value for computed nodes

**Comment by Guria** [comment]
[it is awesome](https://github.com/Guria/cerebral-modular/commit/d773611efd48e5e58fd40a22d3979e0e81aef392#diff-ac00db4b857428d16226b78e5e000436)

**Comment by christianalfoni** [comment]
@Guria Yeah, now the debugger gets the state of the tree. We need a separate concept for looking at computed state. If you use `get` you just have to point specifically to the computed state in question. I will add to debugger a list of computed state you can click to check them out :-)

At least that is the idea

**Comment by christianalfoni** [comment]
I am starting to think the computed values could be a default way to handle this with Cerebral. Then you can power up using Monkeys in Baobab if you need more functionality. Maybe there is a performance difference here too. Computed state will probably not support using other computed state. 

Like type checking, we give the basics. But you can add other lib to go pro if needed :-)

**Comment by Guria** [comment]
I vote to support using other computed state for now. Using monkeys on another layer just for nesting computed values seems overhead. Maybe I missing something, but it doesn't look natural.

**Comment by christianalfoni** [comment]
Yeah, I agree @Guria , though I meant using one or the other solution. So `computed state` if you do not need to have one computed state using an other. If you need that, use only monkeys.

The thing is that computed state based on computed state is insanely complex. The reason is that they have to run in the correct order. It is of course doable, but it will require a lo of effort on my part I believe.

Hm, hm... anyways, just saying it, not saying I will not do it :-)

**Comment by Guria** [comment]
I like `computed state` syntax. It a [lot more clear](https://github.com/Guria/cerebral-modular/commit/d773611efd48e5e58fd40a22d3979e0e81aef392#diff-ac00db4b857428d16226b78e5e000436). Will see if I can live without nested computed state.

**Comment by Guria** [comment]
Maybe `baobab`'s monkeys would accept such way to define someday.

**Comment by christianalfoni** [comment]
@Yomguithereal  and @jacomyal is here to discuss, so maybe :-) The big issue is performance and very often the simpler syntax you have, the less it performs. But yeah, it is always good to discuss :)

**Comment by saulshanabrook** [comment]
@christianalfoni Could you expand on why you think it makes sense to implement this in cerebral instead of in the store?

**Comment by christianalfoni** [comment]
sure :-)

1. The current suggestions has always been "close to component" or "inside state store". This is just a different approach, always good to try out different approaches
2. This would give computed state no matter what state store. For example immutable-js could get it
3. Computed state is more related to grabbing state, than defining state. In Cerebral it is Cerebral that grabs the state, so based on that theory it makes sense
4. Gut feeling
5. Experiments are fun :-)

No, but seriously, point 2. is the selling point here.

**Comment by saulshanabrook** [comment]
@christianalfoni Yeah that makes a lot of sense. I personally have wanted to try out immutable-js, but have shied away, because of the lack of computed data, so I can see how that would be a win.

I think it makes sense to try, it just worries me a bit to have two ways of doing the same thing. If baobab continues to support it's own facets then it becomes unclear which someone using cerebral should use.

It sounds like that that at least for the initial release, baobab's implementation will be more feature-full (allowing computed data to depend on other computed data), so as I user I will likely stick with that (for now). Then you have the added complication of dealing with both types of computed data. Like in the debugger, the issue of computed data has already come up a lot. It seems like it would only get more complicated if we add in another layer of it. Like, will you continue supporting facets/monkeys in the debugger?

It just makes me wonder if we take a step back, whether there is a clean theoretical seperation that we can look to, that will help us disntiguish where this feature belongs.

Despite these reservations, since this project is forging new ground, it seems like trying things out is sometimes the easiest way to understand if they makes sense.

**Comment by christianalfoni** [comment]
Hi @saulshanabrook,

Yup, you make a very good point here. It will indeed be confusing to use both monkeys and computed state. And this is something we have to evaluate in the experiment. We could let the state package "opt-in" on computed state really. So with Baobab the package would say:

```js
{
  computed: function () {
    return 'Baobab requires you to use Monkeys. Read more about them here: ...';
  },
  accessors: {},
  mutators: {}
}
```

And computed state would only be displayed in the debugger if you actually have any of them. So yeah, just some thoughts on how it could be solved. But this will be a voting after we try them out :-)

Yup, it will be strongly highlighted with EXPERIMENTAL until we reach a decision!

**Comment by Guria** [comment]
@christianalfoni could you past here current state of experiment?

**Comment by christianalfoni** [comment]
The current state of the experiment is on the webpage :-)

http://christianalfoni.com/cerebral/

**Comment by christianalfoni** [comment]
Will close this now, thinking about making it official part of Cerebral. It works very well now

**Comment by saulshanabrook** [comment]
Where is this feature documented now? I can't find it on the site, I am probably just missing something obvious =p

**Comment by christianalfoni** [comment]
http://www.cerebraljs.com/utilities/compute :-)

**Comment by christianalfoni** [comment]
We are launching a new site with version 1.0, it is a bit messy now

**Comment by saulshanabrook** [comment]
Ah great! I am so happy to see this project still going strong, I hadn't looked much at in the past 9 months =D

**Comment by christianalfoni** [comment]
Yeah, it has been a crazy ride :D Really looking forward to official 1.0 release in July. Having an event in Vienna, going to be aaaaawesome 🍻
