### ISSUE TITLE
router: Parsing of query params with underscore is unexpected

### ISSUE THREAD

**Issue by sveint** [cerebral/cerebral#1181]
The query to props parsing is a great idea. However, whenever you supply a query with underscores, the router provides props that are very confusing:

```
p_name=ABC&p_version=1&a_id=1
-->
p: {
    p: {
        a: {
            id: "1"
        },
        version: "1"
    },
    name: "ABC"
},
```

Being unfamiliar with the various query format standards out there, I would expect cerebral to just pass me the keys as listed, instead of parsing them. After asking @christianalfoni, he told me the router is using `urlon` for parsing the queries.

I'd like to raise two issues with the current behavior:

1. The user might not want to buy into the `urlon` format for whatever reason (particularly when integrating cerebral into an existing app). The forced usage of urlon can then be a dealbreaker, and the router is one of the most important addons for cerebral. If you can't use the router without a lot of hacking, it will probably put you off from using cerebral at all.

2. The [documentation](https://cerebraljs.com/docs/addons/router.html) is a bit lacking. The example about query -> props handling only show an example without underscores, with no mention of urlon.

I'd suggest making the urlon parsing opt-in (which could open for other parsing standards as well), and adding this to the documentation.

@christianalfoni , @Guria

**Comment by christianalfoni** [comment]
I really do feel that router should work like traditional routers by default, just so people does not get thrown off by this. It is a threshold to do signal based routing in the first place, want to ease people into the experience. Then we can rather add an `opt-in` for parsed query with documentation specifically on that. Cause then you do not have to read all the documentation on query parsing when just starting out with the router :)

**Comment by henri-hulski** [comment]
Just to summarize the discussion we had some days ago (26.10. on discord #general) about that 
> @Guria: the idea is that you are not constructing query by hands. Just setup mapping, put param into State and see what url you will get in address bar. Or you can use getSignalUrl helper. So you will get the value properly escaped.
Though we could be improve escaping in urlon to be not so aggressive and not to crash app on "nonvalid" queries

> @christianalfoni: Maybe we should just expose a `InvalidUrlError` error type from the router? So you can do something like:
```js
Controller({
  catch: new Map([
    [InvalidUrlError, handleTheError]
  ])
})
```
> The error can contain information about path, query etc.

> Or even `InvalidQueryError`

**Comment by henri-hulski** [comment]
@christianalfoni If you use the router in the proper way you don't need that. I think it's enough if we get our router docs clearer and through better errors which should be catchable.

**Comment by henri-hulski** [comment]
Maybe we should show more the strength of this router concept and how it differs from what you call "traditional router". 
I think it's a quite  powerful router concept and easier to use then the react router.

**Comment by Guria** [comment]
We can't just make it behaving like `like traditional routers by default`, because of map features.
But it possible to opt-out using base version of router, though we must document this option well.

@sveint normally queries isn't made for human and shouldn't be constructed by them. You can just use getSignalUrl method with a payload to get url that will work.
Though I see a point about integrating into existing app, but we want to have more safety for newcomers. URLON allows to preserve a types, so you will never get in a situation when you number, true, false becomes a string and your code breaks. Just because your action can't know if argument comes from direct signal call or parsed from url as string,

Given all above, most valid point here is poor documentation that must be improved. Also we can make URLON less faily and document existing opt-out way.

Anyway, thank you for raising concern. Will spent some time on this issues soon.

**Comment by christianalfoni** [comment]
The router documentation is lacking in terms of implementing into existing app. It would be great to write a "guide" on this. Add it to: https://github.com/cerebral/cerebral/tree/next/docs/guides

**Comment by Guria** [comment]
URLON nad url-mapper was updated to be more friendly.
We should update them in router but must consider it as breaking change.
See https://github.com/cerebral/urlon/releases/tag/3.0.0 and https://github.com/cerebral/url-mapper/releases/tag/v2.0.0 and https://twitter.com/GuriaFS/status/933102867795263488 for details

**Comment by christianalfoni** [comment]
Housekeeping!
