### ISSUE TITLE
debugger object inspector

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#119]
Object inspector:
* looks strange on wide area:
![](http://i.imgur.com/SB0hnvx.png)

* need to restore ability put object into chrome console

**Comment by christianalfoni** [comment]
Hm, yeah, that does not look that good. Maybe we should just remove it yes. Go back to just logging it out if you need to explore it. Lets just get a few more opinions here.

**Comment by edgesoft** [comment]
![skarmavbild 2015-12-13 kl 15 28 01](https://cloud.githubusercontent.com/assets/6061720/11767446/25a78ae4-a1ae-11e5-81ca-760e9ccb0e4e.png)

Looks good for me. Is this just for Cerebral router?

**Comment by Guria** [comment]
@edgesoft try mix of objects and strings on input

**Comment by Guria** [comment]
@christianalfoni maybe we can change component that renders input, but "dump to console" feature is must have still

**Comment by edgesoft** [comment]
@Guria Great idé!

**Comment by christianalfoni** [comment]
Hmmm, yeah, not sure how to display it though. Do not control how the object tree is created. So would kind have to have a link or something in front to dump to console? Hm hm hm

**Comment by Guria** [comment]
fixed in new debugger
