### ISSUE TITLE
originalFunc.bind is not a function TypeError in todomvc demo

### ISSUE THREAD

**Issue by zerkalica** [cerebral/cerebral#1194]
I try:

```
git clone https://github.com/cerebral/cerebral.git
cd cerebral
npm install && npm run setup
cd packages/demo/todomvc
npm start
```

<details> 
  <summary>And got TypeError: originalFunc.bind is not a function in browser: </summary>
<pre>
context.(anonymous function).Object.keys.reduce.provider.function._len2
node_modules/cerebral/lib/providers/Debugger.js:39
  36 | 
  37 |     return originalFunc.apply(provider, args);
  38 |   };
> 39 |   wrappedProvider[key].direct = originalFunc.bind(provider);
  40 | 
  41 |   return wrappedProvider;
  42 | }, typeof provider === 'function' ? function () {
View compiled
wrapProvider
node_modules/cerebral/lib/providers/Debugger.js:24
  21 | wrapProvider: function wrapProvider(providerKey) {
  22 |   var provider = context[providerKey];
  23 | 
> 24 |   context[providerKey] = Object.keys(provider).reduce(function (wrappedProvider, key) {
  25 |     var originalFunc = provider[key];
  26 | 
  27 |     wrappedProvider[key] = function () {
View compiled
(anonymous function)
node_modules/cerebral/lib/Provide.js:14
  11 | context[name] = cachedProvider = cachedProvider || provider(context);
  12 | 
  13 | if (context.debugger) {
> 14 |   context.debugger.wrapProvider(name);
  15 | }
  16 | 
  17 | return context;
View compiled
(anonymous function)
node_modules/function-tree/lib/FunctionTree.js:229
  226 | key: 'createContext',
  227 | value: function createContext(funcDetails, payload, prevPayload) {
  228 |   return [(0, _Execution2.default)(this), (0, _Props2.default)(), (0, _Path2.default)(), (0, _Resolve2.default)()].concat(this.functionTree.contextProviders).reduce(function (currentContext, contextProvider) {
> 229 |     var newContext = typeof contextProvider === 'function' ? contextProvider(currentContext, funcDetails, payload, prevPayload) : (0, _Context2.default)(contextProvider)(currentContext, funcDetails, payload, prevPayload);
  230 | 
  231 |     if (newContext !== currentContext) {
  232 |       throw new _errors.FunctionTreeError('A provider is not returning the context object, maybe it is a function factory and you forgot to call it?');
View compiled
FunctionTreeExecution.createContext
node_modules/function-tree/lib/FunctionTree.js:228
  225 | }, {
  226 |   key: 'createContext',
  227 |   value: function createContext(funcDetails, payload, prevPayload) {
> 228 |     return [(0, _Execution2.default)(this), (0, _Props2.default)(), (0, _Path2.default)(), (0, _Resolve2.default)()].concat(this.functionTree.contextProviders).reduce(function (currentContext, contextProvider) {
  229 |       var newContext = typeof contextProvider === 'function' ? contextProvider(currentContext, funcDetails, payload, prevPayload) : (0, _Context2.default)(contextProvider)(currentContext, funcDetails, payload, prevPayload);
  230 | 
  231 |       if (newContext !== currentContext) {
View compiled
FunctionTreeExecution.runFunction
node_modules/function-tree/lib/FunctionTree.js:135
  132 |   return;
  133 | }
  134 | 
> 135 | var context = this.createContext(funcDetails, payload, prevPayload);
  136 | var functionTree = this.functionTree;
  137 | var errorCallback = this.errorCallback;
  138 | var execution = this;
View compiled
runBranch
node_modules/function-tree/lib/executeTree.js:83
  80 |       return payloads;
  81 |     });
  82 |   } else {
> 83 |     execution.runFunction(currentItem, payload, prevPayload, processFunctionOutput(currentItem, runNextItem));
  84 |   }
  85 | }
  86 | 
View compiled
runBranch
node_modules/function-tree/lib/executeTree.js:51
  48 |   }
  49 |   nextBranch(payload);
  50 | } else if (isPrimitive(currentItem, 'sequence')) {
> 51 |   runBranch(currentItem.items, 0, payload, prevPayload, runNextItem);
  52 | } else if (isPrimitive(currentItem, 'parallel')) {
  53 |   var itemLength = currentItem.items.length;
  54 |   var payloads = [];
View compiled
executeTree
node_modules/function-tree/lib/executeTree.js:87
  84 |     }
  85 |   }
  86 | 
> 87 |   return runBranch([execution.staticTree], 0, initialPayload, null, end);
  88 | }
  89 | //# sourceMappingURL=executeTree.js.map
  90 | 
View compiled
withResolveAndReject
node_modules/function-tree/lib/FunctionTree.js:315
  312 | });
  313 | 
  314 | _this2.emit('start', execution, payload);
> 315 | (0, _executeTree2.default)(execution, payload, function (funcDetails, path, currentPayload) {
  316 |   _this2.emit('pathStart', path, execution, funcDetails, currentPayload);
  317 | }, function (currentPayload) {
  318 |   _this2.emit('pathEnd', execution, currentPayload);
View compiled
Controller.run
node_modules/function-tree/lib/FunctionTree.js:332
  329 | };
  330 | 
  331 | if (cb) {
> 332 |   withResolveAndReject(cb, cb);
  333 | } else {
  334 |   return new Promise(withResolveAndReject);
  335 | }
View compiled
Controller.runSignal
node_modules/cerebral/lib/BaseController.js:159
  156 |   }, {});
  157 | }
  158 | 
> 159 | this.run(name, signal, payload, function (error) {
  160 |   if (error) {
  161 |     var signalPath = (0, _utils.ensurePath)(error.execution.name);
  162 |     var signalCatch = signalPath.reduce(function (currentModule, key, index) {
View compiled
run
node_modules/cerebral/lib/Module.js:35
  32 |   signal: signal.signal || signal,
  33 |   catch: signal.catch || controller.catch ? new Map([].concat(controller.catch ? [].concat(_toConsumableArray(controller.catch)) : []).concat(signal.catch ? [].concat(_toConsumableArray(signal.catch)) : [])) : null,
  34 |   run: function run(payload) {
> 35 |     controller.runSignal(path.concat(signalKey).join('.'), signal.signal || signal, payload);
  36 |   }
  37 | };
  38 | 
View compiled
Router.onUrlChange
node_modules/@cerebral/router/lib/router.js:156
  153 | 
  154 | var prevSignal = (this.routesConfig[this.activeRoute.route] || {}).signal;
  155 | if (signal && (prevSignal !== signal || (0, _utils2.getChangedProps)(payload || {}, this.activeRoute.payload || {}))) {
> 156 |   this.controller.getSignal(signal)(payload);
  157 | }
  158 | 
  159 | this.activeRoute = { route: route, payload: payload };
View compiled
Controller.<anonymous>
node_modules/@cerebral/router/lib/router.js:59
  56 |     controller.on('flush', _this.onFlush.bind(_this));
  57 | 
  58 |     if (!options.preventAutostart) {
> 59 |       _this.onUrlChange();
  60 |     }
  61 |   });
  62 | }
View compiled
Controller.emit
node_modules/eventemitter3/index.js:149
  146 | if (listeners[i].once) this.removeListener(event, listeners[i].fn, undefined, true);
  147 | 
  148 | switch (len) {
> 149 |   case 1: listeners[i].fn.call(listeners[i].context); break;
  150 |   case 2: listeners[i].fn.call(listeners[i].context, a1); break;
  151 |   case 3: listeners[i].fn.call(listeners[i].context, a1, a2); break;
  152 |   case 4: listeners[i].fn.call(listeners[i].context, a1, a2, a3); break;
View compiled
Controller.BaseController
node_modules/cerebral/lib/BaseController.js:106
  103 | 
  104 |   _this.getSignal = getSignal;
  105 | 
> 106 |   _this.emit('initialized');
  107 |   return _this;
  108 | }
  109 | /*
View compiled
new Controller
node_modules/cerebral/lib/Controller.js:41
  38 | function Controller(config) {
  39 |   _classCallCheck(this, Controller);
  40 | 
> 41 |   var _this = _possibleConstructorReturn(this, (Controller.__proto__ || Object.getPrototypeOf(Controller)).call(this, Object.assign({
  42 |     Model: _Model2.default
  43 |   }, config)));
  44 | 
View compiled
Controller
node_modules/cerebral/lib/index.js:87
  84 | }
  85 | 
  86 | function Controller(options) {
> 87 |   return new _Controller2.default(options);
  88 | }
  89 | function UniversalController(options) {
  90 |   return new _UniversalController2.default(options);
View compiled
./src/controller.js
src/controller.js:13
  10 | import toggleAllChecked from './actions/toggleAllChecked'
  11 | import clearCompletedTodos from './actions/clearCompletedTodos'
  12 | 
> 13 | const controller = Controller({
  14 |   devtools: Devtools({ host: 'localhost:8787' }),
  15 |   providers: [
  16 |     provide('uuid', uuid),
View compiled
</pre>
</details>

**Comment by henri-hulski** [comment]
Todomvc is not up to date with the recent API.
Try to change the UUID provider in `controller.js` to
```js
  providers: [
    provide('uuid', () => uuid),
```
If it works you could create a PR. ☺️

**Comment by zerkalica** [comment]
No, now i got an a error:

```
FunctionTreeError: A provider is not returning the context object, maybe it is a function factory and you forgot to call it?
```

**Comment by henri-hulski** [comment]
That's strange.
[Here](https://github.com/yacoma/auth-boilerplate/blob/master/client/controller.js#L42) I have updated the API and it works.

Could you compare if it's the same?

**Comment by Guria** [comment]
@christianalfoni is a bit skeptic about todomvc demo since this simple demo with Cerebral looks too complicated.
But I personally think that it could be quite qood e2e and api test at least.
I can take a look into it a bit later.

**Comment by zerkalica** [comment]
@henri-hulski 

Yours controller.js differs from original: https://github.com/cerebral/cerebral/blob/next/packages/demos/todomvc/src/controller.js.

``` git diff ``` in my cerebral directory shows:

```diff
git diff
diff --git a/packages/demos/todomvc/src/controller.js b/packages/demos/todomvc/src/controller.js
index c3da6f1f..ed4101e6 100644
--- a/packages/demos/todomvc/src/controller.js
+++ b/packages/demos/todomvc/src/controller.js
@@ -13,7 +13,7 @@ import clearCompletedTodos from './actions/clearCompletedTodos'
 const controller = Controller({
   devtools: Devtools({ host: 'localhost:8787' }),
   providers: [
-    provide('uuid', uuid),
+    provide('uuid', () => uuid),
     StorageProvider({
       target: window.localStorage,
       sync: { todos: 'todos' },
```

**Comment by henri-hulski** [comment]
@Guria Agree with you to keep TodoMVC.
BTW atm I'm working at a Cerebral implementation of [Conduit](https://realworld.io).

**Comment by henri-hulski** [comment]
@zerkalica yeah sure, it's a different app. But the fix was the same.
Your diff looks good, so not sure what happens. Atm I'm on mobile so I think we have to wait for @Guria.

**Comment by christianalfoni** [comment]
I guess this is old? Closing for now
