### ISSUE TITLE
The Cerebral Debugger App forces discrete graphics card switch

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#1195]
The Cerebral Debugger App forces Apple laptops with discrete graphics cards to use the discrete graphics card.

This means that running the Cerebral Debugger on Apple laptops with discrete graphics consumes considerably more battery then when the debugger is not running (even if the debugger is idle).

This issue can be demonstrated with the following tool: https://gfx.io/

**Comment by christianalfoni** [comment]
This must be an Electron issue. Debugger has been updated to latest version, have you tried again? Closing it for now
