### ISSUE TITLE
Compose Computeds

### ISSUE THREAD

**Issue by cyrusbowman** [cerebral/cerebral#1196]
Composing computeds doesn't seem to be working the way it is documented in the introduction section.

[Here](https://codesandbox.io/s/q86l7mq4o6) is the example from the docs.

When creating the following compute, composing 2 existing computes:

`compute(compute1, compute2)`

The first parameter of `compute2` is not the result of `compute1` as documented after `That means you can compose computeds, lets try by splitting them up into two:` in the introduction section.

---

However in the compute below `result1` is populated correctly.

`compute(compute1, (result1) => {})`

---

To explain another way:

This works: `compute(compute(()=>{return '1'}), (result1) => {})`
This doesn't work: `compute(compute(()=>{return '1'}), compute((result1) => {}))`

**Comment by christianalfoni** [comment]
@cyrusbowman Hi man! Man... so sorry for late response. I have just had problems putting efforts into general maintenance. I just got my head above water and summing up all issues now. Thanks for reporting, this does indeed look like a bug! I would label it as "PR wanted", though it is rather complex, so will look into this myself :)

**Comment by christianalfoni** [comment]
Housekeeping!
