### ISSUE TITLE
Integrating with Falcor/GraphQL

### ISSUE THREAD

**Issue by bfitch** [cerebral/cerebral#120]
The value of [Falcor](https://netflix.github.io/falcor/) and GraphQL's "declarative data fetching/caching/one endpoint" approach over tradition REST or REST-like patterns is obvious. Facebook has [Relay](https://facebook.github.io/relay/)-- their React framework for integrating with GrapQL-- and, apparently, Relay is on its way to managing client side data as well.

Are there any options for integrating with Falcor or GraphQL that are pluggable-- more akin to using an ajax library, so we can get the nice benefits mentioned above *with* cerebral's awesome signal based MVC architecture? Any other projects trying to do this?

**Comment by edgesoft** [comment]
You can check this out https://github.com/overture8/cerebral-react-falcor-example

**Comment by bfitch** [comment]
Summarized from discussion with @christianalfoni in gitter:

- Create a model-ish package (`cerebral-falcor`) that will "merge" Falcor data with an existing immutable store (immutable.js or baobab)
- Behind the scenes it will optimistically update and run a setValue on Falcor
-All state works exactly like it does now, but the model package will automatically update itself behind the scenes.
- You do not have to explicitly get data from server and insert it, or optimistically insert before a post. It just works
- create some custom chains, like we do with `cerebral-addons`: 
```js
import Falcor from 'cerebral-falcor';

export default Falcor({
  source: '/model.json'
});
```
```js
import {get} from './falcor.js';
import set from 'cerebral-addons/set';

export default [
  set(['isLoading'], true),
  get(['todos'], {
    success: [
        set(['isLoading'], false)
    ]
  })
];
```
so the falcor get returns an async array with a default action setting the response into the store on the success. Later we could have something like state.deepMerge({}) to handle any response, but yeah. Enough just to set something for now I think. 

Some pseudo code here:
```js
    get: function (path, outputs) {
      return [
        function makeQuery(input, state, output) {
          model.get(path).then(function (response) {
            output.success({json: response.json});
          }).catch(output.error);
        }, {
          success: [function setResult(input, state) {
            state.merge(input.json);
          }].concat(outputs.success || [])
        },
        error: output.error || []
      ]
    },
```

**Comment by Guria** [comment]
follow explorings at https://github.com/bfitch/cerebral-falcor-module
