### ISSUE TITLE
TS enhancement for @cerebral/inferno

### ISSUE THREAD

**Issue by br1anchen** [cerebral/cerebral#1201]
- [x] Use InfernoChildren type ( PR #1185 )
- [x] Fix other `Inferno` missing/any type
- [x] Add tests for `@cerebral/inferno` type definition file to cover basic usage

**Comment by christianalfoni** [comment]
Awesome @br1anchen , thank you so much for the help! :) Just closing this as PR is merged

**Comment by br1anchen** [comment]
@christianalfoni I think PR [#1207](https://github.com/cerebral/cerebral/pull/1207) is not merged yet. I did changes regarding to review.
Maybe @gaspard or other people can re-review it and merges it?
