### ISSUE TITLE
Rethinking TypeScript support

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#1206]
Hi there!

SO! I am going to write this as if it is already decided, but of course we want feedback before making it final :-) :

Cerebral is a relatively old framework. It was built before Typescript had any traction. Also me personally have never been in a project where Typescript has proven its cost, which means any lacking progress on Typescript is a blocker for the Cerebral project in general. The reason simply being that I can not take action on these issues as I am lacking the experience. Also Cerebrals nature, being highly decoupled, functional and declarative, contradicts Typescript in some ways. It is just difficult to tell Typescript how everything is connected and reap the benefits.

As Cerebral progressed there has been attempts on combining it with Typescript, with various degrees of success. Things like template literals will likely never work with Typescript. Due to the lack of a path to give official Typescript support Cerebral I think it is time to make a clear choice.

**Cerebral does not officially support Typescript**. There will be no documentation about it and the former statement will be the response when someone asks about support... "not officially supported". Anyone is free to create an **addon** which does export needed definitions and stuff, but for maintenance and progress reason we will keep all out of the main `monorepo`.

To actually have proper Typescript support Cerebral needs to be written in Typescript. This is a huge undertaking and we have no idea how well it will work. Due to this fact we need a way to prove its worth without too much effort. We need to start with `function-tree`. Basically implement the whole thing from scratch using Typescript and see where we hit a wall with the desired API... then evaluate alternatives to properly support Typescript.

If we have success with `function-tree` Cerebral will be the next natural step. This needs to be done ground up, not the other way around :)

What consequences has removal of type definitions now? Nothing breaks right? Please give any other feedback as well here!

PS! I just bought a book on TypeScript with the goal of writing `function-tree` from scratch... hopefully it will not be a frustrating experience and I will have something to show for soon ;-)

**Comment by kongdigital** [comment]
I'm all for dropping typescript if it is a blocker. I use typescript and I understand the reasons for dropping support. I've had to drop typescript from a project myself.

Nothing breaks at runtime obviously. However all the tooling will break. ie Webstorm will throw warning along with the compiler. Not that big of a deal. 

My main thought is give people at least some warning before doing it. I like how React gives deprecation warnings in the console. And they give you two minor versions before dropping support or something like that.

**Comment by gaspard** [comment]
I disagree completely.

Cerebral, function-tree or any other parts should not be rewritten with TypeScript, at least not until many core developers are familiar with TypeScript. Rewriting with TS is a very good exercise in simplifying and clarifying abstractions but it takes time and some getting used to. Nothing that can be done overnight.

Removing type definitions breaks each and every app using Cerebral and written with TypeScript. Not a nice move at all.

We should keep TypeScript support as it is:

- no rewrite !
- types added as people need them, gently catching up on missing parts
- gently adding TS specific parts like ([typed paths](https://gist.github.com/gaspard/773647c5438bce74b166d4f0708a933c) for example

If TS definitions block development, we fix this issue, eventually only running TS tests before merging to master or when we have "ts" commits.

**Comment by kongdigital** [comment]
Is there any point in logging Typescript issues?

**Comment by br1anchen** [comment]
Hi, I am currently trying to improve TS support for cerebral bit by bit if I can.
From my working experience on TS (I used vanilla JS on angular 0.x and 1.x, then switched to TS working on angular 1.x and  Reactjs), I think TS/flow introduce static typing on JS eco is a very good and important step. I enjoy working on TS a lot most of time.
But by TS language nature, it needs to support JS. It will not be as easy (less code) as other static typing languages, such as Elm/Haskell/Ocmal. I think that’s the biggest weakness when I am working with TS. It litterally makes developer writing more code (type, interface, type helper function, type definition files...).
But I think it is better and more fun way to write documents and re-think your code. TS makes our code more readable and self explained. And it does catch many potential run-time errors.
I agree with @gaspard, if current TS support does help people use cerebral, we should not drop it. (We need TS support test to verify current work)
But in the other hand, I do understand the mount of work for mainteners to support TS. I do not think it is necessary to rewrite core lib in TS as long as we can make the type definition correct.
From my “limited” package type definition files experience, many framework/library do not maintain official type definition files by themselves. But you can create unofficial one under @types/ to have basic support, and hope other people(like me) to maintain and sync with new updates.
The drawback is that, if your package is not popular enough, types package will not likely be maintained... which can be the reason people using TS switch to other packages. (In my experience, I will create minor type definition files if the package without)
@christianalfoni : If you want to rewrite function-tree in TS anyway. I would like to help :)

**Comment by christianalfoni** [comment]
@br1anchen So sorry for late reply here. I just got my head above water and we are pushing through on this with the `fluent` feature. It is right around the corner and will be a specific addon that allows for full type safety. Devs can still improve typescript support on the other addons etc, but will encourage Typescript developers to use the `fluent` addon for Cerebral/Function-tree type safety :)
