### ISSUE TITLE
Devtools.update also fired when debugger is not present

### ISSUE THREAD

**Issue by mgamperl** [cerebral/cerebral#121]
Is it intended, that `Devtools.update` is fired when the cerebral debugger extension is not present in the browser? 

I'm experiencing performance problems with 160 data items in my state and it seems to be related to the Devtools.update method.

**Comment by christianalfoni** [comment]
Hi @mgamperl,

Thanks for the heads up on this. I always use the debugger so did not notice.

I will make sure that if the debugger has not been loaded it will not store the signals. Will also make tracking signals default `false`. That way if you do not use the debugger at all it will never track or store signals. And when it is not registered to the app for some reason it will never store signals.

In production it will never do any of this btw

**Comment by rohitlodha** [comment]
@christianalfoni How do we set it as production? It appears to me it uses global.process.env === 'production' while it should use global.process.env.NODE_ENV  === 'production'

**Comment by christianalfoni** [comment]
You are perfectly right and this has been fixed :-)
