### ISSUE TITLE
Allow signal declaration to define asynchronicity rather that caller

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#122]
So at the moment we have:

```js
controller.signal('valueChanged', [
  updateValue
]);


<input value={value} onChange={e => signals.valueChanged.sync({ value: e.target.value })}/>
```

But for some (many?) signals we would aways want to do valueChanged synchronously so why not have something like:

```js
controller.syncSignal('valueChanged', [
  updateValue
});

<input value={value} onChange={e => signals.valueChanged({ value: e.target.value })}/>
```

At the moment I'm finding that in my case (input form heavy app) I have more sync signals than async and I rarely (probably never) need to call the same signal both ways.

You could still keep the valueChanged.sync() and add the valueChanged.async() option. So that the signal definition is simply defining the default initiation type which can always be overridden at call time if necessary.

**Comment by christianalfoni** [comment]
This is a really good idea @garth! I think it certainly makes more sense to define it on the signal. Maybe this is a good opportunity to expose an option object to the signal.

```js
controller.signal('somethingHappened', somethingHappened, {
  sync: true
});
```

Or maybe it is too early and we should use `controller.syncSignal`. What do you think?

**Comment by bfitch** [comment]
What if the function definition alone would make it async? Like if the action is an ES7 async function, cerebral would know it's async. 

I have no idea if that would be possible or make sense implementation wise, but would be pretty cool to make the API even simpler! No need to educate users about sync/async syntax, plus "it's just JavaScript". 😀

**Comment by christianalfoni** [comment]
Ah, but these are actually two different things :) This is about when the signal is triggered. If it waits for animation frame or just runs instantly. Though inside the signals, where the actions actually run it might be an idea to check the function. That said, we still need a way to group actions together.. but yeah... hmmmmmmm...

Maybe:

```js
const chain = [
  someSync,
  someAsync,
  [
    paraAsync1,
    paraAsync2
  ]
]

function someSync() {...}

async function someAsync() {...}

async function paraAsync1() {...}

async function paraAsync2() {...}
```

The point is that arrays now just becomes a way to group actions together. Meaning that it will run all of them right away, while if not grouped together it will run one after the other. The means it would make sense to do:

```js
[
  setLoading,
  get('/something'), {
    success: [unsetLoading, setSomething],
    error: [setError]
  }
]
```

And:

```js
[
  setLoading,
  [
    getOneThing, {...},
    getSomethingElse, {...}
  ]
]
```

Hmmm, I think that makes it a lot easier to reason about arrays. As they group actions, rather than defining async vs sync actions. Does that make sense?

**Comment by bfitch** [comment]
Yes, completely. Not overloading array would be great! Just for grouping actions 👍

**Comment by christianalfoni** [comment]
Hm, I have been researching a bit. The biggest problem is that we can not identify beforehand if the function is async or not. We actually have to run it to figure it out :-D

So we do not know if the function should have access to changing state or not. We could of course let async functions also change state. Hm... I think that is the only solution.

**Comment by garth** [comment]
I think that `controller.syncSignal` would be ok.

**Comment by salespreso** [comment]
Perhaps it should be `controller.signalSync` in the same way [node](https://nodejs.org/api/fs.html#fs_fs_fstatsync_fd) writes it?

**Comment by NervosaX** [comment]
Perhaps it should be `controller.signalSync` in the same way [node](https://nodejs.org/api/fs.html#fs_fs_fstatsync_fd) writes it?

**Comment by christianalfoni** [comment]
Okay, added as `signalSync`, will be part of next release. Soon to come :)
