### ISSUE TITLE
Cerebral 4: @cerebral/mobx-state-tree does not work with ModuleDefinition

### ISSUE THREAD

**Issue by hipertracker** [cerebral/cerebral#1223]
New Cerebral 4 uses new Module object with `ModuleDefinition` type which does not allow for `model` attribute
```
(7,3): error TS2345: Argument of type '{ model: { message: ISimpleType<string>; }; state: { message: string; }; signals: { app: Action<a...' is not assignable to parameter of type 'ModuleDefinition'.
  Object literal may only specify known properties, and 'model' does not exist in type 'ModuleDefinition'.
```

**Comment by gaspard** [comment]
You need to import `Controller` and `Module` from `@cerebral/mobx-state-tree`.

The types do not exist for this addon, but Controller accepts `Model` and Module accepts the `model`, `computed` and `getters` fields.
