### ISSUE TITLE
Inconsistent docs for the migration

### ISSUE THREAD

**Issue by hipertracker** [cerebral/cerebral#1227]
The website currently has two entries for the migration between Cerebral's versions.

The one is at https://cerebraljs.com/docs/migration/index.html. It's titled "4.0" but it does not say what version is it migrating from. 

And another, older one is located at https://cerebraljs.com/docs/resources/migration.html which describe the migration from 1.x to 2.x

**Comment by christianalfoni** [comment]
This can be fixed here: https://github.com/cerebral/cerebral/blob/next/docs/migration/4_0.md

**Comment by christianalfoni** [comment]
Housekeeping!
