### ISSUE TITLE
Compute error

### ISSUE THREAD

**Issue by tnrich** [cerebral/cerebral#123]
![image](https://cloud.githubusercontent.com/assets/2730609/10475325/10237912-71f7-11e5-8933-56de4592c1a8.png)

I'm not quite sure why this would be. Here's the offending lines of code: 

![image](https://cloud.githubusercontent.com/assets/2730609/10475313/db8f2a0c-71f6-11e5-8e58-532654f38b6d.png)

**Comment by tnrich** [comment]
You can debug it yourself if you want on master at: https://github.com/TeselaGen/openVectorEditor

**Comment by tnrich** [comment]
Yup, reverting to cerebral@0.20.5 fixed it.

**Comment by christianalfoni** [comment]
It this still an issue?

**Comment by Guria** [comment]
@tnrich ping

**Comment by tnrich** [comment]
This has been fixed as far as I can tell
