### ISSUE TITLE
@cerebral/storage type mismatch

### ISSUE THREAD

**Issue by hipertracker** [cerebral/cerebral#1230]
```javascript
import { Module, Controller } from 'cerebral'
import StorageModule from '@cerebral/storage'

const storage = StorageModule({
  target: localStorage,
  json: true,
  sync: {
    'someStorageKey': 'some.state.path'
  },
  prefix: 'somePrefix'
})

const app = Module({
  modules: { storage }
})
```
(code example source: https://github.com/cerebral/cerebral/blob/next/packages/node_modules/%40cerebral/storage/README.md)

[ts]
Argument of type '{ module: { storage: Provider; }; }' is not assignable to parameter of type 'ModuleDefinition'.
  Object literal may only specify known properties, and 'module' does not exist in type 'ModuleDefinition'.
(property) storage: (context: any, funcDetails: Primitive, payload: Payload, next: Payload) => any

**Comment by gaspard** [comment]
Thanks @hipertracker for the careful review of these types !
