### ISSUE TITLE
Custom Cerebral providers don't work with TypeScript

### ISSUE THREAD

**Issue by hipertracker** [cerebral/cerebral#1234]
When I try to import `Provider` from `cerebral` I have an error in TypeScript

```javascript
import {Provider} from 'cerebral'
```
```
error TS2305: Module '"/myapp/node_modules/cerebral/index"' has no exported member 'Provider'.
```
I guess the TS definition must be wrong, but not only in `cerebral`. The problem leads to `function-tree`.  I tried to import and create the TS version of [Provider.js](https://github.com/cerebral/cerebral/blob/next/packages/node_modules/cerebral/src/Provider.js) but I couldn't. It's because `Provider` (exported from the `function-tree`) [is not a class](https://github.com/cerebral/cerebral/blob/next/packages/node_modules/function-tree/index.d.ts#L105.), it's a TypeScript `type.`

**Comment by christianalfoni** [comment]
The `fluent` addon is right around the corner, where this is fixed :)
