### ISSUE TITLE
httpPost cannot read state

### ISSUE THREAD

**Issue by yustinrd** [cerebral/cerebral#1236]
my code:

```
import { httpPost } from '@cerebral/http/operators'
import { state } from 'cerebral/tags';

export default [
    httpPost('/auth', {
        username: state`auth.username`,
        password: state`auth.password`,
    })
];
```

request payload:
`{"username":{"type":"state","strings":["auth.username"],"values":[]},"password":{"type":"state","strings":["auth.password"],"values":[]}}`

how to send a state?

**Comment by hipertracker** [comment]
What Cerebral version are you using? It looks like a module. New Cerebral 4 requires a different syntax. Try this:

```javascript
import { Module } form 'cerebral'
import { httpPost } from '@cerebral/http/operators'
import { state } from 'cerebral/tags';

export default Module([
  httpPost('/auth', {
    username: state`auth.username`,
    password: state`auth.password`,
  })
])
```

**Comment by fopsdev** [comment]
hmmm interesting...is this some bug or do we need to write our own custom resolver inside a custom httpPost operator?

**Comment by christianalfoni** [comment]
@yustinrd @fopsdev We have changed how to pass objects where the properties have tags.

```js
import { httpPost } from '@cerebral/http/operators'
import { state, resolveObject } from 'cerebral/tags';

export default [
    httpPost('/auth', resolveObject({
        username: state`auth.username`,
        password: state`auth.password`,
    }))
];
```

Is this not documented? We have to fix this :)

**Comment by fopsdev** [comment]
aaah :) thanks!!!

**Comment by christianalfoni** [comment]
@yustinrd Would you want to update the docs with this solution? Just go to website and click edit :) If you do not have time, no worries, let me know and I will update when I find some time. Got some other pressing stuff going on :)

**Comment by Ackos95** [comment]
@christianalfoni 

When I try to use your solution with `resolveObject` I receive same stuff as before only wrapped in `cvalue` key. Request payload copied from chrome network tab looks like this.
```json
{"cvalue":{"email":{"type":"props","strings":["email"],"values":[]},"password":{"type":"props","strings":["password"],"values":[]}}}
```
I'm using wrapper around httpPost, to modify headers, but that shouldn't impact this. Inside wrapper only headers are modified, other params are passed down (to httpPost) as they were received.

Is this a bug or my mistake?

**Comment by henri-hulski** [comment]
For me it works fine.
Do you have recent cerebral and @cerebral/http? 
Do you use it exactly the way @christianalfoni shows above? 
Maybe show your code.

**Comment by henri-hulski** [comment]
And try without the wrapper.

**Comment by Ackos95** [comment]
@henri-hulski You were right, when I replaced wrapper with `httpPost` it worked as it should. That helped me a lot with debugging, I actually tried to implement my own resolver (wrapper around wrapper), in short, I wasted too much time on reinventing the wheel..

Thanks @henri-hulski, @christianalfoni.

P.S. You should think about upgrading documentation, it does need to grow, both in definitions and in examples.

**Comment by Ackos95** [comment]
While I'm at subject, have you thought about enabling spread operator before `state` or `props` tag? Something like this:
```js
httpPost('test/route', resolveObject({
  ...state`app.testObj`,
  override1: props`override1`,
}), { /* ... */ }
```
Should I maybe open new issue for that?

**Comment by christianalfoni** [comment]
@Ackos95 Yeah, we just put in "guides" in documentation. Though we need help expanding it. It takes so much time writing docs :-/

About your resolveObject thing, we would have to make it as:

```js
httpPost('test/route', resolveObject(state`app.testObj`, {
  override1: props`override1`,
}), { /* ... */ }
```

So it works like `Object.assign`. PR on this would be great :)

It can be fixed in: https://github.com/cerebral/cerebral/blob/next/packages/node_modules/function-tree/src/ResolveValue.js#L42

**Comment by henri-hulski** [comment]
See also #1280

**Comment by tazomazo** [comment]
It's still not in the documentation :(

https://cerebraljs.com/docs/addons/http.html#@cerebral/http-post

**Comment by christianalfoni** [comment]
Housekeeping!
