### ISSUE TITLE
HTTP Provider's onProgress Callback Always Receives Either 0 or 1.

### ISSUE THREAD

**Issue by lots0logs** [cerebral/cerebral#1237]
This is caused by a bug on this line:
https://github.com/cerebral/cerebral/blob/c7f7131ed0c5f8958cf1e28004e0773d5d5402b9/packages/node_modules/%40cerebral/http/src/utils.js#L11

It should be:
```js
progress: Number((event.loaded / event.total) * 100).toFixed()
```

**Comment by henri-hulski** [comment]
@lots0logs  Looks good! Do you want to create a Pull Request?

**Comment by lots0logs** [comment]
@henri-hulski I rebased my PR on latest from `next` branch.
