### ISSUE TITLE
Reaching for version 1.0

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#124]
- [x] Release new version of router
- [x] Release initial version of `cerebral-addons`
- [x] Refactor webpage with Cerebral and Cerebral-Router
- [x] Move official packages to new cerebral organization on Github
- [x] Only store signals in development and debugger running
- [ ] Review errors
- [ ] Tests for `cerebral-view-react`

#### Optimizations for production
- [ ] Do not create static signal tree
- [ ] Do not wrap mutation methods
- [ ] Do not wrap services

**Comment by Guria** [comment]
```js
import Cerebral from 'cerebral'
import Model from 'cerebral-model-baobab'
import Router from 'cerebral-module-router'
import Devtools from 'cerebral-module-devtools'
import View from 'cerebral-module-react' // yeah I mean a module here

import App, { Container } from './modules/app'

Cerebral(function (controller){
  controller.useModel(Model())

  // controller.registerSignals() // for simple apps

  controller.registerModules({
    devtools: Devtools() // will remember while bootstrap (controller.on('modulesLoaded'))
    app: App(),
    router: Router(), // will trigger right after bootstrap (controller.on('appStarted'))
    render: View(Container, '#root') // will render right after bootstrap
  })
})
```

**Comment by kgdev** [comment]
the Compute.js in Cerebral seems to be a source of memory leak as there is no way to release the cached computedFunc. If I create a computedFunc for each of the news feeds and new feeds keep coming. The old feed components can be unmounted from the DOM, but the computed funcs will not.

The possibility to create dynamic computed functions arrived a bit later and the scenarios it could be used for was still kinda "unknown".Creating a computed for each list item will cause some havoc in the long run. We need a way to release them.

**Comment by saulshanabrook** [comment]
@kgdev We are moving now to use https://github.com/cerebral/cerebral-computed and pulling all the computed out of Cerebral core. If you still find it a problem, could you open an issue on that repo?

**Comment by saulshanabrook** [comment]
consolidating with https://github.com/cerebral/cerebral/issues/215
