### ISSUE TITLE
Need a way to replace a loaded module signals for HMR

### ISSUE THREAD

**Issue by marano** [cerebral/cerebral#1248]
Hello to all!

I am trying to implement hot module reloading with Cerebral and I was wondering if there is a way to replace a module loaded signals. That's kind of the only thing I am missing. The HMR setup would look similar to the redux approach with `replaceReducer`.

Thank you in advance!

**Comment by christianalfoni** [comment]
@marano This sounds interesting! We could expose a method to "reset" the controller. Basically all you need is to in `BaseController.js`:

```js
    this.module = rootModule.create(this, [])
```

The `reset` method would just run this command again. It should probably also do a `this.emit('reset')` so other abstractions has a chance to do its work related to it. 

You want to try to create a PR? :)

**Comment by marano** [comment]
I managed to get this working by recreating the controller on hot reload, I think because that approach is working just fine I wouldn't put any effort on it for now. I'll just close this, but feel free to reopen if this can still be helpful on some other situation.

**Comment by christianalfoni** [comment]
Great stuff! Do you want to contribute with a guide to hot module reloading? :)

**Comment by marano** [comment]
@christianalfoni Yes sure! where should I put it? Should I add a section to the docs?

**Comment by christianalfoni** [comment]
I was thinking you could create a new guide :-) So `docs/guides/hot_reloading.md` or something :)

**Comment by christianalfoni** [comment]
Check out the https://cerebraljs.com/docs/contribute/index.html#introduction-contribute-to-website for info on adding new content :)

**Comment by marano** [comment]
Cool! thank you for the pointers, I'll dig into it soon.
