### ISSUE TITLE
Having trouble building Cerebral 4

### ISSUE THREAD

**Issue by claytonsurgeon** [cerebral/cerebral#1254]
In a fresh brunch project I install Cerebral in the usual manner
`npm install cerebral --save`

and in the main.js file:

```
import * as cerebral from "cerebral"  // this works fine
import devtools from "cerebral/devtools" // this fails
import { state, props } from "cerebral/tags" // this fails
```

Attempting to access devtools or tags results in the browser error:
Cannot find module 'cerebral/tags' from 'main.js'
or
Cannot find module 'cerebral/devtools' from 'main.js'

Any ideas why cerebral sub directories would fail? I have no such errors with cerebral 3.2 and earlier

**Comment by henri-hulski** [comment]
Should work. Do you have a new project or upgraded from Cerebral 3?

**Comment by claytonsurgeon** [comment]
The problem appears to be Brunch specific. I don't have this issue when building with Webpack
