### ISSUE TITLE
Router Error :: Could not parse url (Error: Unexpected char &)

### ISSUE THREAD

**Issue by lots0logs** [cerebral/cerebral#1259]
I'm not sure what the problem is. Any ideas? Here's an example of a URL that causes the error:
```
/?ab_username=_someuser&ab_api_key=abcdefg12345&ab_url=http%3A%2F%2Fwww.somewebsite.co.uk&ab_iframe=1&ab_animation=true&ab_is_bb=1
```

**Comment by christianalfoni** [comment]
Hi @lots0logs and sorry for the late reply here!

Is this an existing app using the url? Or is it produced by the router itself? The router uses `urlon`, which is a project that parses the url. It has some limitations, though the benefit is that the payload passed into your signals are actual parsed JSON. Let me know and we will look into it :)

**Comment by lots0logs** [comment]
Hi, thanks for following up :smiley:  This URL is not generated by the router. Basically we're passing some data as query arguments when initially loading the app in an iframe. I have to be honest and say this is very strange behavior. I think most users, myself included, expect for URL Queries to be handled in the standard way. Just my two cents :grimacing:

**Comment by christianalfoni** [comment]
@lots0logs Yeah, we have an internal discussion on this and I agree with you. I think the URLON parsing should be an opt-in experience as it definitely not what you would expect ;)

Will get back to you on this as the router will have a review shortly

**Comment by JukoPowel** [comment]
New version of urlon and url-mapper use '$' instead '_' for mapping nested payload.
@cerebral/router still uses old version of url-mapper.
After upgrade of this package issue should be solved (since '$' char cannot be part of url).

**Comment by mjarkovska** [comment]
@christianalfoni @Guria is there an update on this? My team is currently struggling with this same problem, and nothing seems to help. I have a similar url as @lots0logs and I have no control over how it looks. Unfortunately, the router is erroring on any symbols such as '.', '_', and '&'.

**Comment by JukoPowel** [comment]
@mjarkovska, I made a fork of cerebral to fix it, but it's for older version.
https://github.com/PowelAS/cerebral

Newer version of url-mapper allows usage of these chars.

**Comment by christianalfoni** [comment]
Housekeeping!

**Comment by lots0logs** [comment]
I also made [a fork](https://github.com/elegantthemes/cerebral-router) to update the url-mapper dep. Its for Cerebral v4.2.2.

**Comment by christianalfoni** [comment]
@Guria If you wanna look at merging that into url-mapper you are more than happy to :)

**Comment by henri-hulski** [comment]
@christianalfoni url-mapper had already an new release in November 2017 by @Guria. Only the url-mapper depency from the router was not updated and the router was not adapted to the new release (if necessary).

**Comment by christianalfoni** [comment]
Oh, sorry, I misread the comment. Yeah, hm... I guess we would have to checkout the repo at last version of the router and do a manual update of this, hm...

**Comment by henri-hulski** [comment]
So you want to bring back the router into Cerebral?  ;)

**Comment by christianalfoni** [comment]
Ah, hehe, no... was just to make that fix official to anyone using previous version of Cerebral. Though probably not worth it as I understand this specific case is solved. Unlikely that someone is using C4 with this exact use case :)
