### ISSUE TITLE
Homepage in npm leads to 404

### ISSUE THREAD

**Issue by troglotit** [cerebral/cerebral#1260]
Hey!
Homepage of cerebral in [npm](https://www.npmjs.com/package/cerebral) leads to 404; I think it's because of `cerebral-website` part of url.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/10955264/35905685-100d49d2-0bf9-11e8-9e17-2650ca6b993c.png">

**Comment by christianalfoni** [comment]
Hi and thanks for the feedback @troglotit :)

https://github.com/cerebral/cerebral/pull/1268
