### ISSUE TITLE
Is providers an object or array?

### ISSUE THREAD

**Issue by quinn** [cerebral/cerebral#1266]
first doc:

![image](https://user-images.githubusercontent.com/3764/36345086-cedcbe28-13f2-11e8-805a-65c43b0ab37e.png)

another doc:

![image](https://user-images.githubusercontent.com/3764/36345091-ddab94e2-13f2-11e8-9e85-0d39e0bc2c80.png)

? which ? is ? it ?

**Comment by quinn** [comment]
fwiw, the first one does not work, the second one does.

**Comment by henri-hulski** [comment]
Yep, in Cerebral 4 `providers` changed from array to object to make the API more consistent.

Where have you found the outdated docs?

**Comment by christianalfoni** [comment]
I am closing this by referencing the official docs: https://cerebraljs.com/docs/api/providers.html

**Comment by quinn** [comment]
@christianalfoni @henri-hulski updated doc: https://github.com/cerebral/cerebral/pull/1269

**Comment by christianalfoni** [comment]
@quinn Great stuff! :)
