### ISSUE TITLE
@cerebral/inferno breaks with inferno-create-element v4+

### ISSUE THREAD

**Issue by thedull** [cerebral/cerebral#1272]
After installing latest versions of @cerebral/inferno and inferno-create-element, I get:

```Uncaught TypeError: (0 , _infernoCreateElement2.default) is not a function```

This is most likely due to breaking changes of inferno-create-element that don't export the function ```createClass``` as default after version 4.0.0 and greater, and also to the fact that it is being imported as default in Hoc.js.

As of now, the only workaround I know is using v 3.X of inferno-create-element, but I'm not sure about any other implications derived from this.

**Comment by henri-hulski** [comment]
@thedull Is this related to #1267?

**Comment by henri-hulski** [comment]
Fixed in #1273.

**Comment by henri-hulski** [comment]
For now you can use `npm install @cerebral/inferno@next`.
