### ISSUE TITLE
Missing documentation for resolveObject

### ISSUE THREAD

**Issue by henri-hulski** [cerebral/cerebral#1280]
Usage of `resolveObject` needs to be documented e.g. in Cerebral tags, firebase docs, http docs and http guide.

**Comment by christianalfoni** [comment]
This can be added in respective README of each addon: https://github.com/cerebral/cerebral/tree/next/packages/node_modules/%40cerebral

and tags doc: https://github.com/cerebral/cerebral/blob/next/docs/api/tags.md

**Comment by christianalfoni** [comment]
Housekeeping!
