### ISSUE TITLE
Support universal apps

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#130]
Will introduce a `cerebral/universal` controller which is basically just a dummy controller that can be used with:

```js
import Controller from 'cerebral/universal';
import {Container} from 'cerebral-react';

app.get('/todos', (req, res) {
  const controller = Controller({
    todos: [{
       title: 'hey'
    }],
  });
  const html = renderToString(<Container controller={controller}><App/></Container>);
  res.send(html);
});
```

So you build up your state object and just pass it into the app. `cerebral-react` will understand that it is a dummy controller and will not register any change listeners etc, just grab the initial state and render the app correctly.

**Comment by ArnoBuschmann** [comment]
:+1:

**Comment by mclouvem** [comment]
HI @christianalfoni...thanks for your hard work on this incredible project. 
I have a doubt about universal app.I'm starting a new project and my initial idea is to use cerebral on it, and it should be an universal app. I saw that you committed the server controller to support universal...but I didn't understand how does it work.
Could you help me with some code example or guidance about how to implement it?

**Comment by grigio** [comment]
:+1: For Redux there is https://github.com/RickWong/react-isomorphic-starterkit but I'd prefer to avoid React-Router

**Comment by christianalfoni** [comment]
Hi guys!

Lets see, please check out this first: http://www.cerebraljs.com/utilities/universal. If something is unclear we can work on that page to make the documentation more clear :-)

**Comment by ArnoBuschmann** [comment]
While just looking at http://www.cerebraljs.com/utilities/universal I am unsure, how I would implement that in the cerebral-boilerplate code. Any hints? Having this explained in the documentation would be great as well, I guess :)

Oh and a small typo in the universal documentation:

```javascript
res.send(renderToString(<Container controller={controller}><App/></Container>);
```
should be
```javascript
res.send(renderToString(<Container controller={controller}><App/></Container>));
```

**Comment by christianalfoni** [comment]
Hm, yeah, would be nice with a universal app example. @ArnoBuschmann if you have time to just set up an example exactly as in the documentation. Do not think about client at all, I could direct you on what you would need to do to get it working. Then we could share that app as an example :-)

I have put up a "universal" channel on discord

**Comment by ArnoBuschmann** [comment]
@christianalfoni Sounds good! I have no time this week but next week I will check what I can come up with. :)

**Comment by christianalfoni** [comment]
:+1: :)

**Comment by Guria** [comment]
There is basic universal application support. Closing now. Fell free to open separate issues if current support is not enough.
