### ISSUE TITLE
Learnings and suggestions from Fluent implementation

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#1308]
So the **fluent** implementation was a huge step forward in getting TypeScript support for Cerebral. During the implementation we learned a lot and I have gotten some ideas to how we can integrate even more tightly with the current Cerebral API. This is not throw **fluent** overboard, it just inspires new possibilities in the Cerebral core package.

So these are the things I will talk about:

1. Generally use proxies to allow "object dot notation" instead of "string dot notation" and how this allows for TypeScript in core Cereral
2. Make Computed push update by attaching it to the controller
3. Expose Reaction to components

### 1. Core TypeScript support

Currently in Cerebral everything uses "string dot notation".

```js
// Operator
[
  set(state`foo`, props`foo`)
]

// Action
function myAction ({ state, props }) {
  state.set('foo', props.foo)
}

// Connect
connect({
  user: state`user`
})

// Computed
Computed(
  state`foo`,
  (foo) => {}
)
```

This is a great way to declaratively express a target and a path. The problem is that as developers we know what this string means, but for a computer it is very difficult. Basically this means typing solutions like TypeScript and Flow has no chance of understanding it.

To fix this we can use the same approach to all these points in the code. Expose proxies through a callback:

```ts
// Chained API operator
sequence(s =>
  s.set(({ state }) => state.foo, ({ props }) => props.foo)
)

// Action
function myAction ({ state, props }) {
  state.set(path => path.foo, props.foo)
}

// Connect
connect({
  user: ({ state }) => state.user
})

// Computed
Computed(
  (get) => get(({ state }) => state.foo),
  (foo) => {}
)
```

This is of course more verbose, but that IS the cost of typing. We can then allow the chaining API of sequences using something like this:

```ts
import { SequenceFactory } from 'cerebral/chaining'
import { connect } from '@cerebral/react'
import { State, Signals, Computed } from './app'

const controller = Controller<State, Signals, Computed>(app)

export const sequence = (s) => SequenceFactory<State>(s)
export const sequenceWithProps = <Props>(s) => SequenceWithPropsFactory<State, Props>>(s)
export const connect = <Props>(...args) => connect<State, Props>(...args)

export default controller
```

So basically what needs to be implemented here is:

1. Callbacks and proxies
2. Expose chaining API with operators
3. Babel loader to convert proxy callbacks to tags (IE support)

The biggest challenge here is point 3. Identifying all points of possible proxy callbacks and replace with normal tags. Just to be clear! The current Cerebral API stays the same, this is just an addition.

### 2. Computed
I want to attach computeds to the module:

```js
Module({
  computed: {
	foo: Computed(...)
  }
})
```

And use it with a tag:

```js
connect({
  foo: computed`foo`
})
```

This allows the computed to hook into the controller, registering for updates on it s dependencies and flag itself as "next usage requires recalculation". That means if the computed is never used, it will not re-evaluate. It is only when actually being used it will recalculate if flagged. Currently this only works on components, but with the new approach it will work wherever computeds are used.

### 3. Reaction

I want to expose the possibility to use reactions in components:

```js
connect({

},
  class MyComponent extends React.Component {
    componentDidMount () {
      this.props.reaction(state`foo`, this.onFooChange)
      this.props.reaction(({ state }) => state.foo, this.onFooChange)
    }
    onFooChange = (foo) => {}
)
```

This allows you to easily hook up state changes to imperative logic in components.

### Summary
So generally this is learnings from using fluent and mobx. There are advantages to using the existing Cerebral API with TypeScript, by giving new signatures and exposing the chaining API to it. That way we keep the current state store and the community closer together.

**Comment by kongdigital** [comment]
Fluent looks like it was a lot of work. My initial thoughts are how different it looks. I would almost hesitate and suggest rebranding. I think a new user would find it hard to reconcile how `fluent` is the same as `cerebral`. 

Plus `reactions` looks good. Can you clarify are reactions meant to be the same as `mobx` reactions? The concept is not really introduced.

**Comment by henri-hulski** [comment]
I really like that this is much closer to the classic Cerebral API.
I really love the simplicity and beauty of Cerebral and don't think we should drop it but evaluate from it! 

BTW we had proxy babel loaders before.

**Comment by christianalfoni** [comment]
@kongdigital Thanks for the input! 

I totally see what you mean about rebranding. It looks and feels very different, but so does TypeScript :) But `fluent` is the beginning of making Cerebral support TypeScript. If the suggested implementation here works I think we will be able to make a more clear separation of JS API and TS API, those will be the two brands. Basically two different versions of the website. At least that is what I am envisioning now.

Yeah, reactions are totally inspired by Mobx. It gives you the possibility inside a component to react to state changes. Previously you would have to depend on the state when you connect, do a new render and use `componentDidUpdate` to check differences in props. The `reaction` approach simplifies this process a lot, and is a lot more expressive.

This has to do with type inference. Believe me, I threw a ton of suggestions at @schotime, to simplify the API... but every time he had a great explanation of why this will not work with TypeScript :)

**Comment by christianalfoni** [comment]
Closing this as a discussion led to a new solution https://github.com/cerebral/cerebral/issues/1311
