### ISSUE TITLE
Project values for decision making

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#131]
Hi guys,

Cerebral is actually based on some core values and I think it would be good to agree on them. That way when new features are suggested we can ask ourselves if they match the core values, that way making it easier to move on and defend any suggestions we reject.

- We want to make complexity readable, not hide it
- We want our UI to be driven by the developed defined state of the app, not by other outside factors like urls or other internal state of the project
- We favor flexibility over less boilerplate. We do not implement features only to reduce code, it has to give more flexibility or increase readability
- We favor hooks rather than hardcoding to a specific scenario

What do you think?

**Comment by garth** [comment]
If you write it like some questions that you ask about a feature/change then anyone can ask those and decided if it fits the cerebral philosophy or not. I like the idea.

* :white_check_mark: Does this feature/change expose complexity and make it easier to understand?
* :white_check_mark: Does this feature/change encourage centralised state and pure functional programming, including pure UI components?
* :negative_squared_cross_mark: Does this feature/change reduce boilerplate code at the expense of flexibility or readability?
* :negative_squared_cross_mark: Does this feature/change introduce hardcoding that is difficult to change when necessary?

**Comment by christianalfoni** [comment]
Yeah, I like that idea a lot @garth, thanks :-D

**Comment by bfitch** [comment]
I think this is great and agree with all principals listed. If there is "one value to rule them all", I think it would be: **"Will this feature make my program easier to understand?"**. And I would add that most programmers (me included!) overvalue removing boilerplate and typing less. Really we should be optimizing comprehension/readability first and foremost and only secondarily DRYing up code and boilerplate. If the cerebral "core" is flexible (as Christian stated) those abstractions can be added on top.

So, how this works out in practice. When considering a new feature we need to weigh comprehension/flexibility vs DRY/abstraction and it can go a few ways:

1. Feature helps comprehension and does not add verbosity.
2. Feature helps comprehension but is more verbose.
3. Feature reduces comprehension but is less verbose.
4. Feature reduces comprehension and is more verbose.

According to @christianalfoni's values above: 

1. Obvious *YES*
2. Requires judgement, but *YES*
3. Requires judgement, but most likely *NO*
4. Obvious *NO*

I heard someone smart say: "the bottleneck when scaling an application is not typing, it's comprehension". :smile:

**Comment by saulshanabrook** [comment]
Reopened on website project https://github.com/cerebral/cerebral-website/issues/37
