### ISSUE TITLE
Making Cerebral even more declarative, with TypeScript typing to boot!

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#1311]
Okay, I had a few discussions related to trying to find a way to bring typing into the core of Cerebral. This is what we have landed on this far.

When you read this please remember the following things:

1. It is completely optional
2. We use babel to transform syntax into runnable code already
3. React brought JSX syntax into React to improve declarativeness, exactly what Cerebral reaches for

## A babel plugin

So the core of this idea is to provide a `babel-plugin-cerebral`. @FWeinb created a version of this some time ago, and just like @schotime chaining API... it surfaces again :)

The plugin will transform the following code:

```js
import { state, props, path } from 'cerebral/proxy'

function myAction ({ state }) {
  state.set(path.user, null)
}

export const doThis = [
  set(state.foo.bar, props.bar),
  myAction
]
```

Into:
```js
import { state, props } from 'cerebral/tags'

function myAction ({ state }) {
  state.set('user', null)
}

export const doThis = [
  set(state`foo.bar`, props`bar`)
]
```

The same happens for `connect` and `computed`.

That means you can use this babel plugin with the current Cerebral core API to make it even more declarative. This proves itself especially with:

```js
[
  when(state.sandboxes[props.id])
  // VS
  when(state`sandboxes.${props`id`}`
]
```

It is a huge improvement!

## Typescript support

Now, the only thing we need to do to make typescript work is to configure the app like this:

*proxy.d.ts*
```ts
import { AllState, AllSignals } from './app'

declare module 'cerebral/proxy' {
  const state: AllState;
  const signal: AllSignals;
}
```

This file will type the exported proxies. Typescript will actually pick up this file automatically, so do not need to import it anywhere.

When you want to type the props you just tell Typescript what the props proxy represents:

```ts
import { state, props, signal } from 'cerebral/proxy'

type Props = {
  id: string
}

const externalProps = props as Props

export default connect({
  user: state.user,
  item: state.items[externalProps.id]
}, ...)
```

What you express here is that you want the `props` proxy to act as the props of the component. Personally I think that makes perfect sense.

To fully bring TypeScript into Core of Cerebral it will need to expose the chaining API from `function-tree`, just like `fluent`. The way you configure your app with types will be pretty much the same, taken from current docs:

```ts
import {
  IContext,
  IBranchContext,
  ChainSequenceFactory,
  ChainSequenceWithPropsFactory
} from 'cerebral'
import { Provider as RouterProvider } from '@cerebral/router'
import { State, Signals } from './app/types'

// Create an interface where you compose your providers together
interface Providers {
  router: RouterProvider
  state: State
}

// Create a type used with your sequences and actions
export type Context<Props = {}> = IContext<Props> & Providers

// This type is used when you define actions that returns a path
export type BranchContext<Paths, Props = {}> = IBranchContext<Paths, Props> &
  Providers

// This function is used to define sequences
export const sequence = ChainSequenceFactory<Context>()

// This function is used to define sequences that expect to receive some initial
// props
export const sequenceWithProps = ChainSequenceWithPropsFactory<Context>()
```

The really great thing here is that we can reuse the existing operators:

```ts
import { state } from 'cerebral/proxy'
import { set } from 'cerebral/operators'
import { sequence } from 'app'

const doThis = sequence(s =>
  s.action(set(state.foo, 'bar'))
)
```

Or we can integrate them in the chaining API like this:

```ts
import { state } from 'cerebral/proxy'
import { sequence } from 'app'

const doThis = sequence(s =>
  s.set(state.foo, 'bar')
)
```

Though there is an exception on props here.

```ts
import { state } from 'cerebral/proxy'
import { sequence } from 'app'

const doThis = sequence(s =>
  s.set(props.foo, 'bar')
)
```

Typescript will not understand that the props are being extended here. But I consider it an edge case. And you can still do:

```ts
import { state } from 'cerebral/proxy'
import { sequence } from 'app'

const doThis = sequence(s =>
  s.action(() => ({ foo: 'bar' }))
)
```

## Summary

So the important thing to understand here is that what you import from `cerebral/proxy` is never run in the runtime. It is converted by the babel plugin to normal tags before it runs in the browser. The goal is to take advantage of babel to improve the declarativeness of Cerebral even more and opening the door for Typescript support in the core API.

**The positive**
- Option to improve declarativeness of existing API
- Typescript in core
- Keep current state store for Typescript (unlike fluent running on Mobx)
- IE support
- It is not possible to solve this with proxies the same way. Because a proxy needs to be created every time any usage would have to be `state().foo.bar` etc.

**The negative**
- Can be thought of as too much magic

As a final note I just want to state that I often get questions about 

```js
state`foo.bar`
```

Template literal tags is a feature of the language, but the syntax throws people off. And that is the point, it is just syntax. React ignored it and put JSX into their library to improve the declarativeness of the code. And that is ultimately what we are trying to do with Cerebral. Make it easy to read and reason about.

**Comment by samdenty99** [comment]
Is there a reason why you'd use a Babel plugin to transform the path, instead of doing it in the browser?

For example, using a proxy:
```js
// Convert a property accessor to an array
const symbol = Symbol('path')
const path = new Proxy({}, {
  get(obj, prop, proxy) {
    // Access the symbol on the proxy
    const property = Object.getOwnPropertyDescriptor(proxy, symbol)
    const access = property ? property.value : []
    access.push(prop)

    // Define the symbol on the proxy, containing the accessed path
    Object.defineProperty(proxy, symbol, {
      value: access,
      writable: true
    })
    return proxy
  }
})

// Example function to convert it back to a string
function convert(accessor) {
  const array = Object.getOwnPropertyDescriptor(accessor, symbol).value
  return array.join('.')
}

console.warn(convert(path.test.b.a))
// 'test.b.a'
```

**Comment by FWeinb** [comment]
@samdenty99 I already wrote a package that implements exactly this see [cerebral-proxy-tags](https://github.com/FWeinb/cerebral-proxy-tags). Cerebral Tags are quite a bit more tricky to implement using Proxy object because they need a `context` to be evaluated to an path. (Because you can nest tags like this: ``state`foo.${state`bar`}` ``)

I do think that it is maybe possible to implemented with proxies but for ie support there will always be the need for a babel plugin.

**Comment by IAMtheIAM** [comment]
It would be great if we can use TypeScript when using cerebral to develop an app too! Maybe we already can? This application framework makes the most sense of many which I have looked at recently, including Redux, Mobx, Next.js, and more. I'm looking into using it with the Electrode framework from Walmart Labs.

**Comment by christianalfoni** [comment]
Housekeeping!
