### ISSUE TITLE
Prevent dot in state / signals / modules key

### ISSUE THREAD

**Issue by etienne-dldc** [cerebral/cerebral#1321]
## Problem

Currently if you define a state / signals / modules key with a dot in it:

```js
Module({
  state: {
    'dotted.value': true
  },
  signal: {
    'dotted.action': []
  }
})
```

For `state` it "works" except state access (```state`dotted.value` ```) won't work, and state mutations (`state.set('dotted.value', false)`) will create an object `dotted: { value: false }` and from then the selection will work because now the `dotted` object exists. This mean cerebral changes the shape of the state which is not a good idea, in my opinion...

For `signals` it just doesn't work because cerebral look for a `dotted` module that doesn't exist.

This also has an impact on `module` because it means the `path` in `Module(({ path }) => ...)` is not "safe" : you can't split the path by dots to access for example the parent state of the module.

## Solution proposition

I think cerebral should check paths to make sure they are valid :
- In normal cerebral I think it should only make sure paths doesn't contain a dot (`.`).
- In `@fluent` we might want to check for variable safe names so we can access all properties with the dot notation (not sure about this, it might be too restrictive)...

**Comment by christianalfoni** [comment]
Housekeeping!
