### ISSUE TITLE
Warn about module overridden by state

### ISSUE THREAD

**Issue by etienne-dldc** [cerebral/cerebral#1322]
If a state has the same key as a module, the module is silently overridden by the state

```js
const module = Module({
  state: {
    override: true,
  },
  modules: {
    override: Module({
      state: {
        value: true
      }
    })
  }
});

// => state.override => true 
// => state.override.value => does not exist 
```

I think cerebral should raise an error or at least warn about this.

**Comment by etienne-dldc** [comment]
From my current understanding of the architecture there are two places where this logic could be added:

- In `src/Module.js` as some kind of validation
- In `src/utils` -> `extractModuleProp`, if I understand correctly that's where the override happen

For me `src/Module.js` make more sense but splitting the validation from the actual implementation is kind of risky...

**Comment by christianalfoni** [comment]
Housekeeping!
