### ISSUE TITLE
Feature: Expose a new param on actions that contains env/meta data about the signal & action path.

### ISSUE THREAD

**Issue by jeroenverfallie** [cerebral/cerebral#133]
## Case

When working with cerebral in production, I add loggers to every error path in the signals.
These loggers trigger an error to a remote service, such a Rollbar, Sentry, TrackJs, ... 

When logging these, I try to provide a meaningful namespace, so the error can be located & fixed easily.

Take this example logging factory:
```js
export default function(namespace) {
    return function logToRollbar(input) {
        if (window.Rollbar) {
            window.Rollbar.error('Custom :: ' + namespace, input);
        } else {
            console.warn('Rollbar::', namespace, input);
        }
    }
}
```

And this example signal:
```js
controller.signal('submitCredentials', [
    persistCredentials,
    [
        postCredentialsInternal, {
            success: [saveInternalUID],
            error: [logToRollbar('submitCredentials.postCredentialsInternal')]
        },
        postCredentialsCrm, {
            success: [saveCrmUID],
            error: [logToRollbar('submitCredentials.postCredentialsCrm')]
        }
    ]
]);
```

This gives us a nice error such as: (silly example)
![_7_custom____submitcredentials_postcredentialscrm_-_rollbar](https://cloud.githubusercontent.com/assets/1143308/11141160/e10c882c-89e2-11e5-8dc0-3ae28e9bbe9c.png)

![_7_custom____submitcredentials_postcredentialscrm__-_rollbar](https://cloud.githubusercontent.com/assets/1143308/11141310/4c18974a-89e4-11e5-8860-6459c916054c.png)

## Feature Request

Instead of manually providing a namespace, it would be nice to get a stack/path of the current signal/action/outputPath.

For example..
````js
// When triggered on "postCredentialsCrm:error"
function logToRollbar(input, state, output, services, stack) {
    // stack = ['submitCredentials', 'postCredentialsCrm', 'error'];
    // And further levels, including the full signal name with its namespace if included.
}
```


----

Discuss! :beers:

**Comment by Guria** [comment]
I vote for such signature then:
```js
function action({ input, state, output, services, stack }) {}
```

**Comment by jeroenverfallie** [comment]
I agree with @Guria , when there's this many params, it might be clever to go with the above.

Not sure how I feel about nesting destruction.
```javascript
function action({input: {id, name}, state, env}) {}
//vs
function action({id, name}, state, output, services, env) {}
```

**Comment by tnrich** [comment]
could this not be something (optionally) added to the services param? like `services.env`

**Comment by christianalfoni** [comment]
Hi guys,

Yeah, I suppose we could add this. But are there any other use cases for this "env" thingy? It seems a bit overkill to implement it just for the paths, for this specific scenario. Which is a great scenario btw :-)

Would like to see some more value to adding a new argument in the signature.

**Comment by Guria** [comment]
@christianalfoni introspections might be useful in tests, I think.

What do you think about putting arguments in single object?

**Comment by christianalfoni** [comment]
I will do this for 1.0 release, put everything in one argument. As we talked about on last session as well :)

**Comment by Guria** [comment]
now meta is exposed in events. @jeroenverfallie will it fit you, or still need an `env` in actions?

**Comment by christianalfoni** [comment]
Cleaning up issues, reopen if still an issue

**Comment by jeroenverfallie** [comment]
See the above PR reference, using events does not seem like a viable option specifically for error tracking.
