### ISSUE TITLE
Changing a store value from defined to undefined does not update props

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#134]
If a signal action unsets a value on the store, components that are subscribed to that value get the previous value passed to props when they update instead of undefined as expected.

**Comment by christianalfoni** [comment]
Ah, this is a `cerebral-react` issue. We... hm, how do one actually remove a state value from a react component? Like:

```js
this.setState({
  foo: 'bar'
})
```

How do I remove the "foo" key from the state?

**Comment by christianalfoni** [comment]
I have concluded that the current strategy is just wrong. I have removed the check for undefined and allow it to pass through. This will fix this issue and as stated, it was not a fix for handling default props at all.

Will be part of next release
