### ISSUE TITLE
@cerebral/forms setField() operator doesn't work with cerebral v4 "module" tag

### ISSUE THREAD

**Issue by cwilso03** [cerebral/cerebral#1355]
The @cerebral/forms `setField` operator doesn't support the cerebral v4 `module` tag.

Consider the following stripped down module:

```JavaScript
import { Module } from 'cerebral';                      // v.4.2.2
import { module, props } from 'cerebral/tags';
import formsProvider from '@cerebral/forms';            // v.3.2.2
import { setField } from '@cerebral/forms/operators';


export default Module({
    providers: {
      forms: formsProvider({
        errorMessages: {
          isEmail () { return 'Email address is not valid'; }
        }
      })
    },
    state: {
      form: {
        emailAddress: {
          value: '',
          isRequired: true,
          validationRules: [ 'isEmail' ]
        }
      }
    },
    signals: {
      emailAddressChanged: [ setField(module`form.emailAddress`, props`value`) ]
    }
});
```
When the `emailAddressChanged` signal is invoked, the `setField` operator throws the following error:  

> Cerebral Forms - operator.setField: You have to use the STATE TAG as first argument

The exception happens in `@cerebral/forms/lib/operators/setField.js`, line 12.

To work around the problem for now, I have to just avoid using the `module` tag in conjunction with `setField` and instead define the module using a function so I can use the `module` argument with its `path` property:

```JavaScript
import { Module } from 'cerebral';                      // v.4.2.2
import { props, state } from 'cerebral/tags';
import formsProvider from '@cerebral/forms';            // v.3.2.2
import { setField } from '@cerebral/forms/operators';


export default Module((module) => {
  return {
    providers: {
      forms: formsProvider({
        errorMessages: {
          isEmail () { return 'Email address is not valid'; }
        }
      })
    },
    state: {
      form: {
        emailAddress: {
          value: '',
          isRequired: true,
          validationRules: [ 'isEmail' ]
        }
      }
    },
    signals: {
      emailAddressChanged: [ setField(state`${module.path}.form.emailAddress`, props`value`) ]
    }
  };
});
```

**Comment by aguilera51284** [comment]
try with `string` tag before the `state`tag.

**Comment by cwilso03** [comment]
@aguilera51284 - Unfortunately, it's the same error.  To be clear, the second block of code in my original post works -- it's the workaround I've employed.  The first block of code, using the `module` tag rather than `state` tag, is the one that fails.  Applying your suggestion, though, I tried changing the relevant line to read: 
```JavaScript
setField(string`${module`form.emailAddress`}`, props`value`) 
```
but it still fails with the same error ("You have to use the STATE TAG as first argument").

**Comment by christianalfoni** [comment]
Housekeeping!
