### ISSUE TITLE
How to add custom error pages (e.g. 404) to @cerebral/router?

### ISSUE THREAD

**Issue by cwilso03** [cerebral/cerebral#1358]
Is there a way to add custom error pages to @cerebral/router, such that, for example, a non-existent URL request could land the client on a custom 404 page?  

Alternatively, is there a way to trap errors thrown by @cerebral/router?  I tried a `catch` property in the options passed to the `Router()` definition (hoping it worked like `Module()`), but it didn't seem to catch anything.

Note I ran across this need while debugging a direct link into a page in my app that uses parameters.  The parameter string had a parsing error that got thrown by @cerebral/router, and I got a generic "Error: Could not parse url" error page (I'm guessing from React's dev mode).  (Actually, the same error reported here:  https://github.com/cerebral/cerebral/issues/1259)

**Comment by aguilera51284** [comment]
in you file `router.js` try with this `{path:'/*',  signal: 'signal.catch'}`
