### ISSUE TITLE
Very simple cerebral app with browserify does not bind to datastore properly

### ISSUE THREAD

**Issue by wrouesnel** [cerebral/cerebral#136]
I've pared this problem down to the most minimal example I can - available in this gist: https://gist.github.com/wrouesnel/8a411db83a4b258afac9

The basic problem seems to be that nothing from cerebral is getting bound to the react components. If the example above is working, the `<h1>` field should have "Bughunter" in it.

**Comment by wrouesnel** [comment]
After some back and forth on gitter, I tried the cerebral webpack boilerplate and compared it to my boilerplate. The latest versions of babel and babelify appear to break everything (or else there's some dark voodoo in the presets I don't understand).

Updating my package.json to this (note the babel and babelify versions)
```
{
  "name": "cerebmin",
  "version": "0.0.1",
  "description": "a minimal example of a cerebral bug",
  "main": "main.js",
  "dependencies": {
    "babel": "^5.8.23",
    "babelify": "6.4.0",
    "baobab": "^2.1.1",
    "browserify": "^12.0.1",
    "cerebral": "^0.24.0",
    "cerebral-baobab": "^0.4.2",
    "cerebral-react": "^0.6.0",
    "gulp": "^3.9.0",
    "gulp-util": "^3.0.7",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "vinyl-source-stream": "^1.1.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

and tweaking my gulpfile to use the 6.4.0 babelify syntax:
```
var gulp = require('gulp');
var gutil = require('gulp-util');

var source = require('vinyl-source-stream');
var browserify = require('browserify');
var babelify = require('babelify'); 

gulp.task('bundle', function() {
    var bundler = browserify({debug:true, fullPaths: true})
        .transform(babelify.configure( {
            ignore: /node_modules/,
            stage: 0
        }))
        .require('./main.js', { entry: true });
    
    return bundler.bundle()
        .on("error", function(err) {
            gutil.log('Browserify error:', err);
            this.emit('end');
        })
        .pipe(source('./bundle.js'))
        .pipe(gulp.dest('.'));
});


gulp.task('default', ['bundle']);
```
everything started working properly.

So there's definitely a problem with using cerebral with newer babel 6 it looks like, in the configuration I have above.

**Comment by wrouesnel** [comment]
Closing this since technically it's resolved. But beware babel 6!

**Comment by christianalfoni** [comment]
Thanks for adding your input as your progressed to a solution :-)
