### ISSUE TITLE
function-tree and TypeScript

### ISSUE THREAD

**Issue by nikolay-borzov** [cerebral/cerebral#1363]
function-tree: 3.2.2

Is it possible to use function-tree on a project with TypeScript?

Take the example from docs:
```
import { sequence } from 'function-tree'

function someFunction(context) {}
function someOtherFunction(context) {}

module.exports = sequence([someFunction, someOtherFunction])
```

TypeScript says that actually, I need to pass an array of arrays to sequence. Is this docs problems? 

On the previous version we used (3.2.0) `sequence([someFunction, someOtherFunction])` worked fine.

I see that `function-tree` has `fluent` module, but I cannot find any docs explaning how to use it

**Comment by Guria** [comment]
In theory [cerebral typescript doc](https://cerebraljs.com/docs/guides/typescript) could help fit function-tree fluent as well.
Though please ask here or on Discord in case of any misunderstandings.

You can also take a look at [action-tree](https://github.com/cerebral/overmind/tree/next/packages/node_modules/action-chain) / [overmind](https://github.com/cerebral/overmind/tree/next/packages/node_modules/overmind) happening in sibling repo which is rewritten in typescript from scratch. It's in active development right now, but you can already try it now, including brand new devtools. I strongly recommend to join Discord to follow updates.

**Comment by nikolay-borzov** [comment]
My mistake, type definition for `sequence` is valid
