### ISSUE TITLE
best practices for building modular cerebral apps

### ISSUE THREAD

**Issue by tnrich** [cerebral/cerebral#137]
Hey there, I wanted to start this issue to see what the community has to say about building modular/reusable chunks of state+signals with cerebral. 

My ideal solution would allow you to build the separate pieces of your app as self contained modules, but which still allow for cross talk if necessary. 

The cerebral website has a brief snippet about organizing the code in "modules" for larger apps, but I was wondering if people have been following that paradigm, and if so, with how much success. Please post examples of your modular cerebral code if you've got it!

Thanks!

**Comment by NervosaX** [comment]
I wrote an application runner for our projects at SalesPreso. https://github.com/salespreso/sp-application
I was given permission to share this, but it's not in a completely runnable form (depends on some private repositories.) I might get to cleaning this up to be runnable from anywhere one day. Any way,
it lets you register classes as an app, which contain store data/routes/signals. The final runner pieces them together and namespaces all the signals and store data. We're still in the early days of using it however.

**Comment by saulshanabrook** [comment]
I [posted](http://www.saulshanabrook.com/organizing-cerebral-code/) a while ago about seperating out my code in different modules.

**Comment by NervosaX** [comment]
@saulshanabrook Our approaches are very similar, down to the django roots. :)

**Comment by christianalfoni** [comment]
Lets focus on the `cerebral-modules` project @garth and @Guria has been exploring. Will release more info as we get closer to a release on that :-)
