### ISSUE TITLE
Suggestion: Allow promise implementation to be overridden

### ISSUE THREAD

**Issue by NervosaX** [cerebral/cerebral#1373]
It would be nice if you could pass through the library used for promises into cerebral. Currently I have an action like the following:

```javascript
import Promise from "bluebird";

export function myAction({ path }) {
  return doAThing()
    .then(() => {
        return path.success();
    })
    .catch(e => {
        return Promise.resolve(path.error())
            .throw(e);
    });
}
```

I then have global sentry error catchers to deal with logging. It would be nice if I could switch it to bluebird to get a simpler:

```javascript
    .catch(e => {
        return path.error().throw(e);
    });
```

Thoughts?

Edit:

Looks like calling .throw() after calling path.error() will break the app here anyway. Might have to tackle this from another angle.

**Comment by christianalfoni** [comment]
Housekeeping!
