### ISSUE TITLE
Various pages returning 404 in the docs.

### ISSUE THREAD

**Issue by zocheyado** [cerebral/cerebral#1376]
Trying to find a way to polyfill signal state routes in internet explorer. Found out that both the internet explorer polyfill page https://cerebraljs.com/install/internetexplorer and the signals page https://cerebraljs.com/docs/api/signal.html (from google) go to nothing. Any link to the current versions of this? 

Or better yet if someone knows how to polyfill the string template setup you use in signals for Cerebral 
```
  set(state`app.myStateValue`, props`stateValue2`)
```

**Comment by christianalfoni** [comment]
Hi!

We have been discussing how to expsoe old versions of the website, though it is a rather difficult and time is such a constraint :-/ You can use the release section of github to find your version and then open the repo at the point in time. The docs are in this repo. 

Very sorry for the inconvenience on this :-/
