### ISSUE TITLE
Improve controller events

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral#138]
I think the controller events could need a little upgrade to be more informative/useful.

Before I create a pull request I would to like to clear a few things up:

The expected event flow should look like this - right?
```
signal-start
  action-start/end
  action-start (with state modification)
  controller-change
  action-end (with state modification)
  action-start/end
signal-end
controller-change
```

Would it make sense to pass the initiator to the change event along with the new state?
e.g. { signal, recorder, state }

Could there be anything else I might want to pass along with a signal event other then the signal itself?
Should I pass `{ signal }` or `signal` - I would prefer the first due to flexibility.

Why is [there](https://github.com/cerebral/cerebral/blob/master/src/CreateSignalFactory.js#L158) a change event fired after the `actionStart`.

**Comment by christianalfoni** [comment]
Hi @maxfrigge,

Yup, you are correct. Though the "change" event triggers whenever it meets an async action (explains your last question) or it is done running a set of sync actions.

I am not quite sure what you mean by "initiator"? I do not see that you would need anything else than the signal itself really. And signal + action on action events?

**Comment by mrmaxon** [comment]
By initiator I mean the source of the event - similar to currentTarget of ui events. I just thought it might be useful in the future to reason about a change event ... e.g. was it the recorder, an action, which action and so on. I can as well leave that out when I create the pull request.

Just out of curiosity: what's the reason for the change event when starting an async action? Shouldn't it be enough to fire when the action resolves?

**Comment by christianalfoni** [comment]
Ah, I see. Hm, yeah, lets find a scenario where it is useful first and then we can implement initiator :-)

The "change" event is what updates the UI. So if you have for example some synchronous actions making some state changes you want those state changes to be updated in the UI when any asynchronous actions starts.

An example would be setting an `isLoading = true` state to true before running an async fetch of data on server. If we did not trigger "change" before the async part of the signal started the UI would not get the `isLoading = true`, only the `isLoading = false` when the fetch resolves... which basically means no loading indication in UI :-)

**Comment by mrmaxon** [comment]
Ok. Got it... I think the whole change propagation is out of scope right now and could be talked about in another issue. I will create the pull request asap.

**Comment by christianalfoni** [comment]
Awesome :+1:
