### ISSUE TITLE
Using set factory to copy computed state to another area in the state copies the computed function.

### ISSUE THREAD

**Issue by NervosaX** [cerebral/cerebral#1381]
If you do something like this:
```javascript
set(state`myThing`, state`computedValue`)
```

You end up not copying the result of the computed function, but the function itself.

Here's an example of the issue happening:
https://codesandbox.io/s/5v6xnvryql

**Comment by christianalfoni** [comment]
Ah, yeah, noted, will fix for next release

**Comment by christianalfoni** [comment]
This is fixed for next release :)
