### ISSUE TITLE
Document example typo in Sequences.md

### ISSUE THREAD

**Issue by dance2die** [cerebral/cerebral#1388]
# 🤔 What?

A typo ⌨ in [Factories](https://github.com/cerebral/cerebral/blob/next/docs/introduction/sequences.md#factories) code example under [docs/introduction/sequences.md](https://github.com/cerebral/cerebral/blob/next/docs/introduction/sequences.md).

`const getUser` is defined with a method that retrieves a user from `jsonPlaceholder` object, which was not previously defined (nor in the scope).

```javascript
import App, { state, props, sequences } from 'cerebral'
...

const getPosts = ({ api }) =>
  api.getPosts().then(posts => ({ posts }))

const getUser = ({ api, props }) =>
  jsonPlaceholder.getUser(props.id).then(user => ({ user }))

const app = App({
...
}, {...})
```

# 🧐 Suggestion

According to [Providers](https://cerebraljs.com/docs/introduction/providers.html) documentation, `getUser` is defined under `providers.api` as shown below.

```javascript
import { App } from 'cerebral'
...
const app = App({
  state: {
  ...
  },
  providers: {
    api: {
      getPosts() {
        return fetch(`${API_URL}/posts`)
          .then(response => response.toJSON())
      },
      getUser(id) {
        return fetch(`${API_URL}/users/${id}`)
          .then((response) => response.json())
      }
    }
  }  
}, {...})
```

So I suggest a following change in the [Factories](https://github.com/cerebral/cerebral/blob/next/docs/introduction/sequences.md#factories) code example.

```diff
import App, { state, props, sequences } from 'cerebral'
...

const getPosts = ({ api }) =>
  api.getPosts().then(posts => ({ posts }))

const getUser = ({ api, props }) =>
-  jsonPlaceholder.getUser(props.id).then(user => ({ user }))
+  api.getUser(props.id).then(user => ({ user }))

const app = App({
...
}, {...})
```

# ➕ Additional Context

I could do a PR for the update if this is a valid issue.

And here is the demo.
![2018-11-30_21-14-58](https://user-images.githubusercontent.com/8465237/49323143-1877e980-f4e5-11e8-8033-30a9dfd9e60f.gif)

**Comment by christianalfoni** [comment]
Ah, yes, sorry for late response on this, but you are perfectly right. Noted for next release :)

**Comment by christianalfoni** [comment]
Fixed in next version :)

**Comment by dance2die** [comment]
Thanks @christianalfoni 😃
