### ISSUE TITLE
TypeError: state.get is not a function

### ISSUE THREAD

**Issue by grigio** [cerebral/cerebral#139]
Hi, I'm migrating to the current Cerebral but it seems the `state` is not complete..

``` javascript
export function setPage (pageName) {
  return function activePage (input, state, output, services) {
     debugger
     // here 
  }
};
```

`state.get()` is missing but I have:

```
state
Object {}concat: ()getComputed: (computedFunc)merge: ()pop: ()push: ()set: ()shift: ()splice: ()unset: ()unshift: ()__proto__: Object
```

**Comment by Guria** [comment]
Check if you have latest version of ~cerebral-baobab` as well

**Comment by grigio** [comment]
@Guria Thanks! I've replaced `cerebral-immutable-store` with `cerebral-immutable-js` and now it works again
