### ISSUE TITLE
Error in CodeSandbox - Could not find module in path: 'cerebral/proxy' relative to '/src/index.js'

### ISSUE THREAD

**Issue by dance2die** [cerebral/cerebral#1391]
# 🤔 What?

Following error occurs on CodeSandbox when using `create-react-app` template.
_Sandbox can be found [here](https://codesandbox.io/s/mj1517orpj)._

> Could not find module in path: 'cerebral/proxy' relative to '/src/index.js'

![image](https://user-images.githubusercontent.com/8465237/50116207-875c7e80-0217-11e9-8fe4-32af51db416c.png)

When you use ParcelJS template, the [same code](https://codesandbox.io/s/qz2xn1qvy6) works fine.

# ↔ Comparison between Create-react-app & Parcel versions.

![2018-12-17_16-21-51](https://user-images.githubusercontent.com/8465237/50116375-f5a14100-0217-11e9-9f9a-9d0e28c63c54.gif)

# ➕ Additional Context

I've been trying to use cerebral with a project created with `create-react-app` but haven't been able to get it working on a local machine as well even though the parcel version works.

Any help would be much appreciated 🙂

**Comment by xmeltrut** [comment]
I think it's an error in the documentation. Importing from the main package works fine:

    import { state } from 'cerebral';

**Comment by christianalfoni** [comment]
closing this, made note to update docs on this, thansk @xmeltrut !
