### ISSUE TITLE
State update not triggering re-render in React

### ISSUE THREAD

**Issue by xmeltrut** [cerebral/cerebral#1392]
If I do a state update, any component wired into that piece of state using the connect function updates. However, if I then pass that state down into a child component, even though the state is updated, the component will not re-render.

    // re-renders fine when I update modules
    export default connect(
        {
            modules: state.modules
        },
        class ModuleList extends Component {
            render() {
                return modules.map(module => <Module {...module} />);
            }
        }
    );

    // does not re-render even though the props have updated
    export default connect(
        {
            somethingElse: state.somethingElse
        },
        class ModuleList extends Component {
            render() {
                return (<div>{this.props.moduleNmae}</div>);
            }
        }
    );

**Comment by christianalfoni** [comment]
Yes, passing state plainly as properties does not work. Cerebral need to connect to it. The way you do this is by passing either the ID of the value you are passing, or an index. And then you use that information to connect to the value in the child component:

```js
connect({
  item: state`myEntities.${props`id`}`
}, ...)
```

So here we are passing an `id` to a child component and we use that id to look up the entity in the state. 

I have noted to write a guide on this! Let me know if something is unclear :-)
