### ISSUE TITLE
prevProps identical to props in componentDidUpdate

### ISSUE THREAD

**Issue by xmeltrut** [cerebral/cerebral#1393]
When using the `componentDidUpdate` lifestyle hook in React, the prevProps variable is supplied with the new props, rather than the old ones. For example, if I push a new element onto the lessons object:

    componentDidUpdate(prevProps) {
        console.log(prevProps.lessons.length);
        console.log(this.props.lessons.length);
    }

I get the result:

    3
    3

Rather than:

    2
    3

**Comment by christianalfoni** [comment]
Yes, this is because Cerebral is not immutable. If you need to do something related to a state change inside a component you use a reaction for that: https://cerebraljs.com/docs/advanced/reactions.html#reactions-reactions-in-views

I hope this helps, please reopen if not :)
