### ISSUE TITLE
Function trees, traversables, and applicatives

### ISSUE THREAD

**Issue by masaeedu** [cerebral/cerebral#1394]
Hi there. Someone pointed me to your very interesting function tree library [here](https://github.com/cerebral/cerebral/tree/master/packages/node_modules/function-tree) and I was reading your blog post [here](https://www.christianalfoni.com/articles/2016_09_11_The-case-for-function-tree) that explains the use case.

I was wondering if you've played around with the concept of traversable and applicative functors, and in particular the applicative functor instance for functions themselves. Together, these tools provide a different approach for solving the problems described in your blog post.

For example here's how threading an argument throughout various containers of functions can be done using traversable containers and the function applicative instance:

```js
const add = x => y => x + y
const times = x => y => x * y

// We can turn an array of integer-accepting functions into an integer-accepting
// function that produces an array
const farray = [add(1), times(2), add(3), times(4)]

console.log(Arr.sequence(Fn)(farray)(2))
// => [3, 4, 5, 8]

// We can do the same with objects
const fobj = { foo: add(1), bar: times(2), baz: add(3), quux: times(4) }

console.log(Obj.sequence(Fn)(fobj)(2))
// => { foo: 3, bar: 4, baz: 5, quux: 8 }

// And similarly for trees
const ftree = [add(1), [
  [times(2), [
    [add(3), []]
  ]],
  [times(4), []]
]]

console.log(RoseTree.sequence(Fn)(ftree)(2))
/* =>
[3, [
  [4, [
    [5, []]
  ]],
  [8, []]
]]
*/
```

Runnable snippet [here](https://runkit.com/masaeedu/inverting-containers-full-of-functions).

Several other features (error handling, asynchronicity, etc.) can also be dealt with by appropriate choice of applicative functor. The applicative functor instances for Promises, Eithers, and the concept of functor composition are useful in this regard. I'm handwaving a lot of details, but I thought you might find this a fruitful avenue for exploration given your use case (if you haven't already looked at all this stuff).

**Comment by christianalfoni** [comment]
Hi @masaeedu and thanks a bunch for adding perspectives :)

The `function-tree` project started out from Cerebral actually (it was later split up). So there has been a lot of iterations to get to where the project is today. It really started out with being able to debug a sequence of logic. It was all driven by the Cerebral devtools. It was not clear to me how I could use lower level and more general functional concepts to achieve this, though I have learned a bit over the years :) 

In the latest project I created this [op-op](https://github.com/christianalfoni/op-op-spec) spec which is much closer to a more pure functional style than function-tree is.  It is being used in [overmindjs](https://overmindjs.org).

function-tree will stay as it is, though I really appreciate the input, as maybe I am starting to grasp these deeper functional concepts more :-)
