### ISSUE TITLE
todomvc-ts demo doesn't work

### ISSUE THREAD

**Issue by user1736** [cerebral/cerebral#1395]
Greetings!

Todo demo doesn't work in `next` branch. Problem seems to be caused by injecting unevaluated values for `computed`

Also I made a [simple example](https://codesandbox.io/s/kk1wqpxymv) to illustrate this problem.

**Comment by christianalfoni** [comment]
Hi there and sorry for an extremely late answer :)

The new version coming out now fixes issue with computed. Also a new example will be provided in the docs
