### ISSUE TITLE
'xxx' of undefined by computed with props

### ISSUE THREAD

**Issue by seulgi0711** [cerebral/cerebral#1396]
This issue happened again. Perhaps I think this code is the problem.

https://github.com/cerebral/cerebral/blob/3334ce55b38d9fc26f840c0f6ef0545470b2eff1/packages/node_modules/cerebral/src/Compute.js#L151

'xxx' of undefined error occur, when calculating initial value.

How about assigning empty object?

**Comment by christianalfoni** [comment]
Do you have a small reproducible example of this? Maybe in a codesandbox? :)

**Comment by seulgi0711** [comment]
https://codesandbox.io/s/wnqv7n0pzl

This is simple example code. But this code does not make the error.
So I tested my local code...

When I use cerebral-devtools the error occur

```js
/* ... */
const app = App(store, {
  devtools: Devtools && Devtools({
    host: 'cerebral-debugger.dev:3001',
    https: true
  })
});
```

**computed.js**
```js
/* ... */
export const logById = get => {
  const logs = get(state`logs`);
  const logId = get(props`logId`);
  return logs.find((log) => log.id === logId);
};
/* ... */
```
I think... The devtools run computed value to get initial value right after devtools run. It's run without props. That make error.

![image](https://user-images.githubusercontent.com/7961148/52522382-0d50ef00-2cc8-11e9-81c9-d29cc482c82a.png)

**Without devtools?**

```js
const app = App(store, {
  // devtools: Devtools && Devtools({
  //   host: 'cerebral-debugger.dev:3001',
  //   https: true
  // })
});
```

No error

![image](https://user-images.githubusercontent.com/7961148/52522496-7422d800-2cc9-11e9-991b-d2a42cb6558f.png)

**Comment by christianalfoni** [comment]
@seulgi0711 So sorry about late answer here, but this is fixed in `next`. It will be released very soon, thanks a bunch for helping out!

If you download and try out this Sandbox you should be good :) https://codesandbox.io/s/m9o6k4q6j9 . The `next` version has a completely refactored observable concept which improves performance, predictability and a few bugs

**Comment by wrumsby** [comment]
@christianalfoni I'm trying `@next` and it addresses the issue mentioned above, but I now have issues accessing those computed values when using TypeScript. Unsure if I'm doing something wrong, but if I have:

```ts
const nullProject: Project = {
  id: '',
  name: 'Unknown'
};

export const project = Compute<Project>(get => {
  const id = get(props`projectId`);
  const projects: ReadonlyArray<Project> = get(state`projects`);

  const result = projects.find((p: Project) => p.id === id) || nullProject;

  return result;
});
```

In my main module `project` is in both `state` and `computed`, e.g.:

```
const module: ModuleDefinition = {
  state: {
    project,
    // other things
  },
  computed: {
     project
  },
  // other things
};
```  

and I try to use this in a Component like this:

```ts
interface Props {
  projectId: string;
}

interface Deps {
  project: Project;
}

export const ProjectOverview: React.SFC<Props & Deps & ConnectedProps> = ({
  project,
  get
}) => {
  const routeToProject = get(sequences`routeToProject`);

  return (
    <button
      className="btn btn-light btn-block my-0 text-left"
      onClick={() =>
        routeToProject({
          params: { projectId: project.id }
        })
      }
    >
      {project.name}
    </button>
  );
};

export default connect<Props, Deps>(
  {
    project: state`project`
  },
  ProjectOverview
);
```

`project` is _not_ the value returned by the my compute function - `project.value` _is_. Am I doing something wrong or is this a bug? It feels strange, maybe I have my `deps` set up incorrectly?

**Comment by christianalfoni** [comment]
@wrumsby Thanks for the example and testing! This is related to an other bug reported as well. I will look into this ASAP so that we can get the next version out the door. Will let you know :)

**Comment by christianalfoni** [comment]
@wrumsby Do you have time to test something? Could you make sure that you also install `@cerebral/react@next`? I have a feeling that package now installs its own version of Cerebral. You can check this by looking into `node_modules`. Just check if `@cerebral/react` has its own node_modules with cerebral installed.

Make sure all packages uses `@next` :)

**Comment by wrumsby** [comment]
Hi @christianalfoni installing `@cerebral/react@next` does resolve the issue I saw.

Looking at the `package.json` for the installed version of `@cerebral/react` I see:

```json
{
  "dependencies": {
    "cerebral": "^5.1.1-1557067149174"
  }
```

which matches the version of the installed version of `cerebral`.

**Comment by christianalfoni** [comment]
Okay great! Then I consider it ready for release, putting it together now :)

**Comment by christianalfoni** [comment]
I believe this is okay now?
