### ISSUE TITLE
compute from computed from another computed does not work

### ISSUE THREAD

**Issue by bernhardreisenberger** [cerebral/cerebral#1397]
Dear Cerebral Folks,

I have an issue with computing state from other computeds and i guess it is a bug.
As stated in the docs, it is perfectly right to compute state on previous computeds. In my application, i compute state on computeds, which themselves where computed from computeds. 
This works for the depth of 2 computeds (computedB -> computedA -> stateX)
For the depth of 3 computeds (computedC -> computedB -> computedA -> stateX) it does not work anymore. The computedC will not be called even though computedB has changed.

I have reproduced the issue using codesandbox: https://codesandbox.io/s/6v3637mm8n

Thanks in advance.

**Comment by codyseibert** [comment]
We've seen something similar as well, so we no longer try to use computeds inside other computeds.

**Comment by christianalfoni** [comment]
Hi there!

Sorry for mye late response. I am just sitting down to do a full refactor of computeds. The additional strategy was to make them reactive (subscribe to each other), but a more solid implementation is to make the computeds inherit from each other instead. This ensure that all computeds runs isolated and does not depend on anything. This is what has caused a lot of challenges.

So stay tuned for a refactor, starting now :-)

**Comment by christianalfoni** [comment]
Okay, so the `next` branch is now running the refactored version of the code. I updated the codesandbox and the issue seems to have been fixed: https://codesandbox.io/s/j2xw5zqrnw.

It will require a bit more evaluation, but the approach taken here fits the scenario better than the previous "reactive subscription" model. So feel very confident it is solved :)

You can try out by installing `npm install cerebral@next @cerebral/react@next`

**Comment by bernhardreisenberger** [comment]
Hi.

I am back from my vacation, and the issue is fixed. What a great service. Thank you very much.

Unfortunately i discovered a behavior change with the next version. :-(
Accessing an object value within the connect() does not work as before. e.g.

> connect(
>   {
>     firstVal: state.a[props.firstElem],
>   }, ...)

This was working with version 5.1.0
props.firstElem is a property that gets passed as attribute to the component
see https://codesandbox.io/s/0qwo6x471l for the whole setup

**Comment by christianalfoni** [comment]
Hi @bernhardreisenberger!

Thanks a bunch for helping out battle testing the change :) I will look into the issue shortly and update!

**Comment by christianalfoni** [comment]
Hi man and so sorry for late response here. Been through a couple of weeks sick, then holiday stuff etc.

It was just a tiny typo causing this. Please install latest next. If you are happy I will release this, cause the next version is already tested on a very complicated project and running like butter :)

**Comment by bernhardreisenberger** [comment]
No problem. Good that you are well again.

I have tested latest next, and it works fine. Thank you.
