### ISSUE TITLE
Allow providers to have keys other than functions

### ISSUE THREAD

**Issue by miraage** [cerebral/cerebral#1398]
I was trying to create a history provider via `history` package:
```
import createBrowserHistory from 'history/createBrowserHistory';

const root = App({
  providers: {
    history: createBrowserHistory(),
  },
});
```
And the result is: `Error: The property length passed to Provider is not a method`.

What I've digged, that `function-tree` assumes, that each key under provider is a function, which is a very wierd scenario. For example, we might want to share an external configuration, which is `Object<String, Any>`.

https://github.com/cerebral/cerebral/blob/0a34b66/packages/node_modules/function-tree/src/Provider.js#L29

There is a code
```js
const originalFunc = definition[key]

wrappedProvider[key] = function(...args) {
  const providerResult = originalFunc.apply(this, args)
  ....
}
```

What would be cool to see here is
```js
const orig = definition[key]

if (typeof orig !== 'function') {
  wrappedProvider[key] = orig;
  return;
}

wrappedProvider[key] = function(...args) {
  ....
}
```

**Comment by christianalfoni** [comment]
Hi there and so sorry for extremely late reply. Been in a transition with work, family, other open source stuff etc.

Ah, yeah, I see what you mean here. Though a "hidden feature" of providers is that you want the provider to be a contract between your app and the 3rd party tool. Basically you decide an API that makes sense for your app an then in this case "history" provides that functionality. That makes it much easier for you to replace that tool, use multiple APIs from the 3rd party tool behind a single method you provide to your application etc.

Hope that made sense or please reopen if you want to discuss more :)
