### ISSUE TITLE
How to set-up an async data stream

### ISSUE THREAD

**Issue by AidanNichol** [cerebral/cerebral#140]
I'm trying to use Cerebral with a pouchdb/couchdb document database. Everything is work nicely but I'm struggling to see what is the correct way to handle a stream of async events telling me about updates made by other users.

I want to something like
```javascript
    db.changes({live: true, include_docs: true})
          .on('change', (change)=>{controller.signals.syncDoc({doc: change.doc})});
 ```
I need access to both **db**, which is a service, and  to **signals** to trigger the required actions. Where is the correct place to put this type of code.

The documention mentions firing signals as a result of something happening on a websockets connection, which is similar to what I'm trying to do, but I haven't found anywhere to give me a clue as to how to set that up.

**Comment by christianalfoni** [comment]
Hi @AidanNichol,

This is a good question :-) I suggest inserting this logic into the `componentDidMount` of the component that is mounted in regards of handling this kind of logic. Might be the main root component or maybe you only want to listen to these changes when you load a specific page in your app. And you use `componentWillUnmount` to stop firing off the signals by removing the change listener.

As with websockets, this is some external event, just like a click event. I think it makes more sense to start/stop listening and fire the signals from "outside" Cerebral, but there are discussions on doing this as a service also.

Hope this made sense :-)

**Comment by AidanNichol** [comment]
Thanks @christianalfoni that makes sense.

In my case it is needed application wide and so doing it in ```componentDidMount``` of the App makes sense.

However, at this point I don't have access to the ```db``` service. I could just do a ```import db from 'dbService'``` but that doesn't feel right.
I am sending an ```appMounted``` signal and it would make it cleaner and more predictable if ```db.changes(...).on(...)``` was issued in an action after the other housekeeping had finished. But when I'm in actions I don't have access to signals.
 I could do
```this.props.signals.appMounted({syncDoc: this.props.signals.syncDoc});```
but feels like a kluge too.

The other wrinkle is that ```db.changes(...).on(...)``` returns an object with a ```cancel``` method  to stop it firing events and I may need to make that available for ```componentWillUnmount```. From an action I could save it to state but then I have to feed it back in through props and that feels wrong too.

**Comment by christianalfoni** [comment]
Ah, yes, you make some very good points here!

If you check out this: https://github.com/cerebral/cerebral/issues/129 (enough to look through last comments :-) )

And this: https://github.com/garth/cerebral-modules

This is seem to be an official part of Cerebral very soon. We are reviewing it shortly, but please let me know if you feel this is in the right direction.

**Comment by AidanNichol** [comment]
Yes - the proposal in #129 to make ```controller``` accessible to the service would do it nicely.

If I didn't want to initiate the stream until other housekeeping had completed then it could be exposed as a method by the service and invoked from an action at the appropriate time.

I look forward to trying it.

**Comment by christianalfoni** [comment]
Cool, I will just close this one in the meantime. We are exploring modules first. See how far we can take them to solve these kinds of scenarios. Services is also a way to go, but will see how it fits with modules first :-)
