### ISSUE TITLE
Change in computed state does not trigger reactions

### ISSUE THREAD

**Issue by atanas-angelov-dev** [cerebral/cerebral#1400]
A reaction depending only on a computed state will never be called. I encountered this locally and reproduced it based on the counter sandbox example:
https://codesandbox.io/s/2k962vopn

As you can see, changes to the computed value do trigger a component render (you can even remove the `count` state dependency and it will still render) but do not trigger the reaction (neither `reactionCalls` increments nor `console.log` gets called). 

If you add `count: state'count',` to the reaction state dependencies the reaction will get called (this is the current workaround I have to use for my project).

**Comment by christianalfoni** [comment]
Hi there!

This is fixed in `next`, https://codesandbox.io/s/0xxmp00630

**Comment by christianalfoni** [comment]
Closing, please reopen if still issue :)
