### ISSUE TITLE
A certain combination of feature usage causes forceUpdate() on an unmounted component

### ISSUE THREAD

**Issue by atanas-angelov-dev** [cerebral/cerebral#1401]
Repro case:
https://codesandbox.io/s/koz63xy3ro

Open the console, click on the unmount button **once** and wait a second - the "update on unmounted component" error will show up.

Key points to reproduce this:
1.Have computed state that depends on **2 OR MORE** other computed states. This does not work when it only requires a single other computed state value. In the repro case `someComputed` uses `someInternalComputed1` and `someInternalComputed2` which yield the same value - `someState`.
2. Connect component A to `someComputed`.
3. Have component B which conditionally renders component A based on some state value which we will flip to unmount component A.
4. Have a sequence which consists of:
  1. Any async action. In the repro case I used `wait(1000)`.
  2. Flip the state which will cause component A to be unmounted
  3. Change the state that powers all of the internal computed state.
5. Run the sequence.

It is quite convoluted but I currently have this issue in a real world project.

**Comment by christianalfoni** [comment]
@atanas-angelov-dev This seems to be fixed in `next`, to be released soon :) https://codesandbox.io/s/l285qnx03z
