### ISSUE TITLE
module.signals is DEPRECATED but controller in @cerebral/mobx-state-tree can't provide sequences

### ISSUE THREAD

**Issue by R4M80MrX** [cerebral/cerebral#1406]
module.signals is DEPRECATED but controller in @cerebral/mobx-state-tree can't provide sequences

**Comment by christianalfoni** [comment]
Hi there. That package is for the old version of Cerebral. Version 5 does not have any addons due to maintainability issues. Sorry, but had to make that choice to prevent the project from consuming my life :)
