### ISSUE TITLE
Docs test page spelling error

### ISSUE THREAD

**Issue by idream3** [cerebral/cerebral#1409]
Hi

https://cerebraljs.com/docs/api/test.html

`import { runComputed } from 'cerebral/test'` 

should be

`import { runCompute } from 'cerebral/test'` 

:)

**Comment by christianalfoni** [comment]
I believe it is already fixed, just not deployed :) Look at `/docs/api/test.md` in this repo and you should see it fixed. Nice catch though! :)

**Comment by christianalfoni** [comment]
Closing it as I believe it is already fixed :)
