### ISSUE TITLE
When using devtools, cannot change store state using string path. 

### ISSUE THREAD

**Issue by cyrusbowman** [cerebral/cerebral#1410]
When using devtools I get the following error:

> You are extracting a path from an argument that is not a Tag.

Using a tag instead of a string ie. `store.set(state`title`, 'Bacon')` works as expected.

@cerebral/react v4.1.1
cerebral: v5.1.1

Action:
```
function changeTitle({store}) {
  store.set('title', 'Bacon')
}
```

![CerebralError](https://user-images.githubusercontent.com/2474343/65654553-3ddf6200-dfe7-11e9-9f02-2c64020b7a69.gif)

**Comment by christianalfoni** [comment]
Hi there!

This is fixed in the next release. You can try it by installing `npm install cerebral@next`, make sure you use `next` tag also for your view layer package :)
