### ISSUE TITLE
codesandbox.io using wrong cerebral version.

### ISSUE THREAD

**Issue by cyrusbowman** [cerebral/cerebral#1411]
When clicking the Open [`Codesandbox.io`](https://codesandbox.io/s/qj183506) link from the docs. Codesandbox is using `v6.0.0-1538588845222` of cerebral which is not the latest version.

It looks like it was published on npm about a year ago before moving to 5.0.1-1539631428220

**Comment by christianalfoni** [comment]
Actually Codesandbox has moved to https://overmindj.org , the successor of Cerebral. Written in Typescript for epic support :)

Cerebral is still my "go to" for JavaScript based apps, but Overmind has far better typing support.
