### ISSUE TITLE
Cerebral v4: Deprecated React lifecycle methods

### ISSUE THREAD

**Issue by JohannesAnd** [cerebral/cerebral#1415]
The following lifecycle methods are currently causing deprecation warnings with React v16.9
- componentWillMount
- componentWillRecieveProps
- componentWillUpdate

as they are added in the HOC used by connect.

Are there any plans to fix this and make cerebral compatible with upcoming React v17?

EDIT: I see this has already been fixed in cerebral v5. Any plans of fixing it for v4, or do we simply have to migrate?

**Comment by christianalfoni** [comment]
Ah, sorry @JohannesAnd , have to migrate :-/ Or you can copy the code off node_modules and just import your own version where it is fixed :)
