### ISSUE TITLE
Can't resolve nested value via moduleState (from computed)

### ISSUE THREAD

**Issue by dmitrykatalkin** [cerebral/cerebral#1425]
The same [issue](https://github.com/cerebral/cerebral/issues/1408) but for computed.

**Comment by christianalfoni** [comment]
@dmitrykatalkin Hm, do you have a codesandbox example of the issue? Just helps me dive right into the issue 😄

**Comment by henri-hulski** [comment]
This is fixed in c99586b92caa6c26afa1d4d00d0da87ea3c2248a.
