### ISSUE TITLE
access dotted keys

### ISSUE THREAD

**Issue by bernhardreisenberger** [cerebral/cerebral#1429]
This is a reference to #1321 .

I guess this was asked before, but i cannot find the answer.

`set(state.domains['example.com'], 'example.com') ` will result in the following error:
> "factory.set(state\`domains.example.com\`, example.com)" has an error: Cannot read property 'com' of undefined

Is there a way, to have keys with dot in it?

**Comment by christianalfoni** [comment]
HI @bernhardreisenberger 

There is no way to safely have `.` as we need some kind of separator and `.` was chosen. You will have to convert the `.`s yourself to some other key 😭
