### ISSUE TITLE
Support "all" mutations

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#143]
@edgesoft suggested to support methods like "mergeAll" and "setAll". We could do this in one batch also adding "mergeMany" and "setMany". Examples:

```js
function MyAction(input, state, output) {
  state.mergeAll(['items'], {completed: true});
  state.mergeMany(['items'], [0,4,6,8], {completed: true});
  // Same for setAll and setMany
}
```

Just throwing it out here first to see how people feel about it :-)

**Comment by Guria** [comment]
was it done?

**Comment by christianalfoni** [comment]
Nopes, not added these yet. Does not seem to be much demand for it. Personally I do not miss them

**Comment by Guria** [comment]
closing it then
