### ISSUE TITLE
modules: service registered in init method got overwriten

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#153]
module:
```js
module.exports = {
  init: function({controller, name}) {
    controller.services[name] = {
      someService: function thatShouldKnowRegisteredName() {
      }
    }
  }
}
```

after `controller.register()` `controller.services[name]` would be overwriten with `undefined` because of this line: 

https://github.com/cerebral/cerebral/blob/7ab740b852b400e5cbcb6cb874854434e16dcc9b/src/CreateRegisterModules.js#L36

**Comment by christianalfoni** [comment]
Ah, yeah, not good... have to fix that :-)

**Comment by christianalfoni** [comment]
Okay, fixed in next version
