### ISSUE TITLE
recording issue

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#154]
* open todomvc demo
* add todo item
* click Record
* mark todo item as completed
* clear completed
* click stop
* click play

original state seems wasn't restored. and we got an error while trying to replay:
`VM1706:12 Uncaught TypeError: Cannot read property 'completed' of undefined`

**Comment by christianalfoni** [comment]
Ah, I suppose you hit record while async action was running. That should not be possible. Let me fix that

**Comment by christianalfoni** [comment]
Okay, deploying fix now

**Comment by Guria** [comment]
i am sure that i waited

**Comment by christianalfoni** [comment]
Hm, strange, I got the problem when hitting record while the todo was saving. But not when it was done saving. It has been deployed now, could you try again?

**Comment by Guria** [comment]
can't see any updates in repo

**Comment by christianalfoni** [comment]
Ah, thought you were testing at www.christianalfoni.com/todomvc ... pushed to repo as well now

**Comment by Guria** [comment]
Still have this issue on repo demo. I run it with `npm run demo`.
Btw could you tell more about how you prepare `todomvc.js` for site? just `npm run deploydemo` or something else?

**Comment by Guria** [comment]
I have tried different node versions to build. no luck

**Comment by Guria** [comment]
`nvm use 0.10` + `npm test` fails on `should play back recording`
Maybe it is somehow related.

**Comment by Guria** [comment]
At the same time I have no issue at site

**Comment by christianalfoni** [comment]
Hm, this is really strange. Yeah, I noticed the problem with old Node version on recording. Not sure why... though 0.10 is pretty old.

Yeah, just `npm run deploydemo` and I copy the dist over to the EmptyBox project (where my blog runs)

And you are running in Chrome?

**Comment by Guria** [comment]
Yes. 49.0.2593.0 dev-m
Hmm, maybe dev is a case. But it works with your build. Will try to investigate more

**Comment by christianalfoni** [comment]
Okay, cool! :+1:

**Comment by Guria** [comment]
@christianalfoni could you try to make fresh `clone` + `npm i` and then build repo again?

**Comment by christianalfoni** [comment]
Did that, still works, hm. Bring some of the other guys here to test also. Really weird

**Comment by Guria** [comment]
@christianalfoni good news. new modularized demo works without issues on my side.
