### ISSUE TITLE
Questions about modules

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#156]
### Q: How should you pass configuration to modules?

I need to instantiate a module with the API endpoint URLs that are stored in my main app. Currently, the code instantiates the module with a configuration object which will be passed to action and signal factories. Is this the best way to pass in static configuration to a module?

I tried to add the configuration object to the module, (right next to the signals, services and init() method) but I wasn't able to access it from the module's Component.

### Q: How should you confiugre a module to interact with the state tree?

The Login module renders a login form and performs an AJAX call to log the user in. It then puts the response into the state tree. The Login module shouldn't need to know the data model of the app that is using it so we need to tell the module where in the state tree to put things. I'm doing this by passing the module constructor some static configuration that includes the paths that the module should use for its state. Is this a good way to do it?

### Q: How should modules trigger events?

Or to put this another way, How should modules talk to each other?

Let's say the Login module was able to detect when the user's session was no longer valid. At that point, I would like to be able to trigger some sort of event to tell the app using the module that this has happened.

My first guess on how to implement this would be by having the app listen for changes on part of the state tree. However, this couples the app and the module together more than I would like since the app now needs to know which node to listen to and the details of how the module will modif the state tree.

My second guess would be to pass a callback to the module as static configuration to be called in the signal output handler. Or, pass in a service to be called once the credentials are no longer valid. Both of these approaches also couple the app and the module together by requiring that the Login module know to use this service and its API.

Another use case for this is for the app to be notified of when the user is logged in without the module needing to know to call a specific service/signal of the app or some other module.

### Q: Should/can modules have "private" state that is stored in the state tree?

I ran into the situation with the Login module where I set a isLoading flag before and after an AJAX call. This state is really only useful for the Login module but I still want to store it in the state tree for debugging purposes. It feels irresponsible to have a module add data to the state tree that the app is not expecting. Is there a best practice for this?

**Comment by christianalfoni** [comment]
### A: How should you pass configuration to modules?

Pass the options by
```js
controller.register({
  someModule: SomeModule({
    foo: 'bar'
  })
})
```

Expose the options by returning them from the module. These options will be available on `props.modules.someModule.options`.
```js
export default (options = {}) => {
  return {
    init({name, controller}) {
      return {
        options
      };
    }
  };
}
```

Or put the options inside a shared file. This only works if the module is supposed to have one instance.

```js
// Inside module.js
import sharedOptions from './sharedOptions';

export default (options = {}) => {
  return {
    init({name, controller}) {
      sharedOptions.set(options);
    }
  };
}

// Inside SomeComponent.js
import sharedOptions from './sharedOptions';

class SomeComponent extends React.Component {
  render() {
    return <div>{sharedOptions.get().whatever}</div>
  }
}
```

**Comment by christianalfoni** [comment]
### A: How should you confiugre a module to interact with the state tree?

I suppose this depends on the module and I think you are doing the right thing in this scenario. If there are any related components you could pass the path on the components themselves also. But as a Login thingy I think it should be an option of the module yes :-)

**Comment by christianalfoni** [comment]
### A: How should modules trigger events?
In your scenario I would make the module trigger a signal when it detects that the user is logged out. Maybe as a callback:

```js
controller.register({
  login: Login({
    onLogout() { controller.signals.myCustomGlobalLogoutSignal() }
  })
})
```

**Comment by christianalfoni** [comment]
### A: Should/can modules have "private" state that is stored in the state tree?
Currently no best practice, though I would suggest using the namespace passed to the module to store state. Maybe we will lock down the "modules" namespace in the state store to emphasise that modules to have their own storage area. But this is not decided upon yet :-)

**Comment by coryvirok** [comment]
Thanks for these answers! I'll continue the convo in Discord.

**Comment by christianalfoni** [comment]
Awesome, will close this then :)
