### ISSUE TITLE
Revised module docs make no means of controller being accessible in module creation.

### ISSUE THREAD

**Issue by delaneyj** [cerebral/cerebral#163]
While working on [the falcor module](https://github.com/bfitch/cerebral-falcor-module) noticed there was no way to get to signals to fire them.  After talking to @Guria the actual signature for module creation is ` return (module,controller) => {` but is not state anywhere in the documentation.

**Comment by christianalfoni** [comment]
It is there now :-) under "sharing a module on NPM"
