### ISSUE TITLE
module.state.import/export not scoped

### ISSUE THREAD

**Issue by delaneyj** [cerebral/cerebral#164]
```jsx
module.state({user:false});

...later in an action
({module})=>{
  module.state.export() === 'THE ENTIRE TREE'
}
```

Also it be nice to have more details on the specifics of import/export, such as.

1. What happens if you merge and want to remove certain values?  
1. It is always upserts?  
1. What's the difference between `module.state.get()` and `module.state.export()` suppose to be?

**Comment by Guria** [comment]
cc @christianalfoni

**Comment by christianalfoni** [comment]
Yeah, good point. Need to review it a bit. Just going through my emails now, will keep this on my list for review. Will make a suggestion on how these should work :)

**Comment by christianalfoni** [comment]
Closing as module is removed. I would suggest using `state.select().export()`.
