### ISSUE TITLE
Asynchronous actions that fail should timeout and display a warning

### ISSUE THREAD

**Issue by NervosaX** [cerebral/cerebral#169]
Currently if your asyncronous actions fail it will hang indefinitely - and is not always obvious why. It's also possible to use it incorrectly, where it can break the debugger:  https://github.com/cerebral/cerebral-chrome-extension/issues/17

If the action times out after something reasonable... 20 seconds? It could throw a warning saying which signal/action failed.

**Comment by saulshanabrook** [comment]
Closed in favor of https://github.com/cerebral/action-tree/issues/3 since we are extracting this functionality from cerebral core
