### ISSUE TITLE
Baobab Monkey not at top level of state results in an error

### ISSUE THREAD

**Issue by abalmos** [cerebral/cerebral#172]
A Baobab monkey anywhere other then the top level of the state causes the below error and Cerebral breaks.

`update.js?0341:182 Uncaught TypeError: Cannot delete property 'totalCostBroken' of #<Object>`

Demo code of the bug can be found here: https://github.com/abalmos/cerebral-boilerplate/tree/monkey-bug

This works fine:
```js
var model = {
  items: [{cost: 1}, {cost: 2}, {cost: 3}],
  totalCost: Model.monkey({
    cursors: {
      items: [ 'cart', 'items'],
    },
    get: function (state) {
      return state.items.reduce(function(total, i) {
        return total + i.cost;
      }, 0);
    },
  })
}

const controller = Controller(Model(model));
```

But this does not (note the monkey is under the cart key now):
```js
var model = {
  cart: {
    items: [{cost: 1}, {cost: 2}, {cost: 3}],
    totalCostBroken: Model.monkey({
      cursors: {
        items: [ 'cart', 'items'],
      },
      get: function (state) {
        return state.items.reduce(function(total, i) {
          return total + i.cost;
        }, 0);
      },
    })
  }

const controller = Controller(Model(model));
```

Unfortunately this is prohibiting me from moving my application to modules. I didn't get too far debugging tonight but it seems [this line](https://github.com/cerebral/cerebral/blob/master/src/CreateRegisterModules.js#L41) is the origin of the error. I can dive into it again tomorrow if no one has any ideas. The issue seems to be related to changes made for modules because both examoles functions on pre module versions of Cerebral.

**Comment by tnrich** [comment]
This error seems related to two issues I've lodged: https://github.com/Yomguithereal/baobab/issues/417 and https://github.com/Yomguithereal/baobab/issues/422

I would ask @yomguithereal for help.

**Comment by abalmos** [comment]
@tnrich thanks for info. I will check out those issues in the morning. 

Just want to add that both the above Monkeys work fine in pre module versions of Cerebral.

**Comment by Guria** [comment]
@abalmos have you tried cerebral's `computed` feature instead of monkeys?

**Comment by Guria** [comment]
fixed in baobab

**Comment by abalmos** [comment]
For future reference, it was https://github.com/Yomguithereal/baobab/issues/430 that resolved the error.
