### ISSUE TITLE
package to test model packages

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#189]
## `cerebral-test-model`

model package should have it as devDep to check whether it conforms to current model package api: accessors, mutators, toJson, etc.
## `cerebral-model-mock`

plain js model package suggested to use within tests across `cerebral-*` packages

**Comment by Guria** [comment]
cc @christianalfoni

**Comment by christianalfoni** [comment]
That is a really good idea! Currently we are a bit in "modules heaven", when things settle down there I think the next iteration on Cerebral should be testability, error warnings and production optimizations.

**Comment by bfitch** [comment]
And documentation, which I'd like to help with.

**Comment by Guria** [comment]
I thought about implementing abstract class (after transition to ts) in `cerebral` core package which can be used as base class by all model packages. So there wouldn't be a need in `cerebral-test-model` and we will have an easy compile time check of model package API conformance.

**Comment by christianalfoni** [comment]
Closing this as @garth has done an amazing job introducing `cerebral-testable` and we have added testing to the view packages asw ell

**Comment by christianalfoni** [comment]
oh, sorry, this was model packages.

**Comment by christianalfoni** [comment]
What is there to test inside model?
