### ISSUE TITLE
cerebral-module-testtools

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#194]
```
controller.addModules({
  testtools: TestTools()
})
```
Could include signal store module. Would provide usefull methods for assertions.

**Comment by christianalfoni** [comment]
This sounds very interesting! I do not have a clear image in my head how you could use it. But as you say, you could expose actions for testing etc. A lot of cool stuff I would imagine :)

**Comment by Guria** [comment]
We just need to collect api ideas while covering existing and new modules.

**Comment by christianalfoni** [comment]
I suggest this is handled by `cerebral-testable`?
