### ISSUE TITLE
Service properties are lost

### ISSUE THREAD

**Issue by abalmos** [cerebral/cerebral#199]
It looks like service wrapping in 0.33.13 is causing service properties to be lost. I don't have the time to look at it right now but I pushed up a quick demo:

https://github.com/abalmos/cerebral-boilerplate/tree/service-props-lost

**Comment by christianalfoni** [comment]
Ah, yeah, if your service is a function with props on they are lost. As the function is wrapped in a new function. You have an example of a service where you point to properties of a function?

**Comment by christianalfoni** [comment]
I can fix it, though not quite sure what you point to props on a function as they are normally for "internal use"

**Comment by abalmos** [comment]
The example that bit me is superagent-promise. It exposes a normal work
method as well as a set of "helper" functions like:
`services.superagent.get()` and `services.superagent.post()`.

**Comment by christianalfoni** [comment]
This is fixed now :-)
