### ISSUE TITLE
Modules as ES2015 classes

### ISSUE THREAD

**Issue by paulopes** [cerebral/cerebral#201]
This is just an idea: Could cerebral implement Modules as ES6 classes, and instantiate them for registration purposes using the "new" keyword instead of using a factory?

Even though using classes instead of factories would make the code for registering a module a little bit more verbose, I suggest that we would have the following advantages:

- the learning curve for newcomers to learn cerebral modules might be less steep.

- the code for a module might be easier to read because it would use the class-based paradigm.

- the use of "new" would make it explicit that a module registration is an instance of an object that is initialized.

- the meta information might naturally be referred to using the "this" variable.

I'm not sure if this would be possible to implement and still retain support for all the capabilities that cerebral modules currently have, but it is just an idea that I'd like you to consider.

**Comment by christianalfoni** [comment]
Hm, interesting idea @paulopes. I think it would be good to review how a module is defined. The API is a bit "in between worlds" now. Its not a normal factory returning an object and its not a class.

Let me think about it a bit and I can make a couple of suggestions.

**Comment by Guria** [comment]
Closing for now.
@paulopes feel free to continue discussion if you want
