### ISSUE TITLE
disallow signals ran before `modulesLoaded` event?

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#203]
see https://github.com/cerebral/cerebral-module-router/#application-startup
also devtools wouldn't be able to detect signals before `modulesLoaded`

**Comment by christianalfoni** [comment]
Just to be clear. You want to give an error if any signals run before `moduleLoaded` event? 

I think it makes sense to not let any signals run before modules are loaded. As modules do indeed create the signals.

I think I asked this before, but in what scenario do they run before `moduleLoaded` event?

**Comment by Guria** [comment]
Module could try to run signal in its init function. Another variant is automatically batch this signal calls to be ran in sync with `'modulesLoaded'` event

**Comment by christianalfoni** [comment]
Ah, I see... yeah, I vote for error :) If some scenario occurs where it actually makes sense to fire it off when instantiating the module we can discuss it. Though currently I do not believe it is a good approach to fire off a signal when instantiating the app.

**Comment by Guria** [comment]
do we really ready for this? what about no module app?

**Comment by christianalfoni** [comment]
We can add the check when `addModules` is called , if not called we do not wait for `modulesLoaded` event either

So I suggest:

1. No checks by default
2. `addModules` is called on controller. We add a flag to throw error if any signal is run
3. Right before we trigger `modulesLoaded` we turn off the flag

**Comment by Guria** [comment]
LGTM

**Comment by christianalfoni** [comment]
Done, https://github.com/cerebral/cerebral/commit/d8d78ae6458b96b9a67a0515a70b4967d8420872
