### ISSUE TITLE
Why has module context been removed?

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#205]
This is just a short summary of the decision on removing context of modules.

### What will be removed?
```js
function action({module, modules}) {
  module // Completely removed
  modules.someModule.state // Removed
  modules.someModule.services // Removed
}
```

### What will I do instead?
```js
function action({state, services}) {
  state.set('someModule.foo', 'bar');
  services.someModule.runService();
}
```

### Short history
The scope of a module is simply to namespace state, signals and services. This gives you structure to your app without manually creating namespace for everything. It also enforces a file structure. Modules also allows developers to create modules that can easily be attached to any application. That said, it is just namespacing.

As these changes were done we added the `module` arg to the action and also exposed `state` and `services` on the modules arg. This was not well thought out. We instantly got into a confusion on "what is exposed where", as the actions got a different kind of `modules` than components for example. We also did not see that exposing `module` arg was like exposing `this` to the action. The concept of `context` does not exist in the functional world. Functions do not have context, they never point to `this` and so should not actions.

### The future
We are not taking this step back to say: "We will never allow you to create an isolated module", we are just saying: "Lets get back to the open flexible Cerebral that was intended" and take a new look at the scenarios where context has been suggested to be used.

**Comment by christianalfoni** [comment]
# FAQ

### It was so nice to use the module arg
```js
// With context
function action ({module}) {
  module.state.set('foo', 'bar');
}

// Now
function action ({state}) {
  state.set('someModule.foo', 'bar');
}
```

1. Same number of chars (Though that is not a factor when considering simplicity)
2. It is explicit in the action which module you are changing the state of
3. Just the STATE arg, all over

### Now I have to hardcode which module I want to use

```js
// With context (moduleA.signals.signal)
[
  changeSomeSate // changes moduleA
]

// With context (moduleB.signals.signal)
[
  changeSomeState // change moduleB
]
````
Now the action can only operate on the module of the signal it is composed into.You can not decide what state it is going to change. It will always be the module it runs on.

```js
// Now (moduleA.signals.signal)
[
  changeModuleAState // change moduleA
]

// Now (moduleB.signals.signal)
[
  changeModuleAState // change moduleA
]

// Now (moduleA.signals.signal)
[
  changeSomeSate('moduleA') // changes moduleA
]

// Now (moduleB.signals.signal)
[
  changeSomeState('moduleB') // change moduleB
]

```
Now you decide yourself if you want to hardcode your action to always change the same state, or you create a factory to let the action change whatever module state you want.

1. You get more flexibility
2. It is always explicit what you are doing

**Comment by Guria** [comment]
I hope context butthurt is in past. Waiting for suggestions from #204 got implemented

**Comment by christianalfoni** [comment]
haha :p
