### ISSUE TITLE
Define action as async (experimental)

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#207]
@delaneyj and I had a talk on the Falcor module, but ended up talking about how new users of Cerebral understands signals. We have both done some support on Cerebral and one thing that can be difficult to wrap your head around is the "arrays inside arrays" thingy. It is defined as: "this is how actions are run async", but it really is not very intuitive. Its just one of those things you have to learn. That said, arrays for grouping async actions is intuitive though. 

So here is a typical signal:

```js
const uploadExemplarImagesSignal = [
  [
    retreiveFileAsync, {
      success:[
        transformImageDataSync,
        [
          sendToFirebaseAsync, {
            success:[updateStateAfterFirebaseUploadSync],
            error:[handleErrorsBetterThanThis]
          }
        ]
      ],
      error:[handleErrorsBetterThanThis]
    }
  ]
];
```

You do understand what is happening by looking at the chain, but it is a bit cluttered with arrays. More often you only have one async action, not a group. So the array can feel a bit "too much". It does more harm than good really.

So what if the chain looked like this:
```js
const uploadExemplarImagesSignal = [
  retreiveFile, {
    success:[
      transformImageData,
      sendToFirebase, {
        success:[updateStateAfterFirebaseUpload],
        error:[handleErrorsBetterThanThis]
      }
    ],
    error: [handleErrorsBetterThanThis]
  }) 
];
```

Does it really matter to you which one of them runs synchronously and asynchronously by looking at the signal? They will all run in order nevertheless.

So the way we can achieve this is by adding a property on actions:

```js
function myAsyncAction() {

}

myAsyncAction.outputAsync = true;

export default myAsyncAction;
```

By adding a property that the action is async Cerebral will handle it as such.

And when async functions becomes a thing of the browser, you can:

```js
async myAsyncAction() {

}

export default myAsyncAction;
```

I want to add this as an experimental feature. I think it will clean up a lot of signals and lower the threshold of understanding signals in Cerebral.

Let me know what you think and I will add it as experimental :-) 

**NOTE!** This change is not breaking. Its just an alternative to using an array. The async function will just be put into an array when the signal is analyzed.

**Comment by bfitch** [comment]
Yes! :+1: this. I think this has been one of the roughest parts of the signal API so far and most confusing new users too. Now arrays only mean one thing: grouping actions, either at outputs or top level. I like the property implementation too.

**Comment by delaneyj** [comment]
I concur, but that's probably obvious. :shipit: :thumbsup:

**Comment by Guria** [comment]
+1. Async action usually already supposed to be aaync when defined, but not used.

**Comment by maxfrigge** [comment]
Really like this move. It shouldn't really matter if an action is sync or async when defining signals. Marking the action with a property makes sense too. It could later maybe even be extended to check for a generator function :)

Just one thing I don't quite understand: why not just use `async` instead of `outputAsync`?

**Comment by christianalfoni** [comment]
@maxfrigge I have been looking into being able to check:

```js
async function getSomething() {

}

export getSomething;
```

But there is actually no safe way if verifying of a function is async or not. Well, there is a way, though it seems to be frowned upon. But again, Angular uses `toSTring()` for dependency injection, which is also quite bold. So maybe we can do it like that.

About the name of the function. Its just that `async` seems a bit too close to native. If functions for some reason got an `async` property we would be in trouble :) Also it is more explicit that you need to give the function an output for it work. I think it is a good reminder.

So yeah, that is the reasoning :)

**Comment by maxfrigge** [comment]
I liked it because it is so close to the native - and yeah `async function()` was my initial thought too :)

I think right now babel transforms async functions to generator functions (`fn.constructor.name === 'GeneratorFunction'`). Once async function support lands with proper detection you could deprecate the async property and use proper async functions instead.

To me output async just sounds a bit imperative ... as in make the output async. But that could as well just be me :)

**Comment by christianalfoni** [comment]
Hehe, you make a good point here :) This is the issue where I asked the question: https://github.com/tc39/ecmascript-asyncawait/issues/78

You know, I really do want to make this work as you say.

Okay, let me change the proposal. I will have to verify identifying the generator/async stuff

**Comment by maxfrigge** [comment]
Maybe just leave it with a property for now and then add async .. step by step. This could help to avoid pulling another "module scope fiasco" ;)

**Comment by christianalfoni** [comment]
Hehe, yeah, though I do not think domenic quite understood my scenario. He is stating "any function that returns a promise", but that is my point, I can not call the function to check its return value. I need to know it before hand. 

And as the first guy said, the spec will name the constructor. And as you say, Babel already does it. So this is safe in my opinion.

Anyways, we should try it. Is experimental and then decide :)

Let you know when I have tested

**Comment by delaneyj** [comment]
Maybe you should rephrase to **can you tell if a function returns a promise without executing it** but like the rest of javascript I don't think you can tell what something returns without types.

**Comment by christianalfoni** [comment]
Except `async function` which always returns a promise :-) Even if you return nothing, "Furthermore, an Async Function always returns a Promise" from https://ponyfoo.com/articles/understanding-javascript-async-await?utm_source=javascriptweekly&utm_medium=email

**Comment by maxfrigge** [comment]
What would happen if you do `await syncFunction()` ?

**Comment by maxfrigge** [comment]
Or will libs that process a list of functions always have to deal with promises?

**Comment by christianalfoni** [comment]
Yeah, that was kinda what I was getting at with my question there, though I think I was not understood. It should be possible to check for a function being of type `async` or not. Because of libraries that executes arbitrary functions. But yeah, I think the constructor name is the identifier that should be used.

**Comment by maxfrigge** [comment]
Just wanted to pop in some links that might be of interest:

http://kangax.github.io/compat-table/esnext/
https://tc39.github.io/ecmascript-asyncawait/
https://github.com/facebook/regenerator/blob/master/runtime.js

**Comment by christianalfoni** [comment]
Okay, did some research:

The `async function () {}` is just a function, no special constructor name. So not able to identify it as async yet.

But you can still: 

```js
async function test() {

}

test.outputAsync = true;
```

And that works.

So what I suggest is:

Lets use the propname `myAction.async = true` instead, and I will make a check on constructor name `fn.constructor.name === 'AsyncFunction';` too, so when this thing hits the browser you just do not need the async prop anymore, but it will not break anything.

**Comment by Guria** [comment]
I had an suggestion to allow define actions as objects< like we did with signals already:
```js
{
  action: function ({input, output, state}) {
  },
  defaultInput: {},
  async: true
}
```

**Comment by christianalfoni** [comment]
I think this is great, it conforms with the signal options object: 

```js
{
  chain,
  sync: true
}
```

I will create a pull on this with support the object format and change to `async`. We are going to refactor our project this week and will use all this new syntax before sharing the project.

**Comment by Guria** [comment]
done in https://github.com/cerebral/cerebral/releases/tag/v0.33.28
object format suggestion moved to #216
