### ISSUE TITLE
Objects passed to controller.addServices are missing keys

### ISSUE THREAD

**Issue by NervosaX** [cerebral/cerebral#208]
I've recently upgraded cerebral to latest, and immediately found that a lot of signals that I've been passing to `controller.addServices` are being altered. This is probably because Object.keys() is not returning all necessary keys. Sometimes they are not enumerable. At least this has been the case for:

A class from one of my modules and an ampersand module (which is object based). Generally I expect the object I pass in to be the object I can access from services in my actions - but I can confirm that cerebral works at version 0.33.10 and fails on 0.33.11 and onwards.

Interestingly, if I add my services as part of a module: `modules.addServices(...)`, there is no issues at all.

**Comment by Guria** [comment]
Did you meant addServices everywhere?

**Comment by Guria** [comment]
@christianalfoni we should revert services wrapping. It is compleately breaking change. If you still want it, make it opt in.

**Comment by NervosaX** [comment]
Apologies yes, addServices. I will edit.

**Comment by NervosaX** [comment]
Example for replicating:
If you go to https://babeljs.io/repl/ and add the following code:

```javascript
class Foo {
  test = "hello";
  foo() {
  
  }
}

console.log(Object.keys(new Foo));
```

You will note the output only includes ["test"]; I'm sure there are other test cases too.

**Comment by Guria** [comment]
Does it fixed?

**Comment by christianalfoni** [comment]
Everything is okay here now right?

**Comment by NervosaX** [comment]
Fixed with commit https://github.com/cerebral/cerebral/commit/a678de5a1be20595277d4aefe33db9aef2246b4c

It is a good idea to specify the ticket with the commit if possible. :)

**Comment by Guria** [comment]
Or at least in pr with that commit
