### ISSUE TITLE
state.push is broken

### ISSUE THREAD

**Issue by pltnkv** [cerebral/cerebral#212]
If you use push (e.g. state.push(['list'], value)) in action, 
field 'list' in model is changing after any signal.

Working example here:
https://github.com/pltnkv/cerebral-umd/blob/master/index.html

**Comment by Guria** [comment]
cc @christianalfoni

**Comment by christianalfoni** [comment]
@pltnkv Is this related to debugger? Or is it actually changing in the state store?

**Comment by pltnkv** [comment]
@christianalfoni Yes, bug is somewhere in the debugger.
State received from _controller.get()_ looks normal.

**Comment by christianalfoni** [comment]
Okay, great, I will check this example. The debugger rebuilds the state, so there is something wrong in rebuilding it there. We experienced the exact same thing, so fantastic with this simple example. Thanks a bunch, keep you posted :)

**Comment by christianalfoni** [comment]
This should be fixed now, thanks a bunch for the great example!
