### ISSUE TITLE
Remove special signal options hard codes

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#213]
Follow up from 114d66f

Originally I just want to suggest not to copy any props fom options to signal execution meta, since options already there. There is no need to some of them.

But seems @christianalfoni has some new ideas based on latest context providing suggestions.

**Comment by christianalfoni** [comment]
Ah, yes, let me explain :-)

The options object now attached to the `signal` is being extended with the `context` object/function shortly. And the options will get more and more options as we move along.

```js
      var signal = {
        name: signalName,
        start: null,
        isSync: defaultOptions.isSync || options.isSync,
        isRouted: options.isRouted || false, // will be removed
        isExecuting: false,
        isPrevented: false,
        isRecorded: options.isRecorded || false,
        branches: tree.branches,
        options: options,
        duration: 0,
        input: payload,
        preventSignalRun: function () {
          signal.isExecuting = false
          signal.isPrevented = true
        }
      }
```

Attaching it to the signal itself means that it will be serialized to JSON. That means when someone for example does this:

```js
{
  context: {
    window
  }
}
```

Suddenly the window is attached to every signal, being JSON serialized.

There is only certain information we want on the signal related to its execution. Like if `sync`, `isRouted`, `isRecorded` etc. I think we should manually attach that data to the signal to avoid bloating the signal object with stuff provided by the developer.

**Comment by Guria** [comment]
Got a point, but really don't like flag hardcodes coming from modules. But seems new context thingy would allow move setting this flags to module:
```js
function setRoutedFlag (context, execution) {
  execution.isRouted = true
}
```

**Comment by christianalfoni** [comment]
Ah, yeah, that is a good point! Though hm...

I actually think these are different things. Like:

```js
{
  sync: true,
  isRouted: true,
  isRecorded: true,
  context() {}
}
```

The context will run right before each action is run. The sync option is used before the signal runs. Also `isRecorded` is used before the context for actions is created.

But yeah, not saying the approach above can not be used, but I think we need to separate options and creating a context. So adding `isRouted` would probably be better to hook on using the `signalTrigger` event... but not `isRecorded`. hm...

Not quite sure about this. How these options are used are so different, so I can not see how we can make a generic way of adding them to the signal itself. Some of them affect how signals run, some of them is just info for the debugger etc.

**Comment by Guria** [comment]
```js
var {
  contextProviders, // extract context providers from all levels of options
  ...options  // JSON serializable properties
} = utils.mergeOptions({}, optionsPassedWithSignalRun, optionsPassedWithSignalDefine, globalDefaultOptions)

var signal = {
  name: signalName,
  input: payload,
  options: options,
  sync: false,
  branches: tree.branches,
  start: null,
  duration: 0,
  isExecuting: false,
  isPrevented: false
}

var isPredefinedExecution = false
if (options.sync) {
  signal.sync = true
}
if (options.branches) {
  signal.sync = true
  signal.branches = options.branches
  isPredefinedExecution = true
    controller.emit('predefinedSignal', { signal: signal })
  } else {
    controller.emit('signalTrigger', { 
      // protect original signal object from mutations
      signal: shallowCopy(signal),
      // still allow to redefine options
      setOptions: function (options) {
        signal.options = options
      },
      forceSyncRun: function () {
        signal.sync = true
      },
      preventSignalRun: function () {
        signal.isExecuting = false
        signal.isPrevented = true
      }
    })
  }
}
```

**Comment by christianalfoni** [comment]
```js
var {
  contextProviders,
  ...options
} = utils.mergeOptions({}, globalDefaultOptions, optionsPassedWithSignalDefine,, optionsPassedWithSignalRun) // Changed order...

var signal = {
  name: signalName,
  input: payload,
  // Remove options, avoids attaching unserializable and unnecessary data, we do not know what
  // we will attach to this in the future
  // options: options, 
  isSync: sync, // This is a core option of Cerebral
  branches: tree.branches,
  start: null,
  duration: 0,
  isExecuting: false,
  isPrevented: false
}

var isPredefinedExecution = false
if (options.branches) {
  signal.sync = true
  signal.branches = options.branches
  isPredefinedExecution = true
    controller.emit('predefinedSignal', { signal: signal })
  } else {

    // It is not common to mutate something passed on an event, but I think its okay that
    // we do it for internal use, like router, recorder etc. 
    controller.emit('signalTrigger', { 
      signal,
      preventSignalRun: function () {
        signal.isExecuting = false
        signal.isPrevented = true
      }
    })
  }
}
```

So recorder and router just does:

```js
controller.on('signalTrigger', ({signal}) => {
  signal.isRecorded = true
  signal.isRouted = true
}
```

I do not think we need to automate adding the options. The reason is that any options added will require a change in Cerebral itself or the Debugger. Like `isRecorded`is related to the debugger, also `isRouted`. So attaching the options to the signal itself does not give us any extra features. It is just unnecessary serializing... I believe :)

**Comment by christianalfoni** [comment]
Though... hm... like the recorder. good example:

```js
      signalMethodPath(signal.input, {
        isSync: true,
        branches: isCatchingUp && signal.branches
      })
```

It feels weird using options passed for signal here and then do:

```js
controller.on('signalTrigger', ({signal}) => {
  signal.isRecorded = !isCatchingUp
}
```

Like... these options are not arbitrary stuff developers add. These are core functionality of Cerebral. We know exactly what options that should be handled and I think we should handle them individually.

So:

```js
var signal = {
  name: signalName,
  input: payload,
  isSync: options.isSync,
  isRouted: options.isRouted,
  isRecorded: options.isRecorded,
  branches: tree.branches,
  start: null,
  duration: 0,
  isExecuting: false,
  isPrevented: false
}
```

Now we have full control of how a signal will look and we can use these options to other things than attaching them to the signal as well. Where for example `context` fits in.

There will never be an arbitrary option, we have full control and should handle them individually I think.

**Comment by Guria** [comment]
from https://github.com/cerebral/cerebral-module-router/issues/56#issuecomment-189668743
> Eyh... maybe we should just:
```js
controller.on('anyEvent', ({signal, options, [action]) {
});
```
So we pass the options as its own argument. That way also the debugger can just pick out any options it wants to pass it to the debugger.

**Comment by Guria** [comment]
Looks fine for me

**Comment by christianalfoni** [comment]
Yeah, really happy about this one :-)

I feel there are issues all over the place right now. I think we have to prioritize a bit. Do you have time for a little talk on discourse? Just look at the list of issues and then we can prioritize it? :)

**Comment by Guria** [comment]
Let summarize:
```js
var signal = {
  name: signalName,
  start: null,
  isSync: defaultOptions.immediate || options.immediate,
  // isRoute, // will be removed
  isExecuting: false,
  isPrevented: false,
  // isRecorded, // will be removed
  branches: tree.branches,
  // options: // will be removed
  duration: 0,
  input: payload,
  preventSignalRun: function () {
    if (signal.isExecuting === false) signal.isPrevented = true
  }
}

controller.on('anyEvent', ({signal, options, [action]) {
});
```

**Comment by christianalfoni** [comment]
Okay, this is now implemented.

We have to identify the modules being affected by this:

- Recorder
- Devtools
