### ISSUE TITLE
Add helpful error message when paths missing from action

### ISSUE THREAD

**Issue by NervosaX** [cerebral/cerebral#214]
When upgrading through the breaking change for the 'when' factory in cerebral-addons using "true" and "false" instead of "isTrue" and "isFalse", I received the following error:

```
Unhandled rejection TypeError: Cannot read property '0' of undefined
```

The stack was extremely unhelpful in finding where the issue was.

The code was:

```
when("state:/app"), {
	isTrue: [],
	isFalse: [setApp("appointments", "list")]
}
```

Therefore there were no workable paths, and the error was thrown. A quick check shows that any action with any missing paths will throw this very confusing error.

When changed to true/false respectively the error was gone... but it was more of a guess than an obvious fix.

To replicate you would need something like:

```javascript
function action({ output }) {
  output.success();
}
```

```javascript
const signal = [
  action, {
    error: []
  }
];
```

**Comment by saulshanabrook** [comment]
This has been fixed in https://github.com/cerebral/action-tree which will be merged into cerebral core soon!

**Comment by NervosaX** [comment]
Nice job. :)
