### ISSUE TITLE
define actions as objects

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#216]
I had an suggestion to allow define actions as objects, like we did with signals already:
```js
{
  action: function ({input, output, state}) {
  },
  defaultInput: {},
  async: true
}
```

**Comment by christianalfoni** [comment]
Yes, this is good stuff :)

**Comment by christianalfoni** [comment]
Hm, I suppose we should also allow: 

```js
const signal = [];
signal.immediate = true;
export default signal;
```

Then...

Hm... this creates quite a bit of complexity in the checkers, and unbalances the API if we do not allow it on signals as well. Has anyone made concerns on this or is it "nice to have"? :-)

**Comment by Guria** [comment]
don't get the point here

**Comment by christianalfoni** [comment]
Its just that I always want less things to learn. After that I want consistency :)

So if it is not desperately needed to define actions a different way, it will just be one more thing to document and one more thing to learn.

If it really is necessary to implement I think it is important to keep consistency in the API. So if an action can be defined as:

```js
{
  action: [],
  async: true
}
```
We already have that signature on signals:

```js
{
  chain: [],
  immediate: true
}
```

For consistency you should also be allowed to build signals the same way you build actions today:

```js
// Normal action
function action() {}
action.async = true
// Object format
{
  action: function action() {},
  async: true
}

// Normal signal
const signal = []
signal.immediate = true
// Object format
{
  chain: [],
  immediate: true
}
```

**Comment by christianalfoni** [comment]
But I suggest we hold on here because it increases complexity in library and though I like how it looks, it just gives more options and more to learn for devs?

**Comment by Guria** [comment]
OK, agreed.

**Comment by saulshanabrook** [comment]
Closing this to settle down the API. We can revisit maybe for 2.0 or something
