### ISSUE TITLE
Documentation is terrible

### ISSUE THREAD

**Issue by letsgetrandy** [cerebral/cerebral#217]
It is impossible to get a project working with the current documentation.

Everything seems to change completely from version to version, and all the spaghetti of related projects seem to keep old docs or often are not even updated to match the requirements of the new version.

You guys need to get a little more diligent about making sure that a person can find _some_ documentation _somewhere_ that tells the truth about actually making the current version compile correctly.  I also feel strongly that that place should be the README file, because that file is updated along with any other files in the repo when you tag for a new version.... unlike the web site which _purports_ to be the current documentation (though it isn't always true) and which completely abandons any documentation of previous versions.

Cerebral is not only a fun project... it is actually in my opinion one of the better options available for flux architectures.  However with the terrible spaghetti of addons, broken features, libraries that deprecate code contained within them, and absolutely terrible documentation, you're going to have a hard time getting people to see the value in this.

**Comment by christianalfoni** [comment]
Hi @letsgetrandy and thanks so much for pointing this out!

Personally I have become completely blind. My head is way too deep into the Cerebral world. So this is really great.

It is not perfectly clear to me where we go wrong though, but I have one specific suggestion:

On the webpage I believe that all pages related to a specific repo. Like modules, views, models etc. gets quickly outdated when new versions arrive. We can fix this quickly by loading the README of the specific repo instead of doubling up documentation. I can make a first iteration on this quite quickly, though we should optimize it later with preloading etc.

Do you think that would solve a lot of the issues? Or do you see other parts of the docs that gives issues as well?

Again, thank you so much for pointing this out :)

**Comment by bfitch** [comment]
hi @letsgetrandy,

Sorry you've had such a rough go getting your project running. It's still early days for cerebral and with all the fast and furious development there are bugs, breaking changes, and outdated docs. It's frustrating, no argument there.

I will say, though, that having [cerebraljs.com](http://www.cerebraljs.com/) be the single source of truth for docs is a deliberate decision, precisely to help with the problems you pointed out above. Maintaining separate docs for each of the repos would make things less consistent and place more burden on maintainers.

If you see anything wrong or confusing in the docs, you can click a [link](https://github.com/cerebral/cerebral-website/tree/master/app/markdown) directly in the website to edit the corresponding markdown file and open a pull request immediately. Beyond that we have an active, helpful [discord chat](https://discord.gg/0kIweV4bd2bwwsvH) were you can definitely get help with specific issues in your project.

Great docs are a community effort and we definitely need your help! Some of us have been lurking around cerebral long enough that we have blinders on and forget what is confusing or broken. Please create issues for improvements and open pulls with edits (if you have the time).

Thanks and come hang on discord :smile:

**Comment by letsgetrandy** [comment]
@bfitch I don't disagree, nor have I ever been one to shy away from participating in helping an open source project -- and would especially love to help _this_ project because I do think it's better than most of the flux implementations out there.

The problem for me, however, is that I _am_ using this in a rather large project that goes live next week, but I'm stuck on 0.22 because any attempt to keep current costs me days of wasted time trying to figure out what you guys have changed... which leads me to the documentation issue.

If I had any idea what the heck has changed, I'd happily update the docs for you. But I don't.  All I see is everything breaking, and when I go try to follow the newest example or copy the implementation in the boilerplate, it fails to even compile.

**Comment by bfitch** [comment]
@letsgetrandy I definitely hear you. Breaking changes are a problem. There has been a ton of churn recently with the introduction of modules, but things will be better now, I believe. We're starting a push for version 1.0 and I'm hoping we can move releases off of the `master` branch and start batching features into regular more stable release cycles (every month, 3 months, etc). These releases will be more stable and will also have docs fleshed out by the time they hit.

I'm glad to hear you are liking cerebral and I definitely understand your frustration. Better days ahead.

**Comment by Guria** [comment]
@letsgetrandy since 0.32 we have a semantic release setup. All noteable changes goes to release notes automatically. Before that @christianalfoni also tried to add major changes there. Have you tried to follow it? https://github.com/cerebral/cerebral/releases?after=v0.25.0

**Comment by christianalfoni** [comment]
I have added a couple of todos on this. With 1.0 release we can add a migration guide on the major changes. Also grabbing README from repos will help. Will get to this as soon as I got some more time on my hands
