### ISSUE TITLE
A tiny bug in cerebral/src/createNext.js

### ISSUE THREAD

**Issue by Searle** [cerebral/cerebral#218]
Hi! I was just looking at your code and my eyes catched a potential problem in cerebral/src/createNext.js:

I believe
`if (checkers === undefined && arg === undefined) {`
should be
`if (checkers === undefined || arg === undefined) {`

Otherwise, if checkers xor args is undefined, the following code would blow up. Object.keys(undefined) is not allowed and arg[key] would be a problem to.

**Comment by Guria** [comment]
cc @christianalfoni

**Comment by christianalfoni** [comment]
Yes indeed, thanks for the heads up @Searle . Validation of inputs/outputs is not as broadly used so this has slipped by :-)

**Comment by Guria** [comment]
took it to pre-0.34

**Comment by Guria** [comment]
@christianalfoni this change breaks test: `should throw error when output is missing`

**Comment by christianalfoni** [comment]
Looking into it now :)

**Comment by christianalfoni** [comment]
Okay, this is now pushed as well
