### ISSUE TITLE
decide correct form of `sync` vs `isSync` signal flag

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#222]
https://github.com/cerebral/cerebral/commit/03afa0f179e66018ab25aadf0abe8d1705d15901#commitcomment-16534275

**Comment by Guria** [comment]
@christianalfoni will we support both or one of them should be deprecated?

**Comment by christianalfoni** [comment]
Lets move to `sync`, deprecate `isSync`. More consistent with `async` prop on actions and `routed` prop

**Comment by Guria** [comment]
ok. got it

**Comment by Guria** [comment]
btw, there is no `routed` prop.

**Comment by Guria** [comment]
https://github.com/cerebral/cerebral/blob/master/src/CreateSignalFactory.js#L39-L55

**Comment by christianalfoni** [comment]
Hm, I am confusing with debugger. Hmf, is a difference between user API and internal API in this matter. Like `sync` is exposed API, and `isRecorded` and `isRouted` is more internal...

hm hm...

Since `isSync` is in between maybe we should support both. `isSync` and `sync`.

**Comment by christianalfoni** [comment]
Either that or only support `isSync`.

**Comment by Guria** [comment]
wip in `pre-0.34`

**Comment by Guria** [comment]
decided to use `immediate` option
