### ISSUE TITLE
Test and refactor devtools and recorder to work with new options

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#234]
New options passed on events needs to be handled by devtools and recorder

**Comment by christianalfoni** [comment]
Okay, made a fix in signal store. It now makes a copy of the signal and adds `isRouted` and `isRecorded` as properties on it. This will allow debugger to give information about that.

We have to discuss how we should release this with the 0.34 release candidate though

**Comment by Guria** [comment]
can signal-store and recorder could be released to be compatible with both 0.33 and 0.34?

**Comment by christianalfoni** [comment]
Hm, yeah... I suppose it can. Need to change the code a bit. But can check for the keys already being on the signal. Good idea!

**Comment by christianalfoni** [comment]
Okay, pushed a branch on this now

**Comment by Guria** [comment]
Is it only signal-store affected? what about recorder?

**Comment by christianalfoni** [comment]
This should be working now?
