### ISSUE TITLE
Router retrigger

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#235]
@Guria , about the router extending the signal with `isRouted`.

I think the right way to do this is to prevent the signal from being triggered and then trigger it again with the option `isRouted: true`

So:

```js
    function onSignalTrigger (event) {
      var signal = signals[event.signal.name]
      if (signal && !event.options.isRouted) {
        event.signal.preventSignalRun();
        signal(event.payload, Object.assign({}, event.options, {isRouted: true}))
      }
    }
```

That means we also expose the payload passed to the signal on the event object. This way makes a lot more sense I think. We never mutate the signal or its options. We have to stop the signal and trigger it again using its payload and now extended options. This also allows us to extend the payload.

**Comment by Guria** [comment]
@christianalfoni router already doesn't extends signals options with isRouted :)

**Comment by Guria** [comment]
https://github.com/cerebral/cerebral-module-router/blob/master/index.js#L71-L73

**Comment by christianalfoni** [comment]
Ah, but original version of:

```js
function onSignalTrigger (event) {
      var signal = signals[event.signal.name]
      if (signal) {
        event.signal.isSync = true
      }
    }
```

Mutates the signal...

So:

```js
    function onSignalTrigger (event) {
      var signal = signals[event.signal.name]
      if (signal && !event.options.isRouted) {
        event.signal.preventSignalRun();
        signal(event.payload, Object.assign({}, event.options, {isRouted: true, immediate: true}))
      }
    }
```

I think the signal should be marked as "isRouted" even if it is a normal signal trigger, as it really does go through the router and the route is updated. Dont you think?

**Comment by christianalfoni** [comment]
But my goal here is really to avoid mutating the signal. So could even be:

```js
    function onSignalTrigger (event) {
      var signal = signals[event.signal.name]
      if (signal && !event.options.immediate) {
        event.signal.preventSignalRun();
        signal(event.payload, Object.assign({}, event.options, {immediate: true}))
      }
    }
```

Its just not good to do these mutations directly on the signal. And exposing payload gives new possibilities as well

**Comment by Guria** [comment]
> but original version of:
```js
function onSignalTrigger (event) {
      var signal = signals[event.signal.name]
      if (signal) {
        event.signal.isSync = true
      }
    }
```
Mutates the signal...

Which is also not necessary as we already discovered: cerebral/cerebral-module-router/pull/79

> I think the signal should be marked as "isRouted" even if it is a normal signal trigger, as it really does go through the router and the url is updated. Dont you think?

No, I don't think. Routed signal for me is that was triggered from url. But signal that updates url is just bound to route. Also you was agreed when I have introduced it and asked you. :)

> But my goal here is really to avoid mutating the signal.

Yeap. Avoid mutating at all and make it not possible at all. There is no known valid usecases anymore, since we resolved both mutations that router was dependent.

> Its just not good to do these mutations directly on the signal.

Just forbid it. :+1:

**Comment by christianalfoni** [comment]
Ah, okay, cool. I added the the exposing of `payload` to events. It will allow for module to do more. But yeah, then we have a strategy at least for changing the options of a signal with a module. Stop it and trigger again with new payload/options.
