### ISSUE TITLE
Remove metadata from modules

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral#241]
Since the upcoming concept of having a context provider, the return value that used to set meta information about the module seems to obsolete. 

Or is there still a use case for it?

``` javascript
export default (options = {}) => {
  return (module) => {

    // Return some META information about the module
    return {}
  }
}
```

**Comment by christianalfoni** [comment]
Ah, yeah, we still expose it to components through: `controller.getModules()` :-)

**Comment by maxfrigge** [comment]
What would be a use case to access the meta data? Wouldn't it be more consistent to store all module data in the state and have components/modules read it from there?

**Comment by christianalfoni** [comment]
Currently it is used to get the path of a specific module. For example you develop a UI module. You want to a dynamically access that module state based on the meta of `some-module-name`, which has the `path` to where it is actually located. But maybe we should think about this differently.

It would be possible for a module to add some "root level" state saying:

```js
{
  'my-awesome-module': {path: ['foo', 'bar'] }
}
```

Which components can safely access to figure out the actual path. You do some of this in useragent, right?

**Comment by maxfrigge** [comment]
Might miss something here but I think that it's obsolete to use meta data for this purpose.

The module should either use it's default alias or the one set by the developer. 
Either way you will be aware where to look for the modules state.

At least that's what I understood to be "the way to go" :)

**Comment by christianalfoni** [comment]
Want to bring @garth in here. Do you use module META in components on your UI lib?

**Comment by garth** [comment]
Most of my module stuff hasn't worked properly since 0.34. So what ever I do I have a lot of refactoring needed to move on. I would suggest that a lot can now be done with context that was previously done with meta, probably a better way to go in future.

**Comment by christianalfoni** [comment]
Okay, cool. The more we can clean up the better. I think you are right on this one :)

**Comment by saulshanabrook** [comment]
So the conclusion is we should remove metadata modules?

**Comment by saulshanabrook** [comment]
We have decided to remove metadata from modules, because we now have context.

**Comment by Guria** [comment]
* [ ] inspect existing modules on meta usage
* [ ] decide release to deprecate (optionally)
* [ ] decide release to remove

**Comment by Guria** [comment]
Seems we also need to deprecate exposing props.modules in view packages as well.

**Comment by Guria** [comment]
Ouch. we still need it:
https://github.com/cerebral/cerebral-view-react/blob/1c75fb14972f27d5181271c22378a05c5a83522d/src/link.js#L39-L42

Or at least find an alternative way to get path of shared (aka community) module in components.

**Comment by NervosaX** [comment]
I use this for my own form implementation. I create a form object, I pass it to a Form module, the meta is stored internally. I then have actions that act on the form object stored in meta.

The great thing about meta is that it's the one place I can store non serializable data.

**Comment by Guria** [comment]
@NervosaX thanks, for pointing this out. We already discussed it, and seems we are not ready to deprecate/remove meta for modules.

**Comment by garth** [comment]
I have been giving this issue some thought for a while and for my current project I didn't want to depend on `.meta`. Meta is not explicit, cannot be validated at the time it's created and may clash with other modules.

Instead I propose that we try something similar to context, but for modules... when a module is defined it is given `module` on which we can `add[stuff]()` I would like to be able to add my own methods to the `module` param in the same was as we do with signal context. This would allow us to do away with returning the ambiguous `meta` and enable more explicit features to be added to modules with better control.

**Comment by christianalfoni** [comment]
@garth Since the `context.module` is now added through a provider I think we should find a way to do this without extending the core. Because if you do not use the `cerebral-module-provider`, this new API has no meaning.

Is there any reason these things can not be services? Just so I understand the scenario :-)

**Comment by garth** [comment]
@christianalfoni I'm currently using the modules as a base for loading application plugins. But what I need to do is add some app specific methods to the `module` object passed to each plugin. (I'm not using the `cerebral-module-provider`)

Each plugins looks something like this, the plugin developer doesn't need to know, but actually it's simply a cerebral module with some additional methods injected.

```js
plugins.number = (plugin) => {
    plugin.functionX(...);
    plugin.functionY(...);
    plugin.addState({});
};
```

So what I'm looking for is simple way to add my custom methods to to the module argument.

At the moment I have something like this:

```js
        const initPlugin = ({ name, plugin }) => {
            module.addModules({
                [name]: (module) => plugin(Object.assign({
                    functionX() {},
                    functionY() {}
                }, module))
            });
        };
```

It occurred to me that if we supported adding these methods directly on the cerebral API then they could replace the returning of implied `meta` from the module init. And add more explicit meaning to the module.

**Comment by christianalfoni** [comment]
Hm, hm... just wondering what these added methods are used for outside of the module callback? Also exposing `addState`, `addSignals` etc. outside the callback could lead to some very weird stuff? :) Or am I misunderstanding maybe?

**Comment by garth** [comment]
in the same way as you want to addState, addModules, addSignals, you may also want to have app specific methods (or methods added via other modules) such as addForm. That is all.

**Comment by christianalfoni** [comment]
@garth Ah, you mean adding methods at instantiation time? No expose methods outside?

So you want: 

```js
module => {
  module.someNewMethod()
}
```

Not:

```js
controller.getModules().someModule.someNewMethod()
```
?

**Comment by christianalfoni** [comment]
I see now :)

So something like: 

```js
controller.extendModules({
  newMethod() {}
})
```

And all module instantiations now has access to a new method:

```js
module => {
  module.newMethod()
}
```

**Comment by christianalfoni** [comment]
Yeah, I think that adds good extensability but lets just hold on a little bit until we get 1.0 out the door. Maybe we could have a small hangout where you show us the plugin system? That way we get some more insight and maybe some ideas as well :)

But yes, I think it is a good idea @garth, sorry me failing so immensely to get what you ment ;-)
