### ISSUE TITLE
signal.chain deprecation

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#243]
Exposing `signal.chain` has negative impact on performance. Signal have to analyze chain each time it run. We are deprecating it in 0.34. Please describe your use case if you have used it some how.

**Comment by saulshanabrook** [comment]
Looks like this was fixed in 8ad3d47283b613da2ae9702ae5cff3e8802f5154

**Comment by Guria** [comment]
it's deprecated, but we are waiting responses here :)
but we can keep it closed :+1:
