### ISSUE TITLE
proto-cerebral - Minimal build of cerebral, store & view layers. No build step required.

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#244]
### Overview

To enable quick prototyping, demos and mini single page apps, `proto-cerebral` would be a single js file, possibly CDN hosted, that allows you to write an app in a single script tag with minimal lines of code and no pre-complication necessary.
### Sample

``` html
<html>
<head>
  <script src='https://some.cdn/proto-cerebral.min.js'/>
  <script>
    cerebral.addState({})
    cerebral.addSignals({})

    cerebral.render(cerebral.Component(function (state, signals) {
      return h('div', 'Welcome to Cerebral')
    }))
  </script>
</head>
<body></body>
</html>
```
### Notes

This would make it very easy for new developers to play with cerebral and to share working sample code. But I would suggest that not all cerebral features be included. For example if you need routing then you probably should be using build tools and structuring the app across multiple files.
### Discord Log:

garth - Today at 3:47 PM
I've been doing a lot of work with very small apps recently, eg an admin screen that just does one thing in < 50 LOC.  These "apps" have historically been written with jQuery since you just add a script tag to the jQuery CDN and then add a small amount of code inside a script tag and add some static html.(edited)
These pages are really too small to justify a build sysytem
But I was wondering about having a cerebral cdn hosted file that would allow you to do the same as the jQuery approach, but in the Cerebral way.(edited)
Single html file, script tag to pull in cerebral+ui+store, then scrhipt tag with model state + component
stick to hyperscript and es5 and no build step should be required.
Would this be useful to anyone, or just encourage laziness/bad practices?

Guria - Today at 3:57 PM
@garth I think it's great to have such thing and completely possible
at least we must have it with 1.0 😃

garth - Today at 3:58 PM
@Guria it's also useful for prototyping
We would just need to be more opinionated about which store and which UI layer to use and maybe not include the router so that larger apps are encouraged to do it the "proper" way.

Guria - Today at 4:01 PM
@garth can you put this notes into issue on github?

garth - Today at 4:01 PM
ok, proto-cerebral build issue coming....

**Comment by christianalfoni** [comment]
Eyh, I think this is really great :) I also like the fact that this is actually what I want to push for. Making signals and state first class citizens. So I think it is just a really great inspiration as well.

Linking this to JSFiddle etc. is also really nice!

Thumbs up for this! 👍

**Comment by bfitch** [comment]
:+1: this is great. Would be great for jsbin type stuff too. Are the hyper script helpers for React?

**Comment by garth** [comment]
So we would just need to decided on which model layer and which view layer.

With the view layer we would either need to include a client side JSX compiler or perhaps use hyperscript.

Though I would suggest that for code sharing it would be nice to support JSX since I think that's what most people are using.

**Comment by garth** [comment]
@bfitch yes there are hyperscript helpers for React, but I don't seem to find a JSX compiler any more.

**Comment by bfitch** [comment]
@garth JSXtransformer is deprecated. Looks like React recommends using babel-core from cdnjs: https://facebook.github.io/react/docs/language-tooling.html

**Comment by garth** [comment]
Would it be a major issue if JSX wasn't supported?

**Comment by bfitch** [comment]
I don't think so. But, like you said, it is probably more approachable to keep it if possible. I personally have no problems using hyperscript helpers. 

Should be as simple as:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/6.1.19/browser.js"></script>

<script type="text/babel">
  React.render(
    <h1 id="my-heading">
      <span><em>Hell</em>o</span> world!
    </h1>,
    document.getElementById('app')
  );
</script>
```

**Comment by garth** [comment]
ok, so perhaps support superscript of the the box (single min.js) and offer documentation on how to use text/babel to get jsx support.

**Comment by bfitch** [comment]
That sounds good to me. And if it turns out most people want JSX or it makes it less useful to not have it, we could switch the default and maybe include babel-core `browser.js` in the `min.js` file.

But, yeah, I say roll with hyperscript helpers and baobab as defaults.

**Comment by saulshanabrook** [comment]
We just talked about maybe using this https://github.com/Daniel15/babel-standalone#installation or webpack bin http://www.webpackbin.com/NyJX0jeUb

**Comment by Guria** [comment]
Umd build is planned for v2
