### ISSUE TITLE
ServerController for Universal apps is inconsistent

### ISSUE THREAD

**Issue by edgesoft** [cerebral/cerebral#245]
When trying to access state in server controller and just have one object you must access it this way.

```js
var controller = require("cerebral").ServerController({ foo: 'bar' })
console.log(controller.get()) // undefined
console.log(controller.get('foo')) // bar. You must use only string and can not be fetched as array
console.log(controller.get(['foo'])) // undefined. Possible bug?
```
However, if the object is nested the you can not access it thru dot notation. Then you must access it as an array

```js
var controller = require("cerebral").ServerController({ foo: {some: 'bar'} })
console.log(controller.get('foo.some')) // undefined
console.log(controller.get(['foo', 'some'])) // bar
```

**Comment by christianalfoni** [comment]
Ah, yes, this sounds like a bug. We will decide on forcing "dot notation" on next hangout. Lets await that :)

**Comment by saulshanabrook** [comment]
We have decided on forcing dot notation, I will investigate this error.
