### ISSUE TITLE
cursors: .select() should act like baobab's (subselection, plain args)

### ISSUE THREAD

**Issue by fvgoto** [cerebral/cerebral#247]
Bug:
given: `aCursor = state.select(path1)`
then, `bCursor = aCursor.select(path2)` is defined (aka. does not give an error).
But `path2` does not get scoped by / "hooked up to" `path1`.
In fact `path2` is re-interpreted starting from the store's root.

[Baobab](https://github.com/Yomguithereal/baobab/blame/master/README.md#L139) allows such "subselection".

TestCase (0.33.34 and 0.34.0):

```
state.get(['root','first','second'])
=> Object {third1: "aString", third22: Object, third333: Object}

state.select(['root','first','second']).get()
=> Object {third1: "aString", third22: Object, third333: Object}

state.select(['root','first']).get(['second'])
=> Object {third1: "aString", third22: Object, third333: Object}

state.select(['root','first']).select(['second']).get()
=> undefined

state.select(['root','first']).select('second').get()
=> undefined

state.select(['root','first']).select(['.','second']).get()
=> undefined

state.select(['root','first']).select(['root','first','second']).get()
=> Object {third1: "aString", third22: Object, third333: Object}

state.select(['root','first']).select('root','first','second').get()
=> Object {firstSibling: Object, first: Object}
```

-> So either correctly implement subselections or remove `cursor.select()` to avoid confusion (this is a general thought - not linked to Baobab, in fact)

As second feature/bug, this also shows, that `.select()` does not work as expected, if it is called with many arguments instead of an array (only the first arg is taken as the path).
Baobab permits also this.
(But Cerebral may go the way of "every path needs to be in the form of an array"... - that would be OK, I think)
-> Would be nice if either plain arguments are accepted the same way as Baobab does or yield a warning if more than one arg (in this case) is given.

**Comment by christianalfoni** [comment]
Hi there @fvgoto and thanks for the bugreport. That is a good point, I was not aware of the subselection feature :)

There is quite a bit of efforts going into the new state-tree, debugger and webpage these days. But yes, this should be fixed!

**Comment by Guria** [comment]
@christianalfoni milestone?
