### ISSUE TITLE
Is it possible to nest async actions?

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral#248]
Hi, I'm trying to do something like this for a signal:

```
mySignal = [
	doSyncAction,
	[ doAsyncFoo, {
		success: [doAsyncBarThatDependsOnFoo, {
			success: [fooAndBarBothWorked],
			error: [catchError],
		}],
		error: [catchError]
	}],
];

```

I'm getting a `Cerebral - Could not serialize output. ` error

**Comment by Guria** [comment]
Output from action must be json serializable.
Join us on discord and describe your case.

**Comment by Guria** [comment]
Also make sure your second async action is treated as async. Either with `async: true` property on action (preffered) or with nested array, because actions in conditional pathes arrays treated as sync by default.

**Comment by awei01** [comment]
If the above code looks okay in theory, then I think I know what's going on.

The `promise.then()` resolved with a non-serializable object as the payload.

Thanks for the fast response.

**Comment by Guria** [comment]
My second comment was about `doAsyncBarThatDependsOnFoo`. If doesn't have `async`  property defined it must appear in nested array.

**Comment by awei01** [comment]
ok thanks.
