### ISSUE TITLE
Throw exception when controller.addModules called more than once?

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral#250]
Hi, so, I stumbled upon this issue when I was trying out the `appStarted` event example in http://www.cerebraljs.com/modules/router. 

I got it working, then after playing around with the framework it stopped and emitted some `cannot trigger signal while modules loading` (or similar) exception.

After digging around, I found that I had done a `controller.addModules()` call from within some of my module definitions. 

If using `controller.addModules()` is an acceptable design pattern, then there should probably be an event signal notifying that the controller is completely loaded. Otherwise, there should probably be an exception thrown when the developer tries to do `controller.addModules()` from within his own module.

**Comment by Guria** [comment]
Yeah, you are completely right. This part wasn't explored yet well, so there can be some pitfalls.
Hope it will be fixed on 1.0 release.
Thanks for bringing it here. I was sure that I have already hvae noted it somewhere, but can't find it.

**Comment by christianalfoni** [comment]
Thanks for debugging that @awei01 , this should be fixed yes :)

**Comment by awei01** [comment]
Sure thing. Glad I could help.

**Comment by edgesoft** [comment]
@Guria @christianalfoni Maybe close this since this is not how 2.0 adds modules?
