### ISSUE TITLE
Throw error when you try to call a signal with a non-object parameter

### ISSUE THREAD

**Issue by TomKaltz** [cerebral/cerebral#252]
You can only send an object through a signal chain.  Cerebral should throw an error if you try to call a signal with a primitive.

**Comment by christianalfoni** [comment]
Completely agree :)

**Comment by saulshanabrook** [comment]
Since we have extracted this signal chain functionality into `action-tree`, I have moved this issue there: https://github.com/cerebral/action-tree/issues/4
