### ISSUE TITLE
Error: Invocation of form runtime.connect

### ISSUE THREAD

**Issue by weepy** [cerebral/cerebral#254]
If I run the demo site with the debugger - I get the following error in the console: 

```inserted-script.js:43 FAILED Error: Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)(…)```

**Comment by christianalfoni** [comment]
Is this the todomvc demo located on the www.cerebraljs.com/todomvc site?

**Comment by weepy** [comment]
seems to be fixed now!

**Comment by saulshanabrook** [comment]
@weepy Closing this then! Feel free to re-open if it comes up again
