### ISSUE TITLE
Allow only dot notation on state access, remove array

### ISSUE THREAD

**Issue by saulshanabrook** [cerebral/cerebral#258]
We have decided to remove the array notation for state tree path access. This is primary to decrease complexity. With [ES6 template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and [`join`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) it is relatively straightforward to turn any array into a string or combine strings directly.

If you have a good reason to keep it, please list it here. 

- [ ] Add deprecation for array access

So for example instead of `state.get(['app', 'users', userID])` you will now need to do ``state.get(`app.users.${userID}`)``

**Comment by saulshanabrook** [comment]
We are currently converting from strings or arrays to arrays in multiple different modules. Both in the Cerebral core as well as in `cerebral/state-tree`. We have decided to translate to arrays in Cerebral core in the `stateProvider` and only allow arrays in the `cerebral/state-tree`

**Comment by saulshanabrook** [comment]
We would also have to change [the `path` returned when we create a module](https://github.com/cerebral/cerebral/blob/be87cf7ede783b6f0b1cef5b238a603b6f200eb0/src/CreateRegisterModules.js#L13) to be a string, instead of an array, to be consistant.

This is problematic, because it is hard to deprecate the old behavior.

**Comment by TomKaltz** [comment]
Seems like both should be supported. Any reason other than slimming core to
remove?

On Sunday, July 3, 2016, Saul Shanabrook <notifications@github.com> wrote:

> We would also have to change the path returned when we create a module
> <https://github.com/cerebral/cerebral/blob/be87cf7ede783b6f0b1cef5b238a603b6f200eb0/src/CreateRegisterModules.js#L13>
> to be a string, instead of an array, to be consistant.
>
> This is problematic, because it is hard to deprecate the old behavior.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cerebral/cerebral/issues/258#issuecomment-230164815>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC0_IXDy4v8m5ZxEzGm6rB6TEWK9EZ4Hks5qR_E0gaJpZM4JDrMn>
> .
>


-- 
Thomas Kaltz III
586-214-7150
Sent from Gmail Mobile

**Comment by saulshanabrook** [comment]
From my perspective, its not the code that is particularly hard to keep working, just the added burden of documentation, testing, and the added lines when we refactor (like hen we bring in action-tree). Also since other tools handle this more comprehensively and with more thought (tcomb or typescript come to mind) it seems to make sense to let users who want these checks to reach for one of those.

**Comment by saulshanabrook** [comment]
@christianalfoni what was the impetus for this idea? I think slimming down/less choice/more consistency was the main driving factor.

**Comment by Guria** [comment]
@christianalfoni do you have ideas on how to deal with `modules.path`?

**Comment by Guria** [comment]
need a milestone as well

**Comment by edgesoft** [comment]
Think we should support both but have dot notation in all docs.

**Comment by maxfrigge** [comment]
👍  agree.. you never know what it's good for

**Comment by christianalfoni** [comment]
We are doing this now, closing it :)
