### ISSUE TITLE
Remove type checking

### ISSUE THREAD

**Issue by saulshanabrook** [cerebral/cerebral#260]
It would simplify that action implementation to remove [typechecking](http://www.cerebraljs.com/utilities/typechecking) from action input and outputs.

If we did this, you could still type check your actions by using an external library like tcomb. 

Does anyone have any use cases/reasons for keeping action type checking in cerebral? If not, we should work on removing it.

**Comment by saulshanabrook** [comment]
So we are going to remove these two syntaxes:

```javascript
var action = ...
action.outputs = {
  foo: {
    whatever: String
  },
  bar: {
     thing: Integer,
  }
}

action.output = {
  whatever: Integer
}
```

But we will keep:

```javascript
var action = ...
action.output = ["foo", "bar"]
```

**Comment by Guria** [comment]
@christianalfoni let decide a milestone for it (0.35 or pre-1.0). Also we should decide would we spent a time to deprecate it? So task would be splitted into two: deprecate in current release and cleanup in next.

**Comment by christianalfoni** [comment]
This stuff is gone now

**Comment by christianalfoni** [comment]
This was not gone, https://github.com/cerebral/cerebral/pull/264 .. we should just get rid of it for 1.0

**Comment by maxfrigge** [comment]
@christianalfoni What do you mean by gone and not gone? :)

Anything I can do here?
