### ISSUE TITLE
Auto generated API docs

### ISSUE THREAD

**Issue by saulshanabrook** [cerebral/cerebral#261]
It would be great to have auto generated API docs, as a reference for the cerebral core. `cerebral-module-router`  has [some nice ones](http://cerebral.github.io/cerebral-module-router/index.html#_index_d_) which we could get if we moved to typescript and added doc strings.

**Comment by edgesoft** [comment]
@saulshanabrook Maybe we could close this since we have docs that uses bem instead?

**Comment by Guria** [comment]
@edgesoft what do you mean?

**Comment by edgesoft** [comment]
@Guria Do we need auto generated api docs when moving to 2.x?

**Comment by Guria** [comment]
Why not? I thinks it's good to have docs built on actual code from sources.

**Comment by christianalfoni** [comment]
cleaning up this. The API surface of Cerebral is so small and not really any methods... just factories and options. Just a lot of effort with little value I think :)
