### ISSUE TITLE
Extra dependencies in 0.35

### ISSUE THREAD

**Issue by fmal** [cerebral/cerebral#275]
First of all, congrats on the release and thanks for bringing the best state-management solution out there :+1: 
In the latest release you're including both cerebral models and cerebral-operators as direct dependencies. If i decide to use `cerebral-model` my bundling solution still needs to bundle `cerebral-model-immutable` and it's dependencies like `baobab`. That means a lot of dead-code. I know that tree-shaking is a thing and it wil be supported in Webpack 2, but a lot of people are stuck with the older version. Same thing with `cerebral-operators` - I've been using Cerebral for a while now and created a bunch of action factories for common tasks and i'm not really interested in using these operators. Why not making them opt-in? Please, keep things pluggable. I don't see much benefit in including these things in the core package. Just wanted to share my two cents, keep up the great work :heart:

**Comment by christianalfoni** [comment]
Hi @fmal :)

Thanks for the feedback!

Actually, when you do:

```js
import Model from 'cerebral/modules/immutable'
```

you do not import any of the `mutable` code. They are separate files in the `cerebral` package. Please correct me if I am wrong, but that was the idea at least :)

**Comment by fmal** [comment]
@christianalfoni Sorry, I rushed a bit with creating the issue. Of course, you're right - it won't get bundled when you include it this way. I have been just skimming through the latest changes without actually updating and got concerned about seeing these extra packages. Thanks for the quick explanation, i will close now :+1:
