### ISSUE TITLE
make Link component in all view packages

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#278]
* [ ] Link for snabbdom
* [ ] Link for inferno
* [ ] advertise Link components well

**Comment by saulshanabrook** [comment]
What is a Link component?

**Comment by Guria** [comment]
https://github.com/cerebral/cerebral-view-react/blob/master/src/link.js

**Comment by christianalfoni** [comment]
I made a suggestion here not to have a Link component at all. Rather create a function which produces the URL for you:

```js
getSignalUrl('some.signal')
```

Less to learn, works in all view packages

**Comment by christianalfoni** [comment]
You had some input there @Guria ?

**Comment by garth** [comment]
I agree with @christianalfoni , link function should be enough.

**Comment by Guria** [comment]
moved to https://github.com/cerebral/cerebral-module-router/issues/107
