### ISSUE TITLE
Add props to signal paths making them more dynamic

### ISSUE THREAD

**Issue by hipertracker** [cerebral/cerebral#284]
Currently props can be passed only to dynamic paths of the model tree. Signal paths are static. They can't accept any parameters from the props. It would be useful to make them also dynamic. E.g. dynamic signal paths could take the current 'page' value from the props and the main Navbar component would need just that one dynamic signal to switch to the proper page. It's less verbose, clean and consistent with the way state paths work.

```javascript
// router:
import Router from 'cerebral-module-router'

export default Router({
  '/home': 'app.home.openPage',
  '/admin': 'app.admin.openPage',
  '/*': 'app.openNotFound'
}, {
  onlyHash: true,
  query: true
})

// Navbar subcomponent
export default connect({
    currentPage: 'app.currentPage'
  }, ({page}) => ({
    redirectTo: `app[${page}].pageOpened`, // it's not available at the moment
    //redirectTo: 'app.redirectTo' // old way, it needs one more signal
  }),
  function NavbarLink({page, current, label, redirectTo}) {
    const styles = classNames({
      'uk-active': page === current
    })

    // dynamic way, not available yet
    return (
      <li className={styles}>
        <Link signal={() => redirectTo}>
          {label}
        </Link>
      </li>

    // current way, require one more signal and the action
    //return (
    //  <li className={styles}>
    //    <Link signal={() => redirectTo({page})}>
    //      {label}
    //    </Link>
    //  </li>
    )
  }
)
```

The very good use case for having the dynamic signal paths would be the building of generic widgets (by widget I mean the component + it's internal state managment, aka it's module) With dynamic signal paths we could completely *isolate signals* of the widget from the external signals by simple passing the path prefix as the prop. Something like that

```javascript
<Foo signalPath='app.home.foo1' data={data1} headers={headers1}/>

// different place

<Foo signalPath='app.about.foo2' data={data2} headers={() => {myHeaders()}}/>

// component:

connect({}, ({signalPath}) => {
  clicked=`${signalPath}.app.home.updateSomething`
}, function Foo({data, headers}) {...})
```

So with dynamic signals we could be able to create fully  reusable components. For now they are not reusable too much because they contain a lot of injected signals which always map to the same *absolute* signal path.

**Comment by christianalfoni** [comment]
Yeah, let me look into this tomorrow :)

**Comment by garth** [comment]
I have been thinking about something that is similar to this recently: where a component can be a module.

Use case would be that I want to make a component (maybe react) and share it with others who may or may not be using cerebral for their app.

**Comment by christianalfoni** [comment]
This is released :)
