### ISSUE TITLE
Different computed behavior in actions

### ISSUE THREAD

**Issue by fmal** [cerebral/cerebral#285]
Here's the scenario: you have two actions which are part of the same signal. One of them uses `state.set()`  to mutate some path in the state and the other one uses this path as dependency for `state.computed()`. You would expect that `state.computed()` will produce new value, but it's not the case, because controller's `change` event  runs after all actions inside the signal are executed (https://github.com/cerebral/cerebral/blob/22bb152c9d7af01371ef7fac6e4f4bfba77c3db6/src/CreateSignalFactory.js#L90) and computed's cache gets updated after that (https://github.com/cerebral/cerebral/blob/ee82114a0ee4e3082d47d9ff28a24228f87fc2df/src/index.js#L103).
Cerebral versions prior to 0.35 updated the computed in such case and in my application i heavily relied on that. I think that the current behaviour is less intuitive and would force me to stop using Computeds inside actions (which would be pretty dissapointing).
@christianalfoni is there any way to workaround this? I'm using `cerebral-model-immutable`. Is it somehow possible to get the same behavior as previous `function (get) {}` syntax for computeds? 
Thank you for any help or insight.

**Comment by christianalfoni** [comment]
@fmal Great catch, we have already talked about this and I will make a fix where use of `state.computed` will force a new value. Computed values during the "signal lifecycle" is not the bottleneck, it is when rendering the components. So it caches on components, but forces new values in actions :)

**Comment by fmal** [comment]
@christianalfoni that sounds reasonable, looking forward for the fix :+1: Would it make sense to use Baobab monkeys in actions instead? I have a few computeds that i share across actions but i don't actually use them in the views. Thanks!

**Comment by christianalfoni** [comment]
@fmal Good question! You can use Monkeys as well yes, maybe in this situation that will work perfectly fine. The issue with Monkeys is that they are not serializable, but as long as you do not hydrate/dehydrate state from the model etc. it should work just fine :)

**Comment by christianalfoni** [comment]
This is being deployed and published now :)
