### ISSUE TITLE
handling context in Computed

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral#287]
Hi,

I'm wondering if whether or not it's possible (or if it should be considered) to handle the React `context` in the Computed callback. 

Looking at https://github.com/cerebral/cerebral/blob/ccad32149f5c1987f99f82ff1b73d1a53cf43daf/src/Computed.js#L36

```
    var deps = typeof paths === 'function' ? paths(props, context) : paths
```

Obviously, there would be more work to handle the caching of `context` along with the `props`.

**Comment by awei01** [comment]
Actually, thinking about this more, it should probably be handled in the `cerebral-view-react@connect` method.

**Comment by edgesoft** [comment]
@awei01 Can you open a new issue there and close this one?

**Comment by awei01** [comment]
Done: https://github.com/cerebral/cerebral-view-react/issues/72
