### ISSUE TITLE
State props should override original props

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#290]
### Problem:

Given a component that accepts a prop x that then extracts state x, the explic state x is overridden by the original input prop.

``` js
// given the following component where state value = 2:
const ComponentX = connect({ x: 'value' }, ({ x }) => <div>{x}</div>)

// rendered with 
<ComponentX x={1} />
```

I would expect the output to be `<div>2</div>`, but it's `<div>1</div>`.
### Reasoning:

The order is `props` => `state` => `render()` so I would expect state values to override props.
### Justification:

I have a case where I accept a prop then use a computed to verify and if necessary update the prop, but this is always overridden by the original prop value even though the computed function is executed.

**Comment by Guria** [comment]
cc @christianalfoni

**Comment by Guria** [comment]
@christianalfoni is it still actual or solved in v2?

**Comment by christianalfoni** [comment]
This I believe is fixed?
