### ISSUE TITLE
Cached computed values are not invalidated when state ancesters are removed

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#291]
Given a Computed:

```js
export default Computed({
  value: 'parent.value'
}, ({ value }) => value ? value * 2 : 'missing')
```

The computed response will not return `'missing'` when `parent` is deleted from the state tree, it will return an older cached response.

**Comment by christianalfoni** [comment]
Yeah, this is edge case, like: `state.merge('foo', {bar: 'what'})`. where a listener to: `foo.bar` would not update either.

We have to make decision. Like Computed is an extremely simple concept. It is not like Mobx with a bunch of overriding getters/setters on values creates a dependency graph and stuff :)

But we can make sure that a change to a path affects all the paths, also downwards, not just upwards. Which is the case above.

On merge we can make sure that keys added on merge is also added to the flushed changes map.

Small fixes and handles the issues we know of :)

**Comment by garth** [comment]
@christianalfoni did we have the same problem with view components not updating when dependent state was removed from the tree? If so wouldn't they both use the same solution?

**Comment by christianalfoni** [comment]
Yeah, there is actually no difference between a computed and a component now. So yeah, this fix will fix it both on computed and component :)

**Comment by garth** [comment]
The same problem also occurs on `state.merge` (it works if you use `state.set`)

```js
// in an action action
state.merge('root', { parent: { child: 1 } })

// view will not re-render when only child changes
connect({
  parent: 'root.parent'
}, ({ parent }) => <div>{parent.child}</div>)
```

**Comment by garth** [comment]
One more thing.... 

```js
connect({
  x: ComputedFunc()
}, (x) => ())
```

will pass undefined to the input params of the computed. The following fixes it, but according to the docs the above should work.

```js
connect({
  x: ComputedFunc({})
}, (x) => ())
```

**Comment by bfitch** [comment]
@christianalfoni doesn't the `.**` and `.*` syntax fix this?

- `root.parent.**` registers a change in `parent` if *any* child value changes
- `root.parent.*` registers a change one level deep
- `root.parent` only registers a change if that exact path changes

With those 3 cases, the developer has complete control over re-rendering and computed values.

**Comment by garth** [comment]
@bfitch the problem is when you bind to 'root.parent.child'. and the delete the parent. components and computed functions won't update. so it's kind of the opposite of .**

**Comment by bfitch** [comment]
Ah I see @garth. So, I would say this is definitely a bug. :) All child paths need to get marked as changed if their parent is deleted (or updated). I think that logic should always be the case.

**Comment by christianalfoni** [comment]
@garth This was all related to computed right? Also the `state.merge` issue?

I just remember discussing `state.merge` with @bfitch about the case where merging in new keys would not cause a change on those keys specifically... but that is not an issue as I see it.

Now all paths are checked with `path.indexOf(changedPath) === 0 || changedPath.indexOf(path) === 0` , which means that any component pointing to a "point in a path" will rerender if any part of the path is changed.

This logic is what was missing in computed, forgot that computed had this logic for updating cache as well.

**Comment by christianalfoni** [comment]
Anyways, computed is fixed with a pull request now.

**Comment by garth** [comment]
As far as I can tell this issue was apparent whenever a view or computed is bound to a child state node where the parent is set to undefined. When this happens then the view or computed is not updated.

**Comment by christianalfoni** [comment]
Hm, okay, cause I can not reproduce it directly on components, but the `updateCache` logic on computed was wrong so that is fixed now :)

**Comment by Guria** [comment]
@garth can you checkout if `next` branch fixes an issue?

**Comment by christianalfoni** [comment]
I am just closing this as it is getting old, please reopen if still an issue here :)
