### ISSUE TITLE
Add `log()` method to Operators

### ISSUE THREAD

**Issue by idream3** [cerebral/cerebral#297]
It would be nice to have this operator as part of the core for easy debug.

`log('state:path', optionalMessage)`

Eg.

`log('state:app', 'Entire app state')`

Outputs in console

```
Entire app state
Object > (console object)
```

If you want to proceed I will create PR.

**Comment by garth** [comment]
I had something like this in addons, but since the debugger has improved so much I didn't find the need for it any more.

Also, a custom inline action method is almost the same length.

```js
export default [
  ({state}) => console.log(state.get('path'))
]
```

**Comment by idream3** [comment]
True true!
