### ISSUE TITLE
Promise.all is not performing correctly under iOS

### ISSUE THREAD

**Issue by NervosaX** [cerebral/cerebral#307]
In my application I have two asynchronous actions I want to run side by side:

```
[async1, {
  success: [],
  error: []
}, 
async2, {
  success: [
    // Perform state change here, that affects computed values   
  ],
  error: []
}]
```

This is essentially run here: https://github.com/cerebral/cerebral/blob/master/src/CreateSignalFactory.js#L189 as far as I can tell.

Now for whatever reason, the flush event is not being triggered (which cache busts the computed functions) and effectively causing lack of re-renders in my iOS application. 

I replaced Promise.all with Bluebird.all (a 3rd party promise library), and the issue immediately fixed itself. I'm guessing some sort of timing issue is addressed inside bluebird that native promises don't deal with? It's really hard to say... this is as far as I've gotten with my testing.

**Comment by NervosaX** [comment]
Note this issue can be solved temporarily with:

```
window.Promise = Bluebird;
```

so that native promises are not used.

**Comment by edgesoft** [comment]
@Guria  Maybe we can close this then?

**Comment by Guria** [comment]
I think it must be documented

**Comment by christianalfoni** [comment]
This is most likely fixed with new sequence/parallel
