### ISSUE TITLE
Investigate possibility to provide codemods

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#318]
assigned to @jeroenverfallie

**Comment by NervosaX** [comment]
https://github.com/facebook/jscodeshift Perhaps this is useful?

**Comment by Guria** [comment]
Exactly this tool was meant by "codemods". :)
But haven't heared any news from @jeroenverfallie on this task yet :(

**Comment by NervosaX** [comment]
Played around for an hour trying to understand how jscodeshift works. 

Managed to create a codemod that converts the new controller code from here: http://cerebral.github.io/cerebral-website/migration/01_start_migration.html

https://github.com/NervosaX/cerebral-codemods

Might try and find the time to continue with the rest. Very interesting tool. :) 

Some useful documentation:
https://www.toptal.com/javascript/write-code-to-rewrite-your-code

Absolutely required tooling:
https://astexplorer.net/

**Comment by Guria** [comment]
@NervosaX would you like to continue explore on this task? We haven't heard anything from @jeroenferfallie

**Comment by NervosaX** [comment]
@Guria Sure thing. Based on the migration guide, the hardest (or possibly impossible part) to code mod will be actions and providers.

Are we considering some sort of migration path between what we have and what we're moving to? Are promises expected, or does async = true still exist in cerebral 2.x? 

My only issue is I need some catchup on the full implications of the changes.

**Comment by NervosaX** [comment]
This AST Type definition files are also required when writing these (just noting this for others that may come across this).

https://github.com/benjamn/ast-types/tree/master/def

**Comment by christianalfoni** [comment]
Just closing this as codemods has been created?

**Comment by Guria** [comment]
It is still need to be merged

**Comment by NervosaX** [comment]
Work could continue in the repo, if we're happy with its direction. Probably best I finish off the latest changes and docs however.

**Comment by Guria** [comment]
@NervosaX yeah, lets update and merge it. We can iterate on it later.

**Comment by edgesoft** [comment]
@Guria Can this be closed?

**Comment by Guria** [comment]
Yes
