### ISSUE TITLE
scheme parser fails on specific expression

### ISSUE THREAD

**Issue by fopsdev** [cerebral/cerebral#332]
hi guys, i've found a bug in scheme parser using the set operator.
path and value to test with:

``` javascript
path = "state:app.modal.msg", value = "Hey dudes. Who enables nices action flows and keeps your state safe:"
```

in this case the target gets evaluated as "Hey dudes. Who enables nices action flows and keeps your state safe:" but should be "state"(bearbeitet)
(using cerebral 2 latest)

**Comment by edgesoft** [comment]
@fopsdev Maybe we can close this since we are now using Tagged template literals
