### ISSUE TITLE
collocate tests with source

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#338]
* [lerna docs](https://lernajs.io/)
* use *.test.js as tests extensions

**Comment by gaspard** [comment]
Should I split operators tests for each operator (debounce.test.js, set.test.js, etc). Feels natural but wanted to ask.

**Comment by gaspard** [comment]
Cerebral needs babel for tests... How can we avoid the files ending in the build ? Adding ignore in babelrc also changes test setup...

```js

  "ignore": [
    "**/*.test.js"
  ]
```

**Comment by gaspard** [comment]
Should I update cerebral tests to not require babel for testing ?

**Comment by Guria** [comment]
> Should I split operators tests for each operator (debounce.test.js, set.test.js, etc). Feels natural but wanted to ask.

Choose that feels better. I haven't explored it deep so don't have a strong opinion.
If splitting feels better, just do it.

> Cerebral needs babel for tests... How can we avoid the files ending in the build ? Adding ignore in babelrc also changes test setup...

`.babelrc` should support different configs for different ENVs as I remember.

> Should I update cerebral tests to not require babel for testing?

Do you mean write in es5 and import from `lib/` instead of `src/`?
I don't know which is best practice here. We can see how it solved somewhere else and examine pros and cons.
Does previos answer fixes a problem?

**Comment by gaspard** [comment]
Will try to use different ENV in babelrc. Thanks for the tip. Will leave all operator tests in a single file for now (don't want to make too many changes at once).
