### ISSUE TITLE
Update todomvc app

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#339]
* put to packages/cerebral-todomvc as private package
* use create-react-app
* write jest tests (see create-react-app) (optionally)

**Comment by henri-hulski** [comment]
@Guria Importing the existing repo would be fine for me.

**Comment by henri-hulski** [comment]
@Guria But if you think starting from scratch makes more sense that's also ok.
So create-react-app should be ejected?

**Comment by Guria** [comment]
nope, try to build not ejected app

**Comment by Guria** [comment]
see demos in #336 for refference

**Comment by henri-hulski** [comment]
Ok.

**Comment by henri-hulski** [comment]
@Guria Should I remove the Recorder?

**Comment by Guria** [comment]
@christianalfoni will start to work with recorder soon, but you can omit it right now

**Comment by henri-hulski** [comment]
@Guria I have imported the existing repo and created a PR.
The tests are still missing and there is a strange bug: 

When I have one Todo completed and I click Clear completed (1) the state and the view updates and the Todo disappears, as it should.
BUT when I have 2 or more completed Todos, only the state updates and the view stays untouched until it re-renders next time.
It seems that the component doesn't subscribe to state changes, when there is more then one completed Todo.

But I think you can already make a first review if it goes in the right direction.

**Comment by henri-hulski** [comment]
#343

**Comment by henri-hulski** [comment]
Just tried out the cerebral-todomvc repo and there everything works fine the the bug must be introduced here.

**Comment by edgesoft** [comment]
@Guria @christianalfoni @henri-hulski I can verify that having an array of two items will not update the UI with strict mode. using alpha-4.

**Comment by henri-hulski** [comment]
@edgesoft  Todomvc doesn't use strict mode (yet) but has the same problem, so seems to be unrelated to strict mode.

**Comment by edgesoft** [comment]
@henri-hulski Yes, have tested in both strict and not strict.

**Comment by henri-hulski** [comment]
After switching to strict mode the bug is fixed with current cerebral.

**Comment by henri-hulski** [comment]
@christianalfoni But the bug still exists in non strict mode and I think it shouldn't, right?

**Comment by henri-hulski** [comment]
Cc @Guria

**Comment by Guria** [comment]
@henri-hulski I haven't explored strict vs non-strict well yet. Could you make a test into cerebral that you think should work, but fails in non-strict?

**Comment by henri-hulski** [comment]
The bug was related to unset and is fixed in #382.

**Comment by Guria** [comment]
@henri-hulski do we need strictRender on todomvc then?

**Comment by henri-hulski** [comment]
@Guria Nope. But maybe it's good to have it as an example how it works.
