### ISSUE TITLE
Move outdated packages to cerebral-legacy org

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#368]
@henri-hulski would you like to take this task?

**Comment by henri-hulski** [comment]
@Guria Yeah I can look at that this weekend.

**Comment by Guria** [comment]
ping me it you will require extra permissons. 
It will also include some edits on readmes for moves packages as well

**Comment by henri-hulski** [comment]
@Guria So which packages should go here?

**Comment by Guria** [comment]
Almost all except urlon, url-mapper and addressbar. In other words all repos related to cerebral <=1.x

**Comment by henri-hulski** [comment]
@Guria Yeah, need admin permissions in both organizations.

[The user transferring a repository must have owner or admin permissions in both organizations to complete a repository transfer.](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/#transferring-to-another-organization)

**Comment by Guria** [comment]
@henri-hulski ok, added permisions.

**Comment by henri-hulski** [comment]
@Guria Thanks! :-)

**Comment by henri-hulski** [comment]
@Guria Just to be sure, the packages which were transferred to monorepo go also in legacy?
I mean the ones which have only the README left.

**Comment by Guria** [comment]
Yeah. No need to keep it main org. And good thing that github manages redirects for moved repos automatically.

**Comment by henri-hulski** [comment]
@Guria @christianalfoni I have transferred the packages now.
Please take a look if it's ok like this.
After I will update READMEs and URLs.

**Comment by henri-hulski** [comment]
@Guria Anything else to do with this?

**Comment by Guria** [comment]
provider-firebase

**Comment by henri-hulski** [comment]
provider-firebase was written for Cerebral 2.
What is the reason to move it to legacy? 
Should I add some information about this to the README?

**Comment by Guria** [comment]
Oh sorry, it was about importing to monorepo

**Comment by henri-hulski** [comment]
I will do.

**Comment by Guria** [comment]
Thanks for your great hiqh quality work.
