### ISSUE TITLE
powerful cerebral-demo

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#369]
demo that involves using cerebral and modules like provider-htttp, forms, useragent, etc

**Comment by edgesoft** [comment]
We should also involve firebase and other modules to show of

**Comment by gaspard** [comment]
Yes, I am first creating a working simple app without database, forms, useragent, etc (this is the part I can do OK). I propose that we then review this app for best practices and to avoid some silly things I might have done.

Then I'll ask for help integrating firebase, forms, etc. There are people in the community who know these libraries much better then I do.

Todo (as of end of October):

* Create new tasks (= time entry), clients, projects
* Tagging support (with #hashtag in task description)
* Reports

**Comment by Guria** [comment]
Thanks for great demo. I have merged it recently. Lets keep iterating on it.
