### ISSUE TITLE
use node compatible syntax in function-tree

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral#375]
How do you feel about using valid (node 6.9.1 lts) syntax for function tree (and other packages that could be used on the server).

When working with node 6.9.1 (current lts), you can easily drop babel and not just reduce your dependencies but also have codes that's easier to debug. The only major thing that's currently not supported by node is the new module syntax with `import` and `export`. So going back to `require` for a little longer brings quite a few upsides (imho). 

The however means that you cannot use `default`. So you either export a function directly OR export an object that can be used with destructuring .. but not both. I personally think that this is not a big deal and would improve the ease of use in node environments.

**Comment by Guria** [comment]
We can add a target with only [transform-es2015-modules-commonjs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) enabled. It means just use subpath when requiring from cosumer code.

**Comment by maxfrigge** [comment]
Okay.. so you would leave import/export statements as is in source code and then use `require('function-tree/es6')` in consumer code?

**Comment by Guria** [comment]
yes, is it ok for you?

**Comment by maxfrigge** [comment]
Let's push this one and close it for now.

My initial idea was to get rid of babel, which is not possible. And I guess it's not worth it "just" for peace of mind :)
