### ISSUE TITLE
import website

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#398]
* import cerebral-website v3 branch as 'packages/docs'
* create 'docs/README.md' with link to 'packages/docs/content'
* cleanup cerebral-website repo
* update cerebral-website readme with links to monorepo and cerebral-website v2 branch
* move cerebral-website to legacy org

I will do CI part myself

**Comment by henri-hulski** [comment]
@Guria 
> create 'docs/README.md' with link to 'packages/docs/content'

Do you mean in the root directory or change 'packages/docs/README.md'?

**Comment by Guria** [comment]
@henri-hulski it is smth like https://github.com/facebookincubator/create-react-app/tree/master/template

**Comment by Guria** [comment]
so: https://github.com/cerebral/cerebral/tree/master/docs/README.md should point to https://github.com/cerebral/cerebral/tree/master/packages/docs/content

**Comment by Guria** [comment]
Great work as always. Thanks
