### ISSUE TITLE
useragent: disable network offline detection

### ISSUE THREAD

**Issue by fopsdev** [cerebral/cerebral#409]
using the brilliant useragent-module but missing the possiblity to disable the offline detection feature
thats the config part for the network. btw i couldn't see in the code where this gets used?
```
 offline: {
    checkOnLoad: false,
    interceptRequests: true,
    reconnect: {
      initialDelay: 3,
      delay: 1.5
    },
    requests: false
  },
```

**Comment by edgesoft** [comment]
@fopsdev useragent uses offline-js under the hood and according to their docs "You can disable the reconnect module by setting the reconnect to false. Reconnect can be configured by setting options on the reconnect setting." So basically you could just update the state of useragent and you should be good to go.

**Comment by fopsdev** [comment]
ok that would be great :)
but i couldn't see where the options get handed over to the network library.
and the check here:https://github.com/cerebral/cerebral/blob/master/packages/cerebral-module-useragent/src/index.js#L44
is just checking the offline object which is somewhat always set

**Comment by edgesoft** [comment]
Think you could pass in the option here. 

```js
https://github.com/cerebral/cerebral/blob/master/packages/cerebral-module-useragent/src/index.js#L31
```

**Comment by edgesoft** [comment]
So basically pass ```offline: false```
