### ISSUE TITLE
review all packages readme, prepare a checklist

### ISSUE THREAD

**Issue by edgesoft** [cerebral/cerebral#420]
### Packages to review

- [x] function-tree
- [x] cerebral
- [ ] cerebral-router
- [x] cerebral-module-useragent
- [x] cerebral-provider-firebase
- [x] cerebral-forms
- [x] docs
- [x] debugger

**Comment by edgesoft** [comment]
forms is reviewed and is in sync with new code. We should add a sample with dependsOn as array as well because now it isn't clear that you can use both arrays and strings.

**Comment by edgesoft** [comment]
function-tree looks very good

**Comment by edgesoft** [comment]
useragent looks good

**Comment by edgesoft** [comment]
Firebase 👍

**Comment by edgesoft** [comment]
@Guria Looked through all readme:s and they look good. Maybe someother could also read them through to get a second opinion?

**Comment by edgesoft** [comment]
In a discussion at Discord the router readme is outdated.

**Comment by henri-hulski** [comment]
In https://github.com/cerebral/cerebral/blob/master/packages/cerebral-forms/README.md#api the last sentence seems not be finished.
> Cerebral forms is basically a function that creates state needed to handle validation and an action factory for validating fields. It is simple in nature, but handles

**Comment by edgesoft** [comment]
Thanks @henri-hulski Created a PR for this.

**Comment by henri-hulski** [comment]
https://github.com/cerebral/cerebral/blob/master/packages/docs/README.md is not yet updated to monorepo.

**Comment by henri-hulski** [comment]
Same in https://github.com/cerebral/cerebral/tree/master/packages/function-tree#demo.

**Comment by Guria** [comment]
add debugger to list

**Comment by edgesoft** [comment]
Done

**Comment by edgesoft** [comment]
Do we really need to have monorepo in all readmes? It's in the contribution of root readme.

**Comment by edgesoft** [comment]
@Guria router is missing readme. Is this intentional?

**Comment by edgesoft** [comment]
#476

**Comment by edgesoft** [comment]
@christianalfoni debugger is missing readme. Do we have to have readme for debugger?

**Comment by christianalfoni** [comment]
Good question @edgesoft . I think it is such an integrated part of Cerebral that it is enough with website documentation. You do no install the debugger from NPM either... so yeah, do not think it is necessary :)

**Comment by Guria** [comment]
@christianalfoni We still could have very simple one for those who just browsing repo

**Comment by christianalfoni** [comment]
Did I not write an answer here? Anyways, yeah, does not hurt :)

**Comment by christianalfoni** [comment]
This review is done, router will be new anyways so need separate review there.
