### ISSUE TITLE
react-native and debugger

### ISSUE THREAD

**Issue by ozanturksever** [cerebral/cerebral#456]
I am using cerebral for a react-native project, but debugger is not working. It is stuck at 'Please refresh your app to use the debugger...' screen. Any idea how to use debugger on react-native?

"react-native": "0.37.0"
"cerebral": "^1.1.0"
"cerebral-module-devtools": "^0.7.2"

thanks

**Comment by christianalfoni** [comment]
Hi there!

If you follow this guide: https://facebook.github.io/react-native/docs/debugging.html#chrome-developer-tools . It would be awesome if you go to: https://cerebral.github.io/getting-real/03_devtools.html and update our Cerebral 2 docs with a shortlist of what you did to make it work :)

**Comment by henri-hulski** [comment]
@christianalfoni @ozanturksever is using Cerebral 1.

**Comment by christianalfoni** [comment]
I know, but it is same setup :) @henri-hulski

**Comment by ozanturksever** [comment]
What you mean by "Chrome connection" ? i have dev tools open an i can see my console messages but extension is not working.

also i don't think i can move to cerebral2 now, it seems there is a lot of breaking changes.

**Comment by christianalfoni** [comment]
@ozanturksever You are doing this?

"To debug the JavaScript code in Chrome, select "Debug JS Remotely" from the Developer Menu. This will open a new tab at http://localhost:8081/debugger-ui."

**Comment by ozanturksever** [comment]
yes it automaticly opens that. I can also see my console.log messages there.

**Comment by christianalfoni** [comment]
It should just work, cause there is no difference running the code there, than in a normal application. And devtools is added to controller? Sorry, just have to make sure :)

You can also try to close and open Chrome devtools.

It seems weird, cause we have been testing this and it does work :)

**Comment by ozanturksever** [comment]
ok, i will create a vanilla project to test it then.

**Comment by ozanturksever** [comment]
`react-native init test1`
`npm install cerebral --save`
`npm install cerebral-module-devtools --save`

added this code to index.ios.js
`
import {Controller} from 'cerebral'
import Model from 'cerebral/models/immutable'
import Devtools from 'cerebral-module-devtools'

const model = Model({
  items: [],
  newItemTitle: ''
})

const controller = Controller(model)
controller.addModules({
  devtools: Devtools()
})
`

`react-native run-ios`

<img width="376" alt="screen shot 2016-11-18 at 00 53 38" src="https://cloud.githubusercontent.com/assets/438223/20409161/3ed78594-ad21-11e6-8e68-f0030ee8649c.png">

`npm install events --save`

<img width="365" alt="screen shot 2016-11-18 at 00 55 38" src="https://cloud.githubusercontent.com/assets/438223/20409199/60893b7e-ad21-11e6-9829-c842fac500a5.png">

**Comment by christianalfoni** [comment]
Hm, yeah... that seems strange, cause that would mean the code is not running in Chrome, it is running on the JavaScript engine of iOS, which it should not. Maybe they have made some changes to this? Cause `window` should be defined

**Comment by christianalfoni** [comment]
Let me ask on discord as well, do not remember who worked on this, get some input :)

**Comment by ozanturksever** [comment]
great thank you very much :) it is very hard without devtools.

this might be the change https://github.com/facebook/react-devtools/issues/229

**Comment by christianalfoni** [comment]
Ah, man, that is definitely it! That is super annoying.... hm. I think we have to give support for this: https://nodejs.org/api/debugger.html

**Comment by ozanturksever** [comment]
what do you think about https://github.com/zalmoxisus/remotedev? actually i don't understand how node debugger fits :)

**Comment by christianalfoni** [comment]
@ozanturksever Yeah, I read through the node debugger thing more carefully :) I thought it would be possible to connect Chrome debugger to the server fired up by Node debugger and then pass messages somehow... but yeah.

We have discussed using a websocket connection instead, the problem there is that we actually need to fire up a websocket server. So question is... what is best approach there? Should we run a separate script for the debugger, next to your existing workflow. Should we fire up one on Heroku? That would be slower, especially for large data... but it works out of the box. Should we create an Atom plugin? Though then you have to use Atom :)

So yeah, it is a challenge, but actually not hard to implement at all. You have some thoughts on it?

**Comment by ozanturksever** [comment]
i think i prefer separate script.It doesn't look as a big deal for me. 

I don't think Heroku is a good idea because i don't have internet all the time. Also Atom is plus but not for me, i don't use it as ide, i use IntelliJ. Instead of Atom plugin  i prefer a standalone electron app like https://github.com/jhen0409/react-native-debugger

**Comment by ozanturksever** [comment]
i think the best way for me is a extension to react-native-debugger project, you can spin up websocket process with it, also it supports others like redux so if i use a lib that is using redux, i can see their messages too. Like i am using apollo for graphql with cerebral. i can debug apollo with redux dev tool extension and cerebral with cerebral debugger in the same app.

also i prefer to use standalone app other then chrome tab. Even you can deattach a tab, it is better to reach debugger with command+tab

**Comment by christianalfoni** [comment]
@ozanturksever That is a really good idea :) I will put that next on my list! Thanks a bunch for looking into it!

**Comment by ozanturksever** [comment]
let me know if i can help. Thanks

**Comment by christianalfoni** [comment]
@ozanturksever I got inspired :) 

https://github.com/cerebral/cerebral/pull/463

It is not inside react debugger, but looked at the project and the setup seems so complex. This one is just "download and start". And we have been exploring some more tools related to building Cerebral apps, so maybe this is the start of that :)

**Comment by ozanturksever** [comment]
cool, will it work for cerebral1?

**Comment by christianalfoni** [comment]
@ozanturksever It will require some extra implementation for Cerebral1. Specifically the devtools needs a new version and also have to bring in old version of debugger into the new one. It is possible, but would love to not do it ;-)

**Comment by ozanturksever** [comment]
totally understand :) 
i think i have to make some time to upgrade to cerebral 2. there is a lot of repetitive work :)

**Comment by christianalfoni** [comment]
@ozanturksever Hehe, working on our project now, refactoring. It is a bit of work, of course relative to size of project, but for example components does not need refactor if you set the `signalsProp` option. But yeah... all operators, return promises from actions, path instead of output. But migration guide is still in the works, also some codemods being worked on :)
