### ISSUE TITLE
cerebral2 react-native babel error

### ISSUE THREAD

**Issue by ozanturksever** [cerebral/cerebral#459]
`react-native init test`
`npm install cerebral@next --save`
added `import {Controller} from 'cerebral'` to index.ios.js
`npm install babel-preset-es2015`
`npm install babel-preset-react`
`react-native run-ios`

<img width="372" alt="screen shot 2016-11-18 at 00 36 50" src="https://cloud.githubusercontent.com/assets/438223/20408726/5137f77a-ad1f-11e6-8e09-32c6f57fc4d3.png">

it seems there is a babel conflict with react-native. i tried https://github.com/facebook/react-native/issues/5747 these but no luck.

**Comment by ozanturksever** [comment]
any suggestions on this?  since i need to upgrade to cerebral 2 for debugger. this issue is a deal breaker for me.

Thanks :)

**Comment by Guria** [comment]
will exclude .babelrc files from npm package, thanks for report

**Comment by Guria** [comment]
@ozanturksever fix is on the way. But I want to note that you should consider excluding your node_modules from processing by babel. It could break many other things as well.

**Comment by ozanturksever** [comment]
cool thanks, JS ecosystem is huge, trying to blend in. Too many exceptions :) anyhow thanks.
