### ISSUE TITLE
minLength shouldn't fail when field is empty

### ISSUE THREAD

**Issue by henri-hulski** [cerebral/cerebral#469]
In forms the minLength rule should not apply when the field is empty. 

For this case we have the isRequired option.

Compare with [HTML5](https://www.w3.org/TR/html5/forms.html#attr-fe-minlength):

> The minlength attribute does not imply the required attribute. If the form control has no minlength attribute, then the value can still be omitted; the minlength attribute only kicks in once the user has entered a value at all. If the empty string is not allowed, then the required attribute also needs to be set.

**Comment by christianalfoni** [comment]
Yeah, it makes sense... I think it actually worked this way in previous forms, though after cleaning up a bit too much, this was removed :) Just have to make sure it actually uses the `isValueRules` for the field

**Comment by henri-hulski** [comment]
@christianalfoni hmm..  How can you access `hasValueRules` in rules.js with the signature `minLength (value, form, length)`. 
Also don't understand for what the form argument is used. 

In the signature `matchRegexp (value, _, regexp)` I don't understand the '_' argument.

**Comment by edgesoft** [comment]
@henri-hulski Form is not used in matchRegexp. null is passed as a parameter.

**Comment by henri-hulski** [comment]
@edgesoft this was not the question. 
@christianalfoni Just wanted to understand the '_' argument in matchRegexp and the form argument of minLength and similar.

**Comment by christianalfoni** [comment]
@henri-hulski Form is passed in for `equalsField` etc. 

But maybe we should pass in the field here instead then. So all rules gets the field, the form it is connected to and any values passed in on the rule. Makes sense?

**Comment by henri-hulski** [comment]
Refactored forms to reuse runValidation in #486.
This should make it easier to solve this issue in runValidation.js
For sure it makes forms more dry.

**Comment by henri-hulski** [comment]
@christianalfoni Hmm yeah I think it makes sense to refactor rules.js.
Do you want to look at it?

**Comment by christianalfoni** [comment]
@henri-hulski I have a bit too much on my hands with Debugger, but if our newborn is nice tonight I will get up to speed. But please feel free to make a PR on it, happy to look through it. Or I can get to it later this week :)

**Comment by henri-hulski** [comment]
Fixed in #486.

**Comment by henri-hulski** [comment]
Actually only fixed when `isRequired`.
If not required `minLength` still fails with an empty field.

**Comment by henri-hulski** [comment]
will fix it by adding
```js
!rules.isExisty(value) || rules.isEmpty(value) || 
```
to the rule.

Like this it behaves like most other rules which uses `rules.matchRegexp`.
