### ISSUE TITLE
moving migration into corresponded packages

### ISSUE THREAD

**Issue by edgesoft** [cerebral/cerebral#472]
All of the below mentioned packages need it's own migration guide.

- [ ] cerebral-provider-forms deprecates cerebral-forms
- [x] cerebral-module-useragent
- [ ] cerebral-provider-firebase
- [ ] cerebral-router
- [ ] cerebral-provider-http

**Comment by edgesoft** [comment]
function-tree is new in cerebral-2 so no need. useragent has not changed.

**Comment by christianalfoni** [comment]
@edgesoft What you think about this? Add a "migration" to each package in the docs?

**Comment by edgesoft** [comment]
@christianalfoni Yes! That sound great. Also, your awesome video could help as well :)
