### ISSUE TITLE
debugger issues

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#484]
follow up from https://github.com/cerebral/cerebral/pull/482#issuecomment-262230671

- "Please refresh your app to use the debugger..." is completely useless. We should provide better instructions here.
- 8080 is not a good choice for default port
- must provide a way to configure host:port to listen
- Support several instances and/or apps connected to the same debugger host
- auto publish debugger to github releases

**Comment by henri-hulski** [comment]
Hmm https://github.com/cerebral/cerebral/releases/download/latest/tutorial.zip does not work.

**Comment by Guria** [comment]
@henri-hulski it shouldn't now, because latest is cerebral v1.1

**Comment by christianalfoni** [comment]
@Guria I am on it :)

**Comment by henri-hulski** [comment]
@Guria For Atom it also doesn't work. But maybe this is a special case.

**Comment by Guria** [comment]
@henri-hulski we can just point to release page and let user choose needed artifact

**Comment by henri-hulski** [comment]
@Guria Yep that's a clever solution.

**Comment by christianalfoni** [comment]
@Guria Okay, so I can fix the debugger stuff. You want to look at the deploy and point to latest releases thing? :)

**Comment by christianalfoni** [comment]
@Guria Okay, all the issues should have been handled in latest pull for devtools :) It is just the publishing part I need help with
