### ISSUE TITLE
tutorial chapter 01 build fails

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#485]
see https://cerebral.github.io/tutorial/01/

**Comment by christianalfoni** [comment]
Oh... hm, how does that work?

**Comment by Guria** [comment]
There is errors during build of chapter 1: 
```
Module not found: Error: Cannot resolve 'file' or 'directory' ./components/App in /home/travis/build/cerebral/cerebral/packages/tutorial/src
```

**Comment by christianalfoni** [comment]
@Guria Hm, okay... though what is building those chapters?

**Comment by Guria** [comment]
scripts/build

**Comment by Guria** [comment]
https://github.com/cerebral/cerebral/blob/master/packages/tutorial/scripts/dist.js

**Comment by christianalfoni** [comment]
Ah, cool, thanks! WIll check it!

**Comment by christianalfoni** [comment]
https://github.com/cerebral/cerebral/pull/491

**Comment by Guria** [comment]
please don't close issue until merged
