### ISSUE TITLE
Get "How do I handle..." into docs for 2.x

### ISSUE THREAD

**Issue by edgesoft** [cerebral/cerebral#498]
- [ ] modals
- [ ] Storing server data
- [ ] Feedback messages
- [ ] Popups
- [ ] Long running services
- [ ] Internet Explorer

**Comment by christianalfoni** [comment]
@edgesoft I did a change to menu structure. Now we have a "Best practices" section... those docs should be put in there :)

**Comment by christianalfoni** [comment]
These are in now :)

Except Internet Explorer... though that should probably be part of `install` section
