### ISSUE TITLE
Demo - save item by clicking outside field

### ISSUE THREAD

**Issue by hampusohlsson** [cerebral/cerebral#535]
Perhaps this is by design, but it was not the behavior I expected from the UI, which led me to think that Cerebral is buggy and unstable.

**Steps to reproduce**
- Open https://cerebral.github.io/todomvc
- Type in any word in the field, press enter
- Double click to edit, change item
- Click outside field

**Expected result**
Should update text but reverts to previous value. I would expect previous value if I pressed `esc`

**Comment by christianalfoni** [comment]
Hi @hampusohlsson and thanks for notifying about this!

Maybe you want to clone out cerebral monorepo and suggest a fix? The README file has details on how to get going. Completely understand if you do not have time, but just try to ask when I can :-)

Let me know and I will make the fix unless you want to do it

**Comment by hampusohlsson** [comment]
Hey @christianalfoni , I would love to help but it would probably be faster for you to make the update, since I'm not familiar with the cerebral code base and don't have much time on my hands to learn it right now. But it is a nice project, good work!

**Comment by christianalfoni** [comment]
Okay, just fixed this in new refactor :)
