### ISSUE TITLE
Problem in example code in chapter 7 (v2)

### ISSUE THREAD

**Issue by FWeinb** [cerebral/cerebral#546]
I was just going through the introduction tutorial and I am already sold on the idea of function-trees. This feels very good and is really nice to read. Awesome job! 

But there might be a slight issue in the last code sample in [chapter 7](https://cerebral.github.io/tutorial/08_using-paths.html). 

```js
const toastDebounce = debounce.shared()
function showToast (message, ms, type = null) {
  return [
    set(state`app.toast`, {type}),
    set(state`app.toast.message`, message),
    toastDebounce(ms), {
      continue: [
        set(state`app.toast`, null)
      ],
      discard: []
    }
  ]
}
```

With that code I get `Signal Tree - Unexpected entry in signal chain` because it looks like the `testDebounce` factory is working slightly different, it expects a `continueBranch` as the second argument and needs to be merged into the previous array like this:

```js
const toastDebounce = debounce.shared()
function showToast (message, ms, type = null) {
  return [
    set(state`toast`, {type}),
    set(state`toast.message`, message),
    ...toastDebounce(ms, [
        set(state`toast`, null)
     ])
  ]
}
```

Maybe I am on the wrong track here but with these changes the example is working like expected for me.

**Comment by christianalfoni** [comment]
@FWeinb Hi there and thanks so much for giving feedback :) There is a versioning problem here. Could you try doing:

`npm install cerebral@next function-tree@next cerebral-provider-http@next cerebral-router@next`

This just ensures that everything is indeed running on latest version? :) Will update introduction about this.

**Comment by FWeinb** [comment]
Strange though I have done that. Everything is fine now.
