### ISSUE TITLE
cerebral-forms issues

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#555]
Form factory has wrong [documentation](https://github.com/cerebral/cerebral/tree/master/packages/cerebral-forms#form) . `hasValue`, `isPristine`, `isValid`, `errorMessage` will be [ignored and overwriten](https://github.com/cerebral/cerebral/blob/ec8ba3a1f82869de443ea3675ae0f09c4b0222b3/packages/cerebral-forms/src/utils/configureField.js#L29-L32).
Anyway, form factory returns lot of useless fields to be stored in state even if user doesn't needs it.
```js
{
  value: '', // must be always present, it's ok now
  validationRules: null, // should be omitted if not passed to form factory
  validationMessages: null, // should be omitted if not passed to form factory
  isRequired: false, // should be omitted if not passed to form factory
  requiredMessage: null, // should be omitted if not passed to form factory
  isValueRules: ['isValue'], // should only present if isRequired passed to form factory
  defaultValue: '', // seems ok, but I would rename it to initialValue and made it optional
  hasValue: false, // should never be in state, it is computed
  isPristine: true, //should be in state, and set to false by changeField
  isValid: true, // should never be in state, it is computed
  errorMessage: null, // should never be in state, it is computed
}
```
so when I call `form({field: {value}})` I expect only minimal state in my state-tree:
```js
{
  value: '',
  defaultValue: '',
  isPristine: true
}
```

**Few more notes:**
* should have better example for isTouched, maybe even demo implementation
* `Set a default value for the whole form` contains a typo (newForm)
* `Custom global props` should go before  `Set a default value for the whole form` where it used
* to make `changeField` be more composable it should accept params:
```js
changeField(input`field`, input`value`)
// or
changeField(state`path.to.field`, input`value`)
```
* `changeField` is different from set, because it operates with `value` property and sets `isDirty`
* no need to run any validation on `changeField` since it can be computed
* `validateField` ans `validateForm` action factories is extraneous, see above :)
* `formToJSON` should have operator equivalent:
```js
set(input`formValues`, form`pathToForm`)
```

**Comment by Guria** [comment]
Problem:
existing users of cerebral@next + cerebral-forms@next wouldn't expect such breaking change :(

**Comment by christianalfoni** [comment]
Great feedback @Guria ... since we are still in alpha I think we should just do what is best for the future now. I am a bit busy now, but maybe @edgesoft og @henri-hulski has some time on this? Since you have pretty forms dirty hands? :)

**Comment by Guria** [comment]
another possible operator:
```js
field`${form`path.to.form`}.fieldName`
// eg
httpPost('/signin', {
  login: field`${form`login.credentials`}.login`,
  password: field`${form`login.credentials`}.password`
})
```

**Comment by henri-hulski** [comment]
Sounds interesting. Not yet understand everything like accessing `hasValue`, `isPristine`, `isValid`, `errorMessage` in components when it's not in state. 
I would leave `defaultValue` as it's used for resetting. 
The operators are cool! 

Unfortunately at the moment I have not much laptop time (not much electricity from panel and much work). So now I'm on mobile.

**Comment by Guria** [comment]
@henri-hulski component would look like:
```js
connect(
  ({fieldPath}) => ({ // passed by props
    field: fieldPath,
    hasValue: hasValue.props({fieldPath}),
    isValid: isValid.props({fieldPath})
  }),
  Field
)
```

**Comment by christianalfoni** [comment]
@Guria I suggest we create two general ways of extracting fields with derived state:

```js
import {field, fields} from 'cerebral-forms'

connect({
  fields: fields('some.path.to.form'),
  field: field('some.path.to.form.field')
}, 
  function FormComponent ({field}) {
    field.value
    field.isValid
    field.hasValue
    ....etc
  }
)
```

**Comment by Guria** [comment]
@christianalfoni how it supposed to work? connect accepts only path to state or computed.props({})

**Comment by Guria** [comment]
@christianalfoni please post here revisited blueprint for new forms getting in mind latest API changes

**Comment by christianalfoni** [comment]
New forms specification:

```js
{
  state: {
    form: {
      firstName: {
        value: '',
        validationRules: ['minLength:3']
      }
    }
  }
}

connect({
  form: form(state`form`)
},
  function MyForm ({form}) {
    form.isValid()
    form.getInvalidFields()
    form.getFields()
    form.toJSON()

    form.firstName.isValid // 
    form.firstName.errorMessage // 
    form.firstName.value // Get value
  }
)

function someAction ({resolve}) {
  const form = resolve.value(form(state`form`))
  form.isValid()
  form.getInvalidFields()
  form.getFields()
  form.toJSON()

  form.firstName.isValid // 
  form.firstName.errorMessage // 
  form.firstName.value // Get value  
}
```

**Comment by Guria** [comment]
proposal was updated

**Comment by Guria** [comment]
```
// Should not define text resources in state, should be in component
    form.firstName.failedRuleIndex
```

I see a point, but I don't like proposed solution. Because now you have to track order of validation rules in state and keep it in sync with component.

**Comment by christianalfoni** [comment]
Yeah, I had the same thought, but I still think it is right :) Populating your state tree with text resources is just plain wrong approach... I see text as an element, it is UI. It would be like putting a react component in the state tree. It is just wrong.

If there is some third alternative here that would be great, cause I definitely see the benefit of defining text and rules next to each other, but yeah... just wrong. Maybe:

```js
FormsProvider({
  text: {
    'minLength': (length) => `Text has to be longer than ${length}`
  }
})
```

**Comment by edgesoft** [comment]
minLength example above is maybe not the best solution because minLength might be different text based on some logic. I agree with letting the UI handle this and remove from state. Good suggestion.

**Comment by edgesoft** [comment]
Also need to be able to handle i18n etc

**Comment by Guria** [comment]
I am not saying that poluting state with test resources is good. Just saying that `failedRuleIndex` way is even worse for me.
Provider looks to be a good solution. Another possible solution is `failedRuleKey` and `failedRuleParam`.

**Comment by garth** [comment]
I would also prefer key over index which would probably be hard to maintain.

**Comment by christianalfoni** [comment]
Closing this as new forms is on its way
