### ISSUE TITLE
Last breaking change suggestion: Tags

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#568]
When we first started using template tags with operators we wanted them initially to help express operators with a lot less internals (no parser or compiler). It also gave us the ability to compose paths:

```js
state`foo.${input`bar`}`
```

This is super powerful stuff, but with the experience and late suggestions I think we made a mistake calling them "Operator tags". With the latest suggested feature of router using:

```js
{
  path: '/:id',
  map: {
    id: input`id`
  }
}
```

...operator tags is not the right name and scope for them. Also with suggestions on making connect work like:

```js
connect({
  foo: state`foo.path`,
  someSignal: signal`some.signal`,
  item: state`items.${props`itemKey`}`
})
```

I think we should make a change. This is breaking, but I think it is important that we make the change so "template tags" can live out their full potential.

### Tags
We just call them tags, and there are 5 of them by default:

```js
import {state, input, signal, props, string} from 'cerebral/tags';
```

Tags gives information to operators, connect, module options etc. about targeting something in Cerebral. It is a general concept that can be used with whatever.

#### Operators
```js
import {state, input, string, signal} from 'cerebral/tags';
import {set} from 'cerebral/operators';
import showMessage from '../factories/showMessage';

export default [
  set(state`foo`, input`foo`),
  showMessage(string`Hi there ${state`user.name`}`),
  httpGet('/something', {
    progress: signal`some.signal`
  })
]
```

#### Connect
```js
import {state, signal, props} from 'cerebral/tags';
import {connect} from 'cerebral/react';

export default connect({
  foo: state`foo.path`,
  someSignal: signal`some.signal`,
  item: state`items.${props`itemKey`}`
})
```

#### Router and other options
```js
import {state, input, signal} from 'cerebral/tags';

const routes = [{
  path: '/items/:id',
  map: {
    id: state`currentItemId`
  }
}]
```

#### Documentation
In documentation we can explain **TAGS ** as a general concept for targeting things, not something specifically to operators. Operators becomes less "magic" that way.

#### Scalability
It is now safe to introduce new tags that does not necessarily have to do with operators

#### Dynamic state retrieval in components
An issue now is that you often need two components to grab state. An example:

```js
connect(props => ({
  item: `items.${props.currentItemKey}`
}))
```

The parent component has to depend on `currentItemKey` for the child component to dynamically depend on it and optimize itself. This issue becomes even worse with a computed:

```js
connect(props => ({
  item: augmentedItem.props({itemKey: props.currentItemKey})
}))
```

Now there is a parent component -> child component -> computed dependency. With this new concept these two ones could be implemented as:

```js
// Dynamic state deps
connect({
  item: state`items.${state`currentItemKey`}`
}, ...)
// Computed, same thing
const augmentedItem = Computed({
  item: state`items.${state`currentItemKey`}`
}, ...)
```

This is a huge deal in me opinion, cause it is difficult to reason about the component/computed dependency to get your shit done :)

And yes.. I know we stated no more breaking, but believe me. We have a pretty big refactor in our project to move to this.... so when it comes to "is the juice worth the squeeze", I am positive that it is :)

**Comment by Guria** [comment]
@christianalfoni could you anounce it on release channel in Discord chat?
Can we make it in a non breaking way, but with deprecation. And remove deprecated things on release?

**Comment by christianalfoni** [comment]
Yup, indeed, we can give deprecation warnings on this for sure. And still support second signal arg and string paths... giving warnings

**Comment by Guria** [comment]
Then let's just do it :)

**Comment by christianalfoni** [comment]
Hehe, let me get on it after the debugger changes I am making now :)

**Comment by gaspard** [comment]
@christianalfoni I am not sure I understand the change completely.

So connect with a passed itemKey prop would be:

```js
connect({
  item: state`items.${input`itemKey`}`, // dynamic state
  onClick: signal`items.itemClicked`, // dynamic signal
  prefs: state`user.prefs`, // normal state
  onFoo: signal`foo.bar` // normal signal
},
/* no signal object */
/* optional mergeProps */
function MyComponent ( { /* merged props */ } ) {
// ...
})
```

Indeed, this is a big change that involves rewriting all imports in signals using operators and all components... But yes, it makes sense because reading the connect object is like a definition: "item is a state value of...", "onClick is a signal from ...". Very good.

Also please tell if any of these if not true:

1. "input, state, signal and string" are no longer exported in "cerebral/operators"
2. We do not support standard paths like "foo.bar" in connect and connect no longer takes a function
3. It now feels strange to have `state.get('foo.bar')` and `input.bing` inside actions. Is there a way to use tags there ? Maybe like this:

```js
const someAction = ({get, set}) => {
  const name = get(state`some.name`)
  set(state`other.name`, input`key`)
}
```

**Comment by Guria** [comment]
@gaspard one note: dynamic state and signal would use `prop` tag instead of `input` to avoid confusion

**Comment by Guria** [comment]
> "input, state, signal and string" are no longer exported in "cerebral/operators"
> We do not support standard paths like "foo.bar" in connect and connect no longer takes a function

Will be kept with deprecation until release. and I would personally keep passing function as first argument

> It now feels strange to have state.get('foo.bar') and input.bing inside actions. Is there a way to use tags there ?

I see your point, but there is no need in tags inside actions. Tags just helpers to avoid creating actions or any other sort of callbacks. But in action we can just work with values and strings directly.

**Comment by garth** [comment]
Do we still have mergeProps function?

**Comment by Guria** [comment]
@garth yes

**Comment by christianalfoni** [comment]
@gaspard 

1. Correct, exported from "cerebral/tags"
2. Correct, though `props` is used, not `input`. Tags are targets, so "Input" is not a valid target for connect, but it would be in a signal. Invalid target usage throws errors. Like `signal` is not a valid target for the `set` operator
3. Actions are low level imperative code, not functional. I think it is better to keep actions imperative and signals functional :)

@garth Jup, will be three args to connect. Extract stuff from Cerebral. State and signals. Second arg is the merge prop thingy. And last is component :)

**Comment by maxfrigge** [comment]
@christianalfoni so using the new merge props will be the new gold standard for computed values in views?

**Comment by christianalfoni** [comment]
@maxfrigge Computed is a different discussion ;-) With this change computed works the way it does today

**Comment by Guria** [comment]
Live now
