### ISSUE TITLE
improve error on controller.getSignal before controller was initialized

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#570]

**Comment by christianalfoni** [comment]
You mean trigger signal before controller is initialized?

**Comment by christianalfoni** [comment]
or yeah... get signal I suppose is better, so you do not grab signals before they are evaluated

**Comment by christianalfoni** [comment]
https://github.com/cerebral/cerebral/pull/728

**Comment by Guria** [comment]
@christianalfoni issues is usually closed only after successful reaching master. you can make it happen automatically if you mention it in pr with "resolves" or "closes" keyword.
