### ISSUE TITLE
decide what to do when module without state has submodule with state.

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#597]
Previously it failed with setting unexisted path in a tree.
Now it [sets state for each module](https://github.com/cerebral/cerebral/blob/master/packages/cerebral/src/Module.js#L11).
Not sure if it good behaviour though, because it will pollute state tree for stateles modules.
Maybe better to change it so when nested module with state appears - whole path is created.
Or just throw warning to have state defined on all parents.

**Comment by christianalfoni** [comment]
@Guria 

Hm... not been into the issue, but I think the modules tree should be reflected in state tree. Imagine if you create lots of references to paths which has now a "hidden" step... suddenly you decide to add some state to this "non state" module... you possibly have to refactor bunch of stuff.

It is also not what to expect... so we have to explain it. would suggest it is uncommon, and when it happens it is not a big issue.

But yeah.. state should be`initialState || {}` in my opinion :)

**Comment by garth** [comment]
creating empty state for a module is also useful, tells you the the module was created but has no state.

If a module is like a piece of an app, and for the root state (controller) you would still create an empty store, then I guess a module should be the same.

**Comment by Guria** [comment]
ok, then keeping as  is. thanks
