### ISSUE TITLE
(Feature) Reset model state to initial values

### ISSUE THREAD

**Issue by idream3** [cerebral/cerebral#604]
Ability to reset state to initial values.

Add `state.reset()` or `controller.resetState()`?

Use case: User has logged out and a new user logs in, previous state is still in the tree.

**Comment by Reltik** [comment]
Yeah, that could be very cool! With this we could avoid the need to put the initial state in a separate file and Object.keys with a loop to reset it from a function

**Comment by christianalfoni** [comment]
Addition to API, can look into this after release :)

**Comment by christianalfoni** [comment]
This would require every model to have a `reset` method. They would themselves be responsible for keeping the initial value, typically by doing `JSON.serialize` on the initial state. When resetting the `JSON.parse` would need to be merged into the root of the state.

This needs to be fixed these places:

https://github.com/cerebral/cerebral/blob/next/packages/node_modules/cerebral/src/Model.js

https://github.com/cerebral/cerebral/blob/next/packages/node_modules/%40cerebral/baobab/src/index.js

https://github.com/cerebral/cerebral/blob/next/packages/node_modules/%40cerebral/mobx-state-tree/src/Model.js

And in the upcoming `fluent` addon

**Comment by christianalfoni** [comment]
Housekeeping!
