### ISSUE TITLE
change detection

### ISSUE THREAD

**Issue by fopsdev** [cerebral/cerebral#608]
Hi Guys

Just had a brainfart before after following @christianalfoni and @gaspard in a discussion about how strict mode could work.
It turns out that there is no easy way to easely configure a change detection strategy (Using * and ** is a start but does it cover use case x?)
So why not just stick with the current detection which seems to catch a lot of usecases BUT give devs a possibility to more finegrained control by letting them define a function like:

```js
...
connect({	
 c: state`a.b.c`
 },{
changedArgs => changedArgs.path.indexOf('.b.') > -1 && changedArgs.operation==='list'
})
...
```

if this function returns true that means that the **component** (or **computed**) needs recalc/rerender.
In words for this sample used in a component it would mean:
the parent of "c" is a list and if it changes i need to rerender

used in computeds i think this function could really help to decide if a cache needs to be busted or not

**Because cerebral should already know what has changed** it could deliver the changedArgs like:
``` {path: '.a.b.', operation:'list', index:xy} ``` whereas the operation type is a new group property of the operators.
eg. operator push, pop would be in the group 'list' and set, merge would be in a group like 'object' or so

I believe that 90 up to 100% (of course depending on app complexity) is already handled by today non-strict standard so there is normally no need for this function. So why introduce strict if its not even necessary and maybe confusing/error prone for new users?

Please leave your thoughts here and keep in mind that this is maybe just a brainfart :)

**Comment by fopsdev** [comment]
Additional remark how you could look at this new functionality:
The default detection catches a lot of changes and maybe rerender too much.
The mentioned function will help reduce the changes (it's like an additional filter on top of the current detection)
Hope to be clear :)

**Comment by fopsdev** [comment]
i think we need usecases where we can see that strict-mode is not enough and then let us know here and we can discuss how this feature could help and maybe could be included in a future version

**Comment by fopsdev** [comment]
again, i see this as a optinization feature which should not disturb the beginner (he doesn't even need to know its there) when following the "happy path" ;)
but having possibilities to optimize after recognising that an app gets slow is something we should be prepared for
btw. other framewroks also have low level possibilities to optimize:
https://www.youtube.com/watch?v=FIi6AkI7wKE

**Comment by christianalfoni** [comment]
Hi @fopsdev ,

Sorry for not looking into this before. This is definitely an interesting idea! Currently it will be too much of a change, due to the dependency match is not done inside the component, it is actually done inside the `Controller`. 

It might be possible to register custom dependency matches, but it is in risk of making the dependency matching slower.

But would suggest we meet a performance issue before looking closer into it. This idea is definitely something to keep in mind :)
