### ISSUE TITLE
Add Info to missing signal message

### ISSUE THREAD

**Issue by idream3** [cerebral/cerebral#609]
Would be great if we can get the name of the component in question in the error message, makes it a bit tricky to track down.

![image](https://cloud.githubusercontent.com/assets/1082632/22093531/4b56a18a-de6b-11e6-811a-743290caa56c.png)

**Comment by christianalfoni** [comment]
Yeah, let me shout out on discord, try to get someone to fix that :)

**Comment by reflog** [comment]
fixed in #740
