### ISSUE TITLE
Another approach to express dependencies in connect 

### ISSUE THREAD

**Issue by FWeinb** [cerebral/cerebral#611]
While there is #607 in progress I would like to open a discussion about an idea I had to express dependencies in a more declarative way. Let me start with an example: 

```js
const fullname(firstname, lastname) => `${firstname} ${lastname}`

connect({
  name: [state`firstname`, state`lastname`, fullname]
});

```

So my idea was to be explicit about dependencies by expressing them in a way the connect function knows exactly what to do with the data. So a property on the connect object would take an array where n - 1 items are Tag's and the n-th element is a function that takes these resolved values. 

One benefit about this is that the function `fullname` is not tide to any Cerebral specific API and can be tested without a problem.

Just an idea feel free to close.

**Comment by christianalfoni** [comment]
Hi @FWeinb :) It is a cool idea, though it is very similar to Computed :) Where you define your state deps as an object and those are passed into a function.

The `(getProp, getState) => {}` signature allows for something Computed and this suggestion is not able to handle... and that is grab some state first, then create new dependencies based on existing state. For example you grab the user first, then you iterate the projects of the user and create new dependencies for each project. That kind of dependency handling is not possible with the signature above or with Computed :)

That said, it is a very clean and nice suggestion indeed!

**Comment by FWeinb** [comment]
I don't think of this as a replacement to `(getProp, getState) => {}` I would think of this as a middle ground between both other solutions. So there are three possible ways to connect to a value: 

1. Just plain Tags (even nested ones)
2. Array of Tags ending in an function 
3. Taking full control with `(getProp, getState) => {}`

I think that 1. will be used in most cases. 2. if you want to decouple a compute function from the state dependencies and 3. if you really want to have control.

**Comment by edgesoft** [comment]
@FWeinb Think this is a very good approach and suggestion.

**Comment by henri-hulski** [comment]
I like it also. 👌

**Comment by christianalfoni** [comment]
This is pretty much how the `compute` API ended up :)

```js
const fullname(firstname, lastname) => `${firstname} ${lastname}`

connect({
  name: compute(state`firstname`, state`lastname`, fullname)
});
```

So closing it...
