### ISSUE TITLE
feature(provider-http): Add option to switch on statusCodes

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#613]
Switching on status codes can currently be achieved by something like this:

```js
const checkOutput = [
  equals(input`status`),   {
    '200': [],
    '201': [],
    'otherwise': []
  }
]

http.get('/some/url'), {
  success: checkOutput,
  error: checkOutput
}
```

But it would be nicer to be able to switch on statusCodes directly via an option. eg:

```js
http.get('/some/url'), {
  '200': [],
  '201': [],
  'otherwise': []
}
```

**Comment by christianalfoni** [comment]
Thumbs up for this... I thought we already implemented it? If not, yeah, definitely :)

**Comment by henri-hulski** [comment]
Yeah really useful!

**Comment by Guria** [comment]
hmm, what if I really do not care about status codes? It would mean that I have to define all possible success codes with the same chain.

**Comment by henri-hulski** [comment]
I thought that you can use both. Either status code or success / error.

**Comment by Guria** [comment]
@christianalfoni could we explore available properties on path.* to select behaviour?

**Comment by garth** [comment]
Yes, suggestion is for this to be an option

**Comment by Guria** [comment]
ok. then we definetely should have this

**Comment by christianalfoni** [comment]
@garth @garth @henri-hulski 

The action just checks the `path`.. if a status code is on `path[response.status]` then it runs it... if not it uses `success` or `error` with current logic :)

**Comment by garth** [comment]
so it's already done? I will test, thanks!

**Comment by christianalfoni** [comment]
I thought it was? Can not see it in the code though... but I did talk to someone about it, hehe. But yeah.. just suggesting the implementation:

```js
.then(function (response) {
  return path[response.status] ? path[response.status](response) : path.success(response)
})
```

**Comment by garth** [comment]
https://github.com/cerebral/cerebral/pull/617
