### ISSUE TITLE
Allow users to name individual operators

### ISSUE THREAD

**Issue by idream3** [cerebral/cerebral#622]
I don't know about everyone else but I see `operator.set`, `operator.merge` as being unnecessary in the DEBUGGER signal flow and don't actually add to the developer experience. The 'state' mutation below the name already tells you what it is doing Eg.

![image](https://cloud.githubusercontent.com/assets/1082632/22279229/3c78649c-e32e-11e6-9ba4-3f0ec9d0a401.png)

I propose we add a `name/description` parameter as last optional argument to operators, or any other factory for that matter.

I have been playing with this idea `set(target, value, name/description)`

`set(state'${PATH.allUsers}', {}, 'Empty all users')` would look like this in the debugger

![image](https://cloud.githubusercontent.com/assets/1082632/22279251/707c4100-e32e-11e6-9d5e-e1eeccce0369.png)

So now we have the technical operation, and we also have the human readable description. There are at least two nice benefits of this.

1. we are not limited to camel cased function names eg. EmptyAllUsers. But instead we can write an actual sentence as above.
2. It can serve as a code comment. This is quite important in my book because, even though operators and tags make reading a line of code simple and declarative, it is even easier and faster to read a comment to understand. Especially when you have long state paths, mixed with path constants etc...

Below is a before & after type example

BEFORE

```javascript
[
  set(input`group`, input`result`),
  set(state`Group.data.${input`group.id`}`, input`group`),
  set(state`${PATH.userAssigned}.${input`group.id`}`, input`group`),

  // Now we need to add group id to the project and save
  set(input`projectId`, state`Project.selectedId`),
  set(input`groupId`, input`result.id`),

  function buildProjectRequest({input}) {
    return {
      children: {
        [input.groupId]: true
      }
    }
  },

  patch(string`${BACKEND}${input`projectId`}`, {
    type: TYPE_PROJECT,
    version: DEFAULT_VERSION,
    children: input`children`
  }), {
    ...
  }
]
```
![image](https://cloud.githubusercontent.com/assets/1082632/22279505/18905bf0-e330-11e6-82a2-4996547f20d7.png)

AFTER

```javascript
[
  set(input`group`, input`result`, 'Add result to input'),
  set(state`Group.data.${input`group.id`}`, input`group`,'Set group to state'),
  set(state`${PATH.userAssigned}.${input`group.id`}`, input`group`, 'Set group to user'),

  // Now we need to add group id to the project and save
  set(input`projectId`, state`Project.selectedId`, 'Grab project id'),
  set(input`groupId`, input`result.id`),


  function buildProjectRequest({input}) {
    return {
      children: {
        [input.groupId]: true
      }
    }
  },
  patch(string`${BACKEND}${input`projectId`}`, {
    type: TYPE_PROJECT,
    version: DEFAULT_VERSION,
    children: input`children`
  }, 'Patch project'), {
    ...
  }
]
```

![image](https://cloud.githubusercontent.com/assets/1082632/22279634/be12821a-e330-11e6-8735-9693c9a09d43.png)

**Comment by Guria** [comment]
currently it can be achieved with small wrapper:
```js
namedAction (name, action) {
  action.displayName = name
  return action
}

namedAction('setUser', set(state`user`, user))
```

**Comment by Guria** [comment]
BTW, latest @next has improvements in displaying operators. Can you check it out and revisit an issue?

**Comment by idream3** [comment]
Thanks @Guria, I hadn't considered your approach. I think something like that could work well.

I can see the changes to the debugger but I don't think they add anything, infact, I still think it is doubling up on information.

![image](https://cloud.githubusercontent.com/assets/1082632/22307977/f8273080-e3a9-11e6-83f0-2e3e16f1f87a.png)

operator.set state`App.loaded`, false

is exactly the same, but less clear than

set App.loaded false

BTW I am planning to do some work on the visual display of the debugger. I want to make my own theme.

**Comment by Guria** [comment]
Would be great. Debugger needs some visual impomevents to make ton of information represented more clear.
