### ISSUE TITLE
unhelpful error messages

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#630]
Uncaught Error: Cerebral - Tag of type PROPS can not be used in this context
Uncaught TypeError: Cannot read property 'getTags' of undefined Hoc.js:163

**Comment by christianalfoni** [comment]
Difficult to give any more info, because it has no idea in what context it is being used. Could change the wording though... like "You are using a PROPS tag where it can not be used...", not sure what scenario it happens in though?

**Comment by edgesoft** [comment]
@Guria @christianalfoni Can we close this?
