### ISSUE TITLE
signal `validateInput` helper

### ISSUE THREAD

**Issue by idream3** [cerebral/cerebral#646]
We are using a factory method called `validateInput` which describes the required/optional inputs and their types and throws errors in development. I have found this very useful as a way to catch errors and to also document signals.

```javacsript
const triggerModal = [
    validateInput('modalName:string'),
    ...
]
```

## Syntax

`name:type`

#### type
`string|number|boolean|array|object|any`

By default they are required params. Optional params can be signified using `~`.

`~name:string`

```javascript
 validateInput('modalName:string', '~editMode:boolean'),
```

**Comment by christianalfoni** [comment]
Cool! Would suggest a change though:

```js
validate({
  someProp: String,
  someOtherProp: Number
}, [
  actions
])
```

So it is rather a factory of the signal itself :)

**Comment by idream3** [comment]
Oooh, that's goood!

**Comment by edgesoft** [comment]
@idream3 Maybe we could close this?
