### ISSUE TITLE
bug(http) Date in querystring

### ISSUE THREAD

**Issue by Reltik** [cerebral/cerebral#667]
If one of the properties of an object is of type Date, the urlEncode function fails to add it to the query.

The reason is here (utils.js - LOC 48)

`str.push(typeof v === 'object' ? urlEncode(v, k) : encodeURIComponent(k) + '=' + encodeURIComponent(v))
`

The ternary checks if the param is an Object. If so it would be call itself recursively to encode its properties. And because Date is an object too it tries to do so. The result is that the param is just skipped and a empty '&' is added in the querystring.

**Comment by Guria** [comment]
See reasoning in #666. Closing for now. Please feel free to continue discussion.
