### ISSUE TITLE
Exceptions in compute are lost

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral#670]
Exceptions thrown in compute functions are not logged and the compute returns undefined without indicating that something failed.

Ideally cerebral should rethrow when computes throw exceptions.

**Comment by christianalfoni** [comment]
Does this still happen and if you have time, could you create a PR with a test where it fails? I can jump on and look at it :)

**Comment by edgesoft** [comment]
Can we close this? @Guria @christianalfoni @garth
