### ISSUE TITLE
How to Handle Server Push Notifications 

### ISSUE THREAD

**Issue by MrLoh** [cerebral/cerebral#673]
First of all. Cerebral looks really great it is so much less clutter as compared to redux. 

However I'm not sure how to handle actions that don't originate from the UI but from the server. For example a push notification. Since there is no component to `connect` to, where would I wire up those signals and dispatch the actions?

**Comment by edgesoft** [comment]
@MrLoh Great to have you here. If you use for example websockets there is an example on webpackbin for this. 

https://github.com/christianalfoni/webpack-bin/blob/master/app/modules/Live/services/live.js

**Comment by edgesoft** [comment]
@MrLoh Great to have you here! If you are using websockets for example there is code that you can look at over here. Note that this is cerebral 1 with services but I think you can look at this and get some insight. 

https://github.com/christianalfoni/webpack-bin/blob/master/app/modules/Live/services/live.js

**Comment by MrLoh** [comment]
I didn’t quite understand the live example. But I found a solution that works well for me, adding a Subscription element to those views which need some live updates. The component gets a `query` to subscribe to and an `onNext` callback that triggers a signal that handles the event. I am using [Horizon](http://horizon.io) here. This makes it easy to add and remove subscriptions from components easily.

```js
import { connect } from 'cerebral/react'
import { signal } from 'cerebral/tags'

export default connect({
    onNotification: signal`app.handleNotification`
}, ({onNotification}) => (
    <HorizonSubscription
        query={(hz) => hz('notifications').limit(1)}
        onNext={(res) => onNotification({notification: res[0]})}
    />
    // ...
))
```

The component then looks like this, it gets the connection to the server (`hz`) from a context provider. 

```js
export default class HorizonSubscription extends React.Component {
    constructor(props) {
        super(props)
        this.state = {subscription: undefined}
    }
    componentDidMount() {
        let {hz} = this.context
        let {query, onNext, onError, onClose} = this.props
        let subscription = query(hz).watch().subscribe(onNext, onError, onClose)
        this.setState({subscription})
    }
    componentWillUnmount() {
        this.state.subscription.unsubscribe()
    }
    render() {
        return null
    }
}
```

**Comment by christianalfoni** [comment]
@MrLoh Yup, this is definitely a pattern worth using :) You could also make horizon a provider. It would allow you to do things like:

```js
function someAction ({horizon}) {
  horizon.on({/*someQuery*/, 'some.signal')
}
```

You might want to do this related to route changes, rather than component mount/unmount.

Basically you hide all the observable stuff inside the provider and just give an API to start and stop watchers that triggers signals.

Let me know if you want to look into it, can give you more pointers :)

Closing it for now
