### ISSUE TITLE
operators: using whole tree of a tag from root on

### ISSUE THREAD

**Issue by fvgoto** [cerebral/cerebral#678]
Using the whole tree a tag represents should be possible.
Especially for `props` (former `input`).

Syntax propositions (I think I've seen first one somewhere...):
```
set( state`foo`, props`` )
set( state`foo`, props`.` )
set( state`foo`, props`*` )
```

UseCase:
Store the whole `props` at a state path.
```
// in a component:
  props.mySignal({ width: 3, height: 5 });
// action
  set( state`size`, props`` )
// should result in following state tree
  ...
  size: { width: 3, height: 5 },
```

I guess, it's the tag string parsing code that should be fixed for this...

**Comment by fvgoto** [comment]
Links to #679

**Comment by hipertracker** [comment]
It's not necessary. Too magic.

**Comment by Guria** [comment]
closing as noop for now, but feel free to continue discussion here
