### ISSUE TITLE
SUGGESTION: Functions or chains... does it matter?

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#695]
After some discussions with @tiagocpontesp and I am suggesting a possible change to `function-tree` which will clean up quite a bit. We have been talking around these concepts earlier, but nothing concrete has come out of it yet. So!

```js
[
  actionA,
  ...chainB,
  [
    actionC,
    ...chainD
  ]
]
```

This is how we define actions and chains now. This code actually has a bug. If `chainD` was defined like this:

```js
[
  [
    someAction,
    someOtherAction
  ]
]
```

`function-tree` would throw an error.

The suggested change is to be able to write like this:

```js
[
  actionA,
  chainB,
  PARALLEL(
    actionC,
    chainD
  )
]
```

That means `function-tree` automatically figures out if it is a function or an array you insert. If it is a function it works as normal of course and if it is an array, it will merge it in for you. No need for spread. It basically just flattens all nested arrays.

When you want something to run in parallell you explicitly say so. Again, the arguments works the same way, does not matter if it is just a function or array.

## Summary
The point here is to clean up signals. No more spread or "hard to read" arrays in arrays. Conceptually it does not matter if spread is there or not, the name of the chain is what makes sense. 

It would allow for new patterns where you do not explicitly create folders for every kind of item in a signal (actions, chains, signals etc)... you could rather do things like:

```
/modules
  /moduleA
    /factories
      someFactory.js
   someAction.js
   someChain.js
   index.js
```

You would not be forced to separate so much by folders.

Tell me what you think :)

**Comment by tiagocpontesp** [comment]
would this still be on v2? :)

**Comment by garth** [comment]
Interesting, so chain (as a concept) would no longer exist. An array would only be a way to package an ordered set of actions.

Would this affect paths in any way?

**Comment by christianalfoni** [comment]
Yeah, `chains` would be just `grouping`, exactly @garth.

It would not affects paths, as those need to follow an action, which they still do when arrays are flattened... I believe :)

Also what to note here is that using `spread` would not be a problem in existing code, you just did one level of flattening for the `function-tree` manually. Also detecting "array in array" could give a warning about usng PARALELL instead. So this can be deprecated.

@tiagocpontesp , so yeah, this can be done with C2

**Comment by henri-hulski** [comment]
I think the concept is great. 
Still not sure about the PARALLELL keyword (side note: correctly PARALLEL).
What about 
```js
[
  actionA,
  chainB,
  ll(
    actionC,
    chainD
  )
]
```
Or isn't it possible to wrap the parallel actions in something else then an array? 
E.g. an object with `{...}`?

**Comment by christianalfoni** [comment]
@henri-hulski I would really like to avoid importing something to express parallel... though it is not very common, so doing an `import` for it I guess is okay. Not sure how it could be expressed with literals.

You can do things like:

```js
import {PARALLEL as ll} from 'function-tree'
```

but yeah... how to express it is totally up for discussion :)

**Comment by garth** [comment]
+1 for something other than all caps. Without an import would be even better.

**Comment by christianalfoni** [comment]
I do not see any way to express it with literals, but can do it as easily as:

```js
import {P} from 'function-tree'

export default 
```

Think it is pretty expressive, we we would have to do something like:

```js
export default ({P}) => {
  return [
    actionA,
    P(
      actionB,
      actionC
    )
  ]
}
```

Would favor import here definitely...

**Comment by henri-hulski** [comment]
I think P is not clear enough.
Difficult to associate it with parallel. 
But also don't have a great idea at the moment. 
Maybe something will come up. 

Yeah but I think it's a really good idea.  ☺

**Comment by maxfrigge** [comment]
I used to do the exact same thing before I migrated my server code to function-tree.. so big +1!! 

How about flatten all arrays that are [].parallel !== true. You can then either set it before exporting or with a helper function when composing. In promise syntax it would be all() which is short and easy to get.

**Comment by bfitch** [comment]
It's equivalent to `Promise.all` but for actions, right? Maybe `action.all()` or just `all()`?

**Comment by henri-hulski** [comment]
all() sounds good.

**Comment by maxfrigge** [comment]
It's a similar thought at least.. Promise.all just resolves rather then executing. Tomato .. tomato :)

**Comment by tiagocpontesp** [comment]
And why not support any [defined] Promise collection method?:
```javascript
Promise.all
Promise.props
Promise.any
Promise.some
Promise.map
Promise.reduce
Promise.filter
Promise.each
Promise.mapSeries
Promise.race 
```

Shouldn't we be responsible for our own mess? :)

So maybe?:
```javascript
[
 chainA,
 actionA,
 'all', [
  chainB,
  actionB,
 ],
 'race', [
  raceableChain,
  raceableAction,
 ],
]
```

**Comment by christianalfoni** [comment]
Haha, I thought about Promise.all when I went to bed yesterday... yeah, I think `all` creates a good bridge with `Promise.all` :)

**Comment by christianalfoni** [comment]
@tiagocpontesp Yeah, this is what I meant by opening new possibilities :) This bridge with promises I did not see though, which is great. Cause instead of coming up with crazy stuff we can rely on proven Promise methods. But have to look into that stuff as next step, looking into code for initial change first :)

**Comment by schotime** [comment]
I like the method calls here that wrap the actions rather than relying on indentation to understand what's going on. Very powerful to see the closing bracket to know when all is finished. 

I think having both Parallel or All and P as an alias would be fine.

**Comment by gaspard** [comment]
Excellent idea. Removes a lot of confusion.

"All" does not make sense. In the Promise world "all" means "execute all" or "wrap all". It's the "Promise" part of "Promise.all" that says this is async.

"PARALLEL" all caps looks like a constant but it's a function. I think we should stick with naming conventions for cerebral. We have "connect", "compute", etc. It should be "parallel" if we want to use this keyword.

**Comment by edgesoft** [comment]
Think the latest discord suggestion is the best.

```js
import {execute} from 'cerebral/operators'

export default [
  execute.all(

  ),
  execute.race(

  )
]
```

**Comment by christianalfoni** [comment]
Hm, yeah...

We have to lean on something:

1. Create bridge with Promise API (all, race etc.)
2. Find our own (p, r)
3. Be explicit (parallel, race)

I guess this is a good balance, cause you can name it whatever you want:

```js
import {execute} from 'cerebral/operators'

const {parallel as p, race as r} = execute

export default [
 set(state`some`, props`some`),
  p(),
  r()
]
```

Or just be explicit:

```js
import {execute} from 'cerebral/operators'

export default [
 set(state`some`, props`some`),
  execute.parallel(),
  execute.race()
]
```

**Comment by maxfrigge** [comment]
If actions/chains get thrown in the same bucket, do we then still need the signal abstraction? Couldn't we then directly "trigger" a chain or action from a view?

**Comment by henri-hulski** [comment]
@gaspard I like all(). This is is the Cerebral world, so it can have a different meaning like execute all. 
In addition it's part of the word par**all**el and has `ll` at the end, which can also be associated with parallel. 
@edgesoft yeah `execute.all()` is great and more explicit. Maybe leave `all` as a shortcut?

**Comment by henri-hulski** [comment]
@maxfrigge I just thought about the same.  All this mapping from signals to chains and from past to present tense feels a little annoying.

**Comment by edgesoft** [comment]
@maxfrigge @henri-hulski But you woulds till have to compose complex signals in it's own file? Can you write some more about the suggestion you have?

**Comment by christianalfoni** [comment]
@henri-hulski I also like leaning on Promise API as well (all, race), because funtion tree basically is an execution wrapper around promises :)

@maxfrigge I would state signals are triggering a chain directly from a view :) The reason we need signals is more a conceptual thing. Point to signals by path, hook in router, point to them by path on different operators (firebase, http) etc...

**Comment by maxfrigge** [comment]
@christianalfoni so basically modules expose "public" actions, which can then be referenced and accessed in views. As you say.. more of a conceptual thing. I do agree though with @henri-hulski that the past/present tense thing can be a bit cumbersome and would assume that it might be even more confusing when there won't be a signals folder anymore and instead have everything in actions. Maybe it's time to iterate on the naming and mental model?

**Comment by maxfrigge** [comment]
@edgesoft from what I understood.. the won't be a signals folder anymore.. signal would just be then name of an event, which triggers a chain. And since chain and actions are the same I thought that everything would be in actions.. some are small .. soma are larger. Or was the original idea to keep signals as the are and just merge chains into actions?

**Comment by edgesoft** [comment]
@maxfrigge @christianalfoni Ok, I might have interpreted it wrong. Could we make a model of the total changes suggested?

**Comment by henri-hulski** [comment]
@edgesoft I mean mostly the mapping which was introduced in Cerebral 1.
So instead of `thatHappened`you would use in the view `doThis`. 
But I have to think about this some more as concept we have now still make sense.

**Comment by henri-hulski** [comment]
@maxfrigge @edgesoft I think the original idea by @tiagocpontesp was to remove both, the signal and actions folder and have them directly in the root or module folder.

**Comment by henri-hulski** [comment]
Just to get a little more crazy,  what about using trees (short for function-trees) instead of signals? 
😉

**Comment by christianalfoni** [comment]
To me personally I think naming in past tense is important. Lets say you name a signal `saveUser`. There are problems with this IMO:

1. Nothing indicates it being a signal... it might as well be som arbitrary action

2. No indication of what happened in the UI for it to trigger

3. It indicates one operation, not a flow of operations

While `saveUserClicked` is the opposite.

1. It is a signal, cause it is named passed tense

2. It indicates the something was clicked in the UI

3. It can be any number of operations and the operations can completely change without changing the name of the signal

Also looking through files you understand what "events" that can happen in the UI. Without signals you would have to look through components, look into module files etc. to understand how things are connected.

This is of course opinions, but it is something I really want to expose to developers, because it helps a lot with structuring the project "for the next developer" :)

Even though this change opens up possibility make everything flat (easier), that does not mean it increases readability of the project. For me:

```
/someModule
  /actions
    saveUser.js
  /signals
    saveUserClicked.js
    newUserAborted.js
    newUserNameChanged.js
  index.js
```

Reads a lot better than:

```
/someModule
  saveUser.js
  saveUserAction.js
  abortNewUser.js
  changeNewUserName.js
  index.js
```

If you would hide everything inside `index.js` its readability from a "file structure perspective" is reduced even more and `index.js` is in risk of getting insanely bloated.

Generally making things "easier" makes it less explicit and readable. Have to be very careful about that :)

So with this change I would personally just remove the `chains` folder, rather just have `actions`, them being a single action or a group of actions. But will still use `signals` folder for readability and prevent bloated `index.js` and also keep `factories` folder to know that these create actions.

**Comment by henri-hulski** [comment]
@christianalfoni After thinking about it some more I'm agree with you:
It get's really easier to reason about the App with some structure and it's also nice to have a best practice, so if you look in another Cerebral App you know where to look for what.

Just never really understood the difference between the signals and chains folder. I thought it was just a renaming in Cerebral 2 (or 1?) using some mapping from signals to chains. I thought the signals folder is already gone.

**Comment by christianalfoni** [comment]
@henri-hulski Good question :) Yeah... there has really been two different approaches. I have always favored the signals approach because you can read your app right off the file structure. But I know others, like @garth and @Guria, has rather been using:

```js
/someModule
  /actions
    saveUser.js
  /chains
    createUser.js
    abortUser.js
    changeNewUserName.js
  index.js
```

So inside `index.js` you would:

```js
{
  signals: {
    saveUserClicked: createUser
    userAborted: abortUser
  }
}
```

Personally I do not perfer that because it forces me to actually look into the `index.js` file to figure out what chains belongs to what signals. With the `signals` folder approach you just go straight to your signal :)

But this is conceptually and opinionated. I think it is really good that we have a very flexible way to structure your app with this change, BUT having practices for actually structuring should be on top of this. "Use the signals pattern", "use the chains pattern" or "use the flattened pattern"... kind of thing :)

**Comment by henri-hulski** [comment]
@christianalfoni Yeah that makes sense. So I think I will go back to the signals pattern specially after this change the chains pattern doesn't makes sense anymore.

**Comment by tiagocpontesp** [comment]
on the server i place the chains in "./_stories", so i know i can throw any contents on an function-tree "runner", and leave the inner folder structure as whatever makes sense for their invokers. some room has been made, by not to having to separate actions/ and chains/. :)

**Comment by christianalfoni** [comment]
Closing this :)
