### ISSUE TITLE
HELP NEEDED: Website

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#696]
- [x] Refactor `cerebral-provider-http` to expose its factories behind `cerebral-provider-http/operators`
- [x] Refactor `cerebral-provider-http` to expose a `uploadFile` method instead of `fileUpload`. It should just instantly send the file and supports template tags:

```js
function someAction ({http, state}) {
  return http.uploadFile(state.get('someFile'), {
    onProgress: 'some.signal.path'
  })
}
```
- [x] Review `developer_guide`
- [x] Add `useragent` and `forms` into TOOLS, with same format as existing
- [x] Add function-tree as well to tools, same format

**Comment by bannerintheUK** [comment]
Began `cerebral-provider-http` operators refactor - 24/2/17

**Comment by christianalfoni** [comment]
this is done
