### ISSUE TITLE
SUGGESTION: Function tree instances

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#710]
Had some discussions on how function-tree can be a bit friendlier about creating more instances, typically for server side usage.

The API change would be:

```js
const FunctionTree = require('function-tree')

const myFunctionTree = new FunctionTree({
  // Add directly to context (ContextProvider)
},
[
 // Providers
])

// Global listeners
myFunctionTree.on('EVENT', () => {})

const run = myFunctionTree([
  // Some tree definition
])

// Specific tree listeners
run.on('EVENT', () => {})

// Run tree, returns a promise
run({foo: 'bar'})
  .then(() => {})
  .catch(() => {})
```

**Comment by tiagocpontesp** [comment]
+1 ofc ;), but I don't think the promise should be an emitter.

**Comment by christianalfoni** [comment]
@tiagocpontesp The promise is not an emitter, it is the function that creates the promise that is the emitter :)

**Comment by tiagocpontesp** [comment]
hehe seems i didn't delete that comment fast enough

**Comment by christianalfoni** [comment]
hehe ;-)

**Comment by maxfrigge** [comment]
@christianalfoni does this mean that function tree wouldn't cache anymore and leave it up to the developer whether to cache or not?

**Comment by christianalfoni** [comment]
@maxfrigge you mean caches the `static` representation? It still does that, what we basically do is just create an "in between" layer where the tree does not return execute directly, but rather a factory for producing a new execute function that is also an event emitter :)

**Comment by maxfrigge** [comment]
@christianalfoni ok. so it's more of a convenience thing to run multiple trees with the same environment (initial payload & providers)?

**Comment by christianalfoni** [comment]
Yes, exactly :) Basically you kinda bind a tree to an execution allowing you to listen to events for only that specific tree execution, instead of only globally like it does now.

Also returning a promise allows you to use this as middleware for example :)

**Comment by maxfrigge** [comment]
@christianalfoni just one more thing :-P  

What do you mean by "Add directly to context (ContextProvider)" for the first argument? Isn't that what context providers are for?

**Comment by maxfrigge** [comment]
As this feature would sort of legitimise running multiple trees (e.g. tree inside a tree), it would be super awesome to visualise this in the debugger as well.

**Comment by christianalfoni** [comment]
@maxfrigge Ah, yeah, sorry.. I meant the `ContextProvider`, the provider that allows you to hook things in directly, like superagent etc., making them automatically wrapped for debugging purposes :)

Not sure about the tree inside a tree though ;-) Rather "tree for auth", "tree for requests", "tree for schedules" etc ;-) But yeah... everything up for exploring!

**Comment by maxfrigge** [comment]
@christianalfoni got it. will be experimenting with tree in tree this week and let you know how it goes. I think that especially in node environments this could be quite handy.

**Comment by Guria** [comment]
I am sure it pretty solved with latest API. @christianalfoni right?
