### ISSUE TITLE
Bug in operator.set

### ISSUE THREAD

**Issue by MrLoh** [cerebral/cerebral#712]
I just encounteres a strange error while trying to simply set a string value in the state with 
`set(state`route`, '/trailer/rating')`

I was on cerebral@2.0.0-b-alpha.22884964 The error was `Uncaught TypeError: resolve.isCompute is not a function` in `set.js:19`. 

Shouldn't this be caught by a test though?

**Comment by christianalfoni** [comment]
Hi @MrLoh ,

This seems super strange. `resolve.isCompute` is there and there is also a bunch of tests using `set`.

Would it be possible to try to update back? And just do a plain signal execution when app fires up with a set? Just to see that there might be something strange with this specific scenario?

**Comment by Guria** [comment]
@MrLoh make sure you used --save-exact flag while installing deps and package.json doesn't have ~ or ^ before all cerebral entries versions

**Comment by christianalfoni** [comment]
Closing this for now as it is getting old :)
