### ISSUE TITLE
allow storing prototypeless objects in state

### ISSUE THREAD

**Issue by fmal** [cerebral/cerebral#714]
I would like to use `Object.create(null)` for storing maps/lookups in the state tree (it used to be possible in C1), but in the latest release i get the following error: "You are passing a non serializable value into the state tree". This is due to this check https://github.com/cerebral/cerebral/blob/fab0e4d1094a84d7a6a41db7d00dd6ed9aaf89bb/packages/cerebral/src/utils.js#L51 that does some extra stuff beyond simple `isObject()`. I wonder whether these checks are necessary. Objects created with `Object.create(null)` are still serializable.
@christianalfoni i would be happy to PR if this sounds sensible.

**Comment by christianalfoni** [comment]
@fmal Hi, yeah! We can definitely add more allowed types. Like **RegExp** was just added due to forms needing to store it on the validationRules.

But before we go down the path of identifying this kinds of objects... why do you use `Object.create` and not the literal? :)

**Comment by fmal** [comment]
@christianalfoni they're just better suited for lookups and dictionaries in my opinion as `Object.create(null)` doesn't inherit from anywhere. It's sort of a best practice, see http://www.2ality.com/2013/10/dict-pattern.html 😃

**Comment by christianalfoni** [comment]
Ah, I see, was not aware of that :) I guess these objects has `Object.getPrototypeOf(value)` is `null` then? Yeah, they do: http://jsbin.com/wuyawixocu/edit?js,console. So something like:

```js
if (
    value !== undefined &&
    (
      validType ||
      (
        isObject(value) &&
        Object.prototype.toString.call(value) === '[object Object]' &&
        (value.constructor === Object || !Object.getPrototypeOf(value)) // <- Here
      ) ||
      typeof value === 'number' ||
      typeof value === 'string' ||
      typeof value === 'boolean' ||
      value === null ||
      Array.isArray(value)
    )
  ) {
    return true
  }
  return false
```

**Comment by christianalfoni** [comment]
If you want to make a PR there, happy to merge it :)
