### ISSUE TITLE
Move to prettier

### ISSUE THREAD

**Issue by edgesoft** [cerebral/cerebral#732]
What are the pros and cons of moving cerebral and all other packages to prettier.

https://github.com/prettier/prettier

If no obvious cons I suggest that we move to prettier.

**Comment by christianalfoni** [comment]
I think @Guria has the strongest voice here, being the maintainer of repos :) I think prettier looks really awesome and as I understand it would be an addition to linting? Cause linters picks up stuff that prettier does not?

**Comment by henri-hulski** [comment]
I really enjoy the semicolon free approach of standard. Would really missing it. 
What's nice about prettier is that he just takes your code and normalize it. I also like that he introduces a max. line length and automatically reformat to it.

So maybe a combination of prettier and standard would be fine which keeps the semicolon free approach.

**Comment by gaspard** [comment]
@henri-hulski Prettier has a setting to not add semicolon. I think this tool is a good idea (but it needs to be tested first).

I really like consistency regarding source code and would love something like "prettier" for my own needs (http://new.lucidogen.io/jessy/)...

**Comment by henri-hulski** [comment]
@gaspard It does???

**Comment by henri-hulski** [comment]
https://github.com/prettier/prettier/issues/12

**Comment by gaspard** [comment]
@henri-hulski Oh, sorry. I got confused with the "trailing comma" option. You are right: semicolons everywhere... Back to 1960.

**Comment by sheerun** [comment]
@christianalfoni @Guria I've created https://github.com/sheerun/prettier-standard if that helps you

**Comment by edgesoft** [comment]
#923
