### ISSUE TITLE
feat(function-tree): pass payload when aborting

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral#734]
It's currently not possible to pass a payload when aborting the tree execution. 

The suggestion is `execution.abort(payload)`.

The payload will then me merged with the previous payload and passed along with the abort event.

I am currently swamped, but will create a PR a.s.a.p.

**Comment by christianalfoni** [comment]
Think it is a great idea :)

**Comment by maxfrigge** [comment]
@christianalfoni is it ok to shallow merge with `Object.assign({}, payload, result)` should outputs be deep merged?

**Comment by christianalfoni** [comment]
https://github.com/cerebral/cerebral/pull/756

**Comment by christianalfoni** [comment]
Do not need deep merge :)
