### ISSUE TITLE
Validating the state

### ISSUE THREAD

**Issue by saulshanabrook** [cerebral/cerebral#77]
In `baobab` you can [set up](https://github.com/Yomguithereal/baobab/tree/v2#options) a `validation` function that is called on every state change and can reject changes that do not pass the validation:

```javascript
function validationFunction(previousState, newState, affectedPaths) {
  // Perform validation here and return an error if
  // the tree is invalid
  if (!valid)
    return new Error('Invalid tree because of reasons.');
}

var tree = new Baobab({...}, {validate: validationFunction});
````

I actually have a [JSON schema](json-schema.org/) set up for part of my state, so this is useful to me, to easily verify whether the actions have done some invalid.

I was thinking it might make sense to include something like this in the core of cerebral. It would also open up the door to easier type checking of that state and some forced structure to it.

What if the actions that modified the state, like `state.set`, `state.merge`, could return an error if you set up a validation function?

Or maybe there would be a cerebral event called `invalid` that is emitted when an invalid state is saved.

Just putting some ideas out here would love to hear what others think about it, I might be totally wrong.

**Comment by gcanti** [comment]
Hi @saulshanabrook,

You may want to take a look at:
[cerebral-tcomb - immutable and **type checked** model layer for cerebral](https://github.com/gcanti/cerebral-tcomb)

**Comment by saulshanabrook** [comment]
From gittir chat:

> @gcanti Looks really nice. I am using JSON schema, however, so that both the backend and the frontend can validate the state and use the same schema. Do you think it would be possible to extend that to support pluggable type checking backends?

**Comment by bfitch** [comment]
@saulshanabrook Thanks for brining this up! I had the same idea of using JSON Schema to share validation logic between the client store and api endpoints. 

Maybe pass a validation function as a option to set?
```js
state.set('messages', myData, myValidationFunction);
```
or more "globally" like baobab's `validate` world be nice too.

I really like the idea of getting client validations "for free" and keeping the logic in sync.

**Comment by saulshanabrook** [comment]
What would happen if validation fails? Would it just log an error and discard the changes that caused the invalid state?

**Comment by christianalfoni** [comment]
Hi guys,

As both Baobab and tComb supports validation of state I have a gut feeling that this should belong to the model package. Are there any issues now using the internal tools of the model packages? Like Baobab and tComb?

**Comment by saulshanabrook** [comment]
It works for me so far, as is.

The main problem I see cropping up is that since the validation is supported via an invalid callback, it is impossible to know, when you are inside an action, if some `set` you did just failed.

Like let's say you are taking some input from the user and you want to throw it in the state and validate it through Baobab's validation. Inside your action chain you can't change path's or anything based on the whether the `set` failed.

But I do not have this problem at the moment, so I will close this for now. Anyway there may be a way to solve this without touching cerebral.

**Comment by bfitch** [comment]
Yeah, I agree @saulshanabrook. My ideal would be to have a validation function defined for any path you specify, and then you could also get the error message in your action when it fails. A more local solution that validating the entire tree.

**Comment by christianalfoni** [comment]
Aha, I see, hm... this is interesting. How does it work with Baobab? You have to listen to an event to know if a `set` failed due to validation?

Also a thing here is that you already have validation on the `inputs` which is the only way you can dynamically set state. So instead of failing on the setting, it fails when the action gets the input. Does that make sense?

Lets discuss more :-)

**Comment by saulshanabrook** [comment]
You pass in a function to be called for validation. If you return an error it is logged, as shown in https://github.com/christianalfoni/cerebral/issues/77#issue-102543039

**Comment by christianalfoni** [comment]
Okay, maybe we should conclude on something here.

I suggest it works fine now? You use the Baobab event to handle general validation issues and a custom validation lib to validate state as it is being set?

**Comment by saulshanabrook** [comment]
Sure, if we wanna leave whole tree validation as part of the state store, and not part of cerebral, than we don't have to change anything.

**Comment by christianalfoni** [comment]
I will close this. I think validation should be handled outside of Cerebral
