### ISSUE TITLE
tutorial: no styles loaded in final solution on windows

### ISSUE THREAD

**Issue by fopsdev** [cerebral/cerebral#771]
Just something we shouldn't forget :)
Steps to reproduce:
-Use Windows and recent NodeJS (Didn't test on other OS)
-Download the following BIN as instructed in the tutorial (http://cerebraljs.com/docs/developer_guide/organize.html)
https://www.webpackbin.com/bins/-KfDKApROapTmuhEF5_j
-> When running the solution you will see that styles.css can not be found

**Comment by fopsdev** [comment]
can't we just include styles the old school way (in index.html)?
i'm asking that also because i see quite a few words about style handling in the tutorial which imo could confuse beginners

**Comment by Guria** [comment]
Agreed. Lets simplify this.

**Comment by fopsdev** [comment]
tutorial is not using styles anymore. so its fine :)
