### ISSUE TITLE
provider-forms: add a .oldValidValue property to check for value changes

### ISSUE THREAD

**Issue by fopsdev** [cerebral/cerebral#795]
Hi Guys

This is just an idea which popped up in my head recently.
I had the use case of checking status changes of a document to enabled/disable other parts in the form.

Now ways to solve that would be to compose the existing setField into my own sequence and do a checking of the old value before setting the new.

Another way would be that this existing setField(...) factory just always backs up the current value into a .oldValidValue - field. And this should imho only be done if the value was valid

```js
function setFieldFactory (fieldPath, fieldValue) {
  function setField ({state, resolve}) {
    if (!resolve.isTag(fieldPath, 'state')) {
      throw new Error('cerebral-provider-forms operator.setField: You have to use the STATE TAG as first argument')
    }
   let oldValidValue = null
   if (isValid(fieldPath)) {
       oldValidValue = state.get(fieldPath + '.value')
   }
    state.merge(resolve.path(fieldPath), {
      value: resolve.value(fieldValue),
      oldValidValue: oldValidValue,
      isPristine: false
    })
  }

  return setField
}

export default setFieldFactory
```

That could be a beneficial addition or maybe its stupid :). Let me know what you think

**Comment by Guria** [comment]
I am pretty sceptic on it. Forms provider was revisited with idea to provide composable parts and not universal solution.
Anyway I am very curious on your use case. Can you tell a bit more?

**Comment by fopsdev** [comment]
yeah, usecase its pretty simple :) , lets say we have a:
- select with three options A,B and C
- a checkbox X
now if user selects C -> X will get disabled and value of X will be set to false
if user selects A or B -> X will be enabled and set to true but only IF before it was C

**Comment by fopsdev** [comment]
Oh yeah i'm a huge fan of stateless components in react ;)

**Comment by fopsdev** [comment]
i now solve it by getting the old value before setting the new one...
https://www.webpackbin.com/bins/-Kh1lzYmFrCFI248mXnq
think we can close this one because as @Guria said it should be composable and leave additional logic open to the dev...
