### ISSUE TITLE
Typescript support ?

### ISSUE THREAD

**Issue by Ownelek** [cerebral/cerebral#796]
Hi guys,
As far as i can see, there is no types nor DefinitelyTyped typings for cerebral.
Is it planned ?

**Comment by Guria** [comment]
We are glad to provide d.ts files, but most likeky we will need some help with it.

**Comment by Ownelek** [comment]
I can try writing them, is it ok?

**Comment by Guria** [comment]
Of course. Just make a draft PR and we will see.
