### ISSUE TITLE
Router documentation for version 2 (BETA)

### ISSUE THREAD

**Issue by klis87** [cerebral/cerebral#820]
Could you please add API documentation for Cerebral Router? I am asking, because I cannot find it in Cerebral docs (only some routing examples in tutorial). Or maybe it is documented somewhere else? Anyway, thanks for creation of this awesome package, I tried both Redux and Mobx, and Cerebral is like combination of the best parts of those two! :)

**Comment by henri-hulski** [comment]
Hi klis87!
Thanks for reporting the issue.
This is already fixed in the PR #814.
For now you can find the new router docs [here](https://github.com/cerebral/cerebral/blob/websiteUpdates/packages/cerebral-router/README.md).

**Comment by klis87** [comment]
Thank you for such a fast answer :) And now the question arises, why would anyone use React router when routing can be so simple :)

**Comment by Guria** [comment]
Because so simple routing requires a pretty opinionated setup. Btw, our router in fact does no routing. It only wires up underlying libs addressbar and url-mapper with cerebral controller. And this libs could be used for other opinionated setups.
