### ISSUE TITLE
forceSerializable does not take custom allowedTypes into account

### ISSUE THREAD

**Issue by fmal** [cerebral/cerebral#840]
I have an action factory which looks similar to this:

```js
function logFactory (level, payload) {
  return function log ({ resolve, logger }) {
    const resolvedPayload = resolve.value(payload);
    logger(level, resolvedPayload);
  }
}
```

Then somewhere else i'm triggering signal which contains my log factory and passing custom `Error` class as payload: `{ error: MyCustomError('message') }`:

```js
[
  log(LOG_LEVELS.ERROR, props`error`)
]
```

Another case: i would like to pass controller errors to my action chain and log them in one of the actions. 

```
controller.on('error', error => {
  controller.getSignal('controllerErrorThrown')({ error });
});
```

the `logger` can't properly serialize `Error` because it gets passed through `forceSerializable`: https://github.com/cerebral/cerebral/blob/9702657cd3fd61961d256b72c4325e3d567746e8/packages/cerebral/src/utils.js#L107

I tried to extend `devtools` in controller with `allowedTypes: [Error]` but that doesn't help.

**Comment by fmal** [comment]
I will workaround it by simply not passing custom error as payload in my app, but still it seems a bit of a "gotcha" that already serializable stuff get's overriden. On the other hand i see why it's necessary for the debugger 😃

**Comment by christianalfoni** [comment]
Closing this as we have `CerebralError` now
