### ISSUE TITLE
Provider simplification suggestion

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#842]
Hello to you :-)

During the BETA there has been some feedback on how providers really fit in. That providers produces what is on the context is not clear. I think this is mostly due to its nature... you define the context separate to where you use it, which is the intention of separating side effects from execution. In function-tree this is not a problem because you define the function tree by giving the providers to produce the context. In Cerebral though, you have the controller and lots of other stuff. SO!

This is how it will look:

```js
const controller = Controller({
  context: {axios, uuid},
  modules: {
    firebase Firebase({}),
    http: Http({}),
    forms: Forms({}),
    storage: Storage({}),
    useragent: Useragent({})
  }
})
```

So there are two changes here.

1. We deprecate use of `providers`. It is difficult for people to see how providers relate to the context of actions... with good reason, they are completely separated... with good reason, to separate side effects from execution :-) With function-tree it is easier, cause defining a function tree is defining the context, but Cerebral is more than that, which also means it has the freedom to make this easier

2. There are no provider packages anymore. It will just be `cerebral-firebase`, `cerebral-http` etc. (and for release `@cerebral/firebase`, `@cerebral/http` etc. That means adding "batteries" to Cerebral is creating a module. That module might use state, signals and/or define a provider

## Module code examples
So you can create a provider as simply as plain module definition:
```js
{
  state: {},
  signals: {},

  // Define provider as object will automatically cache the provider, no need to recreate it
  // on every action call
  provider: {/* provider methods */}
}
```

The only change here is that you define the provider object, instead of extending the context. The reason is that Cerebral will put that provider on the correct name, based on what name you choose for your module.

You might need more power, so this is API of advanced implementation:

```js
// You create a factory for the module to pass in some options
function MyModule (options = {}) {
  
  // You define the module with a function to get the controller
  // and the path to the module passed in
  return ({controller, path}) => {

    // You return the module definition
    return {
      // Define provider as function will make Cerebral call it for every action
      context (context) {
        return {}
      }
    }
  }
}
```

Other benefit you get here is that by default you can instantiate multiple instances of the module, cause you give those modules different names.

The big takeaway here is consistency and reduce number of concepts. Now adding separate tools is super easy and all batteries of Cerebral are modules. Also defining a provider has become a lot easier.

We can easily deprecate this stuff as well :-)

**Comment by henri-hulski** [comment]
Hmm in controller you use 
```js
  context: {axios, uuid},
```
and in the module
```js
  provider: {/* provider methods */}
```
Is this not more or less the same?
Maybe we can use `context` also in the module so that we can give up the provider concept intirely.

**Comment by Guria** [comment]
What about operators? How they will get where to find related provider?

**Comment by christianalfoni** [comment]
@Guria Yeah... this reminds me... we have been down this road before :-)

It would have been nice to clean this up, but it does not "fit in". It is not possible to make operators choose targets... at least not now.

I will just adjust docs to make things more clear rather... maybe we will find some way to handle this later
