### ISSUE TITLE
Invalid error message link

### ISSUE THREAD

**Issue by reflog** [cerebral/cerebral#855]
When devtools are not used, the following is displayed:

```
Controller.js:139 You are not using the Cerebral devtools. It is highly recommended to use it in combination with the debugger: https://cerebral.github.io/cerebral-website/install/02_debugger.html
```

That link points to a non-existing page.

**Comment by christianalfoni** [comment]
@reflog Sweet, got time for a PR? Just update the url? :) I think you can actually just go straight into Github, find the file, the line and update directly :)

**Comment by reflog** [comment]
Done. https://github.com/cerebral/cerebral/pull/856

**Comment by christianalfoni** [comment]
Thanks man! :-)

**Comment by Guria** [comment]
@christianalfoni don't close issues before fix in master please
