### ISSUE TITLE
connect has a third argument

### ISSUE THREAD

**Issue by kongdigital** [cerebral/cerebral#862]
Love the project,

I noticed it's not documented but `connect()` accepts three arguments. I found it very useful but was wondering if this will be kept in the 2.0 release? Or is it just not documented yet?

**Comment by Guria** [comment]
Must be documented. Definitely will be in release

**Comment by Guria** [comment]
PR on docs is welcomed as well

**Comment by kongdigital** [comment]
My bad it is mentioned in the API docs. I was looking at the developer guide.

**Comment by Guria** [comment]
developer guide worth to have a quick note about it with a link to api
