### ISSUE TITLE
feature to get Form error messages from the computed field

### ISSUE THREAD

**Issue by psypersky** [cerebral/cerebral#867]
It would be nice to have the same errorMessage in the computed field to not have to do something like

```js
import React from 'react'
import {connect} from 'cerebral/react'
import {field} from 'cerebral-provider-forms'
import myErrors from '../../somewhere'

export default connect({
  field: field(state`path.to.form.name`)
},
  function MyField ({field}) {
    const errorMessage = myErrors[field. failedRule];
  }
)
```

**Comment by Guria** [comment]
another option is to use overrideProps callback to extract a message: http://cerebraljs.com/docs/api/connect.html#override-props

**Comment by edgesoft** [comment]
@psypersky Since you get this when using the form compute I think this should also be available in the field compute. @christianalfoni What is you take on this?

**Comment by christianalfoni** [comment]
Housekeeping!
