### ISSUE TITLE
Deciding on package names

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#882]
Related to release we want to improve package naming in the name of consistency!

There are basically two levels of changes.

1. We will remove "type of package" from the name. So no `provider` or `module` in the name. That allows for freedom to make a provider a module and a module a provider, bumping its major version

2. We can move to a scope type of packages. From NPM docs scoped packages is a way to group related packages and give you full freedom in naming the actual package

The two comments below shows each level of change, where we most certainly will do 1.... but will need to vote on 2.

**Comment by christianalfoni** [comment]
### Remove type from name
cerebral
cerebral-forms
cerebral-useragent
cerebral-router
cerebral-firebase
cerebral-http

function-tree
function-tree-firebase-admin

**Comment by christianalfoni** [comment]
### Use scope
cerebral
@cerebral/forms
@cerebral/useragent
@cerebral/router
@cerebral/firebase
@cerebral/http

function-tree
function-tree-firebase-admin

**Comment by henri-hulski** [comment]
Why not 

@function-tree/firebase-admin

?

**Comment by Guria** [comment]
2 scopes is also a problem for "universal" packages.
I would suggest as option:
@cerebral/function-tree
@cerebral/firebase-admin

But it seems to have cons too.

**Comment by Guria** [comment]
Btw, just thought we can have a scope with another name:

@foobar/cerebral
@foobar/function-tree
@foobar/forms

But it wouldn't easy to choose a name for it.

**Comment by edgesoft** [comment]
Yes @cerebral/firebase could maybe later compete with @cerebral/firebase that is function-tree specific

**Comment by christianalfoni** [comment]
Yeah... the winning argument for first suggestion is securing naming does not crash between function-tree and cerebral. We want those to live completely separately. It seems like the safest move for where we stand today :)

**Comment by edgesoft** [comment]
So the new shortcuts is hard to name. Since shortcuts can also be a valid server side name

**Comment by Guria** [comment]
Btw, function-tree is not tieted to server. There is users of ft on clidnt side as well

**Comment by edgesoft** [comment]
@Guria Yes but the shortcuts it's tied to client. Because it uses window.

**Comment by edgesoft** [comment]
If we end up having shortcuts on the server some day, than we can come up with some name 👍

**Comment by henri-hulski** [comment]
@Guria universal packages could be published in both scopes.

**Comment by reflog** [comment]
Voted for not adding scope. Seems like a cleaner solution.

**Comment by christianalfoni** [comment]
About client/server, I do not think it needs to be reflected in naming. `function-tree` and `cerebral` can both be used on client and server. The important thing is that `function-tree-firebase` does not crash with `cerebral-firebase`. It is very clear and precise. Where the specific package is to be used is in the docs of the package.

So I want to conclude on this now, summarizing all package names for release:

cerebral
cerebral-firebase
cerebral-forms (cerebral-provider-forms)
cerebral-http
cerebral-storage
cerebral-router
cerebral-shortcuts
cerebral-useragent

function-tree
function-tree-firebase-admin

**Comment by edgesoft** [comment]
@christianalfoni You suggestion above is great!

**Comment by fopsdev** [comment]
@christianalfoni lgtm, as well i like the fact that there is no provider/module in the name giving freedom on how it will evolve
@Guria will we keep the "old" cerebral-forms as a separate release?

**Comment by Guria** [comment]
Btw, I think firebase-admin could work with cerebral as well I suppose. And seems we can just say that cerebral supports both cerebral-* and function-tree-* packages if otherwise not noted in docs.
Based on this, I will suggest `cerebral-http` -> `function-tree-http` and `cerebral-storage` -> `function-tree-storage` at least.
It would

**Comment by fopsdev** [comment]
oops...sry

**Comment by gaspard** [comment]
Sorry to chime in late to the party but I do not think all this is wise. The whole point of renaming packages is to:

1. make them simpler (=remove 'module', 'provider')
2. ensure naming power to "cerebral" for two reasons:
  a. future proof name choosing = make sure an important name for future a package is not used
  b. clarify npm module "responsability" = make it easy for users to know the package is officially supported by Cerebral team.

Having maintained open source projects for more then 10 years, I highly advocate the use of `@cerebral` namespace.

```
@cerebral/forms
@cerebral/useragent
@cerebral/router
@cerebral/firebase
@cerebral/http

@cerebral/function-tree
@cerebral/firebase-admin
```

**Comment by christianalfoni** [comment]
@Guria I disagree. Http and storage are using Cerebral specific functionality. They can trigger signals by passing in options, sync state with the state tree. They also have operators that resolves tags using Cerebral tags and computed. They are not compatible.

And I do not think people using `function-tree` will ever use a custom http provider because it does not give any extra value. Much better to use axios or something similar.

The current naming of packages work and has not created any confusion, we should stick with this now because we know it will work.

**Comment by edgesoft** [comment]
@Guria firebase-admin is for backend only. According to firebase you should not use this in a none backend. @christianalfoni Right?

**Comment by Guria** [comment]
cerebral vs function-tree is not client vs backend. As @christianalfoni said cerebral could work on server as well.

**Comment by christianalfoni** [comment]
@gaspard But this requires people only interested in function-tree to "adopt" into Cerebral world. Do not want that. function-tree should be its own thing, even if you have never heard of Cerebral. Also it will be very confusing what packages belongs to function-tree and what belongs to cerebral... they are not compatible

**Comment by henri-hulski** [comment]
@gaspard Cerebral core is missing there.

**Comment by gaspard** [comment]
@christianalfoni I do not really think people will feel like they are "adopting" into Cerebral world simply by using @cerebral in the prefix of the package.

But what you mention is a very good point and for me this implies moving function-tree related packages in another monorepo + using @function-tree as namespace.

```
cerebral
@cerebral/forms
@cerebral/useragent
@cerebral/router
@cerebral/firebase
@cerebral/http

// moved to another monorepo
function-tree
@cerebral/firebase-admin
```

**Comment by edgesoft** [comment]
@Guria but the firebase-admin should not work in frontend. But I guess this has nothing to do with naming.

**Comment by Guria** [comment]
@edgesoft server-side restriction should be just noted in docs. Notning can stop me from using firebase-admin with cerebral on server

**Comment by henri-hulski** [comment]
@gaspard You mean 

```
// moved to another monorepo
function-tree
@function-tree/firebase-admin
```
right?

**Comment by edgesoft** [comment]
@gaspard Do you mean importing stuff like @cerebral/core/operators?

**Comment by edgesoft** [comment]
@gaspard Ahh, see that you just use cerebral for core.

**Comment by henri-hulski** [comment]
I'm voting for
```
cerebral
@cerebral/router
@cerebral/forms
@cerebral/http
@cerebral/firebase
@cerebral/storage
@cerebral/useragent
@cerebral/shortcuts


// moved to another monorepo ??? not sure about this one!
function-tree
@function-tree/firebase-admin
```
This seems to makes the clearest seperation between cerebral and function-tree and as @Gaspard says is a future-proofed namespace which makes clear that the packages are approved by the cerebral / function-tree organization.

Everybody could claim a cerebral-* package, but not a @cerebral/* package.

**Comment by christianalfoni** [comment]
Peeeeeps, we are spending way too much time of this :-) I do not care about the length of package names. Nobody in their right mind will ever drop the functionality of a package because the name of it is "too long", that is just silly. But they will drop it if they do not understand where it is supposed to be used. 

The suggestion on keeping current package names, just dropping the types will:

1. Cause minor or no changes in docs, articles and repo structure
2. Cause least amount of confusion for existing users and also future users
3. It also clearly states that function-tree and Cerebral are two different projects, which they are at this point in time

I love all the feedback here, but I am about to go crazy if we do not get this release out. Moving to scopes and possibly new monorepo for function-tree will just make things take forever. The conclusion above is the least amount of effort, least confusion and most explicit.

### Least effort, most explicit... lets SHIP IT!
cerebral
cerebral-firebase
cerebral-forms (cerebral-provider-forms)
cerebral-http
cerebral-storage
cerebral-router
cerebral-shortcuts
cerebral-useragent

function-tree
function-tree-firebase-admin

**Comment by edgesoft** [comment]
Good point! We do not want to rewrite docs, articles all over.

**Comment by Guria** [comment]
@christianalfoni 

## storage
* has no cerebral dependency in [provider](https://github.com/cerebral/cerebral/blob/master/packages/cerebral-provider-storage/src/index.js#L24-L41)
* only [option.sync requires controller](https://github.com/cerebral/cerebral/blob/master/packages/cerebral-provider-storage/src/index.js#L10-L22)

option.sync could be either wrapped into conditonal to check if controller exist or moved out to micro cerebral module where it fits better then a provider.

## http
the same here. it's a provider that mostly have no cerebral dependency, except reporting progress. which also could be safely wrapped in a conditional.

Also common problem is operators. Which could be solved with exposing `resolve` in function-tree context supporting props tag.

**Comment by henri-hulski** [comment]
@christianalfoni Hmm but when removing the types we also have to rewrite docs and articles.
I think it's not a big difference.

**Comment by gaspard** [comment]
@christianalfoni the time we are taking now to clarify things is really important. It will slow us down a day at most but I think it is really worth it because it gives the whole project solid foundations for the long run.

**Comment by Guria** [comment]
I don't see rewriting docs/articles a great deal at the moment. But it would be a bigger problem when we would have another bunch of modules.
We expect to accept a lot modules after release and our decision must be scallable. Time spent is really worth it.
So I see @gaspard right about scope adding sure that package comes from / approved by official team

**Comment by edgesoft** [comment]
@henri-hulski Good point. I can help go through all the docs as well and update them. Sure there are others that would help as well.

**Comment by henri-hulski** [comment]
@christianalfoni No panic. I think this is the last important decision we have to make before release and I think it's worth to make it carefully.

**Comment by fopsdev** [comment]
I'm not of too much help here with this strategical discussion (besides closing the issue by accident :speak_no_evil:)
but i would gladly help to adjust the tutorials to whatever convention that will result out of this :)

**Comment by Guria** [comment]
Scoped suggestion:
```
cerebral
function-tree
@cerebral/firebase
@cerebral/forms
@cerebral/http
@cerebral/router
@cerebral/shortcuts
@cerebral/storage
@cerebral/useragent
@cerebral/firebase-admin
```
each scoped package defines what it supports: server/client/universal, function-tree/cerebral

**Comment by henri-hulski** [comment]
@Guria How whould you seperate two different packages with the same function for cerebral and function-tree?
E.g. cerebral-firebase and function-tree-firebase?

**Comment by edgesoft** [comment]
@function-tree/firebase
@cerebral/firebase

?

**Comment by Guria** [comment]
It would just support both and probably will have specific entry points.
eg, provider could be universal, but other parts could require cerebral like computed, specific operators or tags.

**Comment by henri-hulski** [comment]
So not a strict separation between cerebral and function-tree.

Hmm as they have much common that would at least reduce code.

But maybe the API and imports gets more complicated and not so obvious?

**Comment by Guria** [comment]
I suggest to follow general rule:
* index.js re-exports all available stuff
* one who wants bundle size optimization should use direct entry-points or corresponded babel-plugin

**Comment by christianalfoni** [comment]
Okay, so I support this change:

cerebral
function-tree
@cerebral/firebase
@cerebral/forms
@cerebral/http
@cerebral/router
@cerebral/shortcuts
@cerebral/storage
@cerebral/useragent
@cerebral/firebase-admin

so we keep function-tree stuff created by Cerebral organization behind that scope, cause in theory you can use whatever function-tree package with Cerebral

**Comment by henri-hulski** [comment]
Yeah that makes sense.

**Comment by gaspard** [comment]
@christianalfoni I think this solution is much better. If we do not absolutely need two scopes, it makes things simpler. Nice.

**Comment by christianalfoni** [comment]
It is @Guria suggestion btw, hehe... I should not take credit :-)

**Comment by christianalfoni** [comment]
Okay, I am boldly closing this issue now with the latest suggestion, removing one blocker from release:

cerebral
function-tree
@cerebral/firebase
@cerebral/forms
@cerebral/http
@cerebral/router
@cerebral/shortcuts
@cerebral/storage
@cerebral/useragent
@cerebral/firebase-admin

It is good :-)

**Comment by henri-hulski** [comment]
@Guria @christianalfoni What are the next steps?

**Comment by christianalfoni** [comment]
https://github.com/cerebral/cerebral/issues/884 :)
