### ISSUE TITLE
Release blockers

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#884]
- [x] Decide on package naming
- [ ] Create publishing routine without Lerna
- [x] Create debugger auto update
- [ ] Router (getSignalUrl missing)
- [ ] forms
- [ ] http

**Comment by gaspard** [comment]
Router is ready (once tested by Christian) :-)

**Comment by edgesoft** [comment]
@gaspard @Guria @christianalfoni @henri-hulski This is done now right. Can we close?

**Comment by henri-hulski** [comment]
> Create publishing routine without Lerna

This one is still missing.

**Comment by edgesoft** [comment]
And http is missing correct Error that need's to be thrown.

**Comment by henri-hulski** [comment]
We should add 'getSignalUrl' to the router before releasing.

**Comment by edgesoft** [comment]
@christianalfoni Can we close this?
