### ISSUE TITLE
Updating Cerebral

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#888]
Related to release we also have to decide on strategy of updating Cerebral after the release.

After a discussion with @reflog and his work on the debugger "self-update" functionality I realized that we are in a unique position to handle updates to Cerebral in a more predictable way.

The challenge with Cerebral, which we painfully experienced during alpha and beta is that packages depends on each other, also the debugger depends on specific version of Cerebral. When you update one package it might break because of a different package, the debugger does not display because Cerebral was updated, or the opposite.

I suggest we favor a strict and predictable approach to handling Cerebral updates, using the debugger as a "vessel for driving updates". This is how it would work:

1. We have prepared a new release branch containing some fixes
2. We merge the release branch into master, which triggers the publishing flow
3. Absolutely all packages, including debugger, will be updated with the same version number. Even though they did not have any updates
4. When developers fires up the debugger it will notice there is a new version of it, which we display as: "Cerebral has been updated, please follow these instructions and click here to update the debugger. Or we can remind you about this later"

"...please follow these instructions..." is a link to the website. It basically explains how you bring your current Cerebral dependencies up to date, using `npm update` and whatever.

With this approach we are in a unique position to nudge developers into having their dependencies up to date and not running incompatible versions of packages.

And a final note. Cerebral will pass its current version to the debugger when connecting, meaning that debugger can match that with its own version, giving a warning that the connected Cerebral app is "out of date" and debugger functionality can not be guaranteed.

**Comment by gaspard** [comment]
Ohhh, no... This is all wrong. We have semver for API changes and this should be respected at each package level, including debugger. Now let's say you are working on three projects:

- project Foo uses Cerebral 2.1
- project Bar uses Cerebral 2.3
- project Baz uses Cerebral 3.1

For some reasons, projects Foo and Bar cannot be migrated to Cerebral 3.x because some dependent package relies on Cerebral 2.x and cannot be changed for the moment. We still want our debugger to work with each of these projects. Here are 3 ways to handle this:

**A. Multi-core debugger**

The debugger to "adapt" to each version, this means loading different engines depending on what the app announces (but it requires total separation between tabs).

**B. Multi-api debugger**

If using multiple engines is a mess, then another solution in such a case is "API Duck typing": 

* The app sends an initial header with what it supports.
* The debugger adapts to these supported features.

**C. Stable and future-proof debugger API**

In this case, we take some time to create a stable Spec for the API between app and debugger and arrange for it to be future-proof so that there is no sync issue in the future. This solution could support some kind of api header to fallback to "Multi-api debugger" if we cannot manage compatibility.

Obviously, I prefer "C" as it allows the creation of other "debugger" apps (like an in-browser debugger, or some monitoring app, etc). This also allows project to evolve without creating an artificial coupling.

I understand that the coupling was necessary during the exploration phase we have gone through but I think the project has now enough maturity to allow for a proper app-debugger API design.

**Comment by christianalfoni** [comment]
I agree with your concerns @gaspard , but this is not only related to debugger. The problem we have spent tons of time with, and has been super confusing to developers, is that you never know if your current packages fits with the current version. Where would you get an overview of this? We would have to have this insane graph like thing on the website stating:

cerebral-router@2.3.0 supports between cerebral@2.0.0 and cerebral@2.1.0
cerebral-router@2.4.0 supports between cerebral@2.2.0 and cerebral@2.4.0
cerebral-useragent@3.0.0 supports between cerebral@2.1.0 and cerebral@2.1.0

If we run with the same version you will never ask this question and we do not have to answer a bunch of support questions and maintain an overview of what versions matches other versions.

And I thought this was one of the big advantages of having a monorepo? The packages are kept in sync to ensure that when packages are installed with same version they will always work? Just like `react` and `react-dom`, always in sync?

**Comment by bdjnk** [comment]
A mostly-semantic partly-synced versioning system could meet both desires. So long as incompatible API changes are only made in major versions, as semantic versioning demands, only major version number must be kept in sync. So 3.x.x of any package only works with 3.x.x of any other package. This is also basically gaspard's stable API, with major version cutoffs.

**Comment by henri-hulski** [comment]
But what if you make a breaking change let's say in firebase. Then all packages have jump to next major version, right?

**Comment by Guria** [comment]
@christianalfoni We already discussed a problem with a major changes in modules. You will have to bump major version of all packages even only one particular (useragent, shortcuts, firebase) requires a breaking change. Or we will have to delay breaking changes on modules until new cerebral major is ready. Both options doesn't sounds good for me. And in fact it's a disadvantage brought by monorepo. At the moment we are using [independent mode](https://github.com/lerna/lerna#independent-mode---independent) in lerna.

**Comment by Guria** [comment]
@christianalfon @reflog To solve debugger issues I would suggest:
* move out debugger from monorepo to separate repo. It already doesn't have "internal" cross-linking dependencies and relies only on published packages from npm. So there is no advantages to keep it in main repo.
* have a semver for a debugger protocol and strictly follow it.
* have separate debugger bulds for each major debugger protocol version. Track updates only for current protocol version only.

**Comment by christianalfoni** [comment]
Hm, so to summarize:

1. We want to publish packages independently
2. We do not want developers to be confused by what package versions belongs to what version of Cerebral
3. We want developers to be notified about new updates by the Debugger to encourage running on latest versions
4. We want developers to have multiple versions of Cerebral, that is not necessarily compatible with the same version of the debugger... but running in the same debugger experience

This is a tough order :)

### Individual version bumping
This has the benefit of fixes related to one package does not affect the versions of other packages, meaning developers will not need to unnecessarily update all packages if just one package had a breaking change. The problem though is that package versions will most likely not make sense as a whole, making it harder to do support and as a developer understand what versions of packages correlate to your Cerebral version.

### Major version bumping
This has the benefit of being explicit about what versions of related packages fits with your current Cerebral version. 2.x.x packages fits with 2.x.x Cerebral. The problem though is that if one package has a breaking change, all packages, including Cerebral will need a major bump.

### Notifying updates from debugger
The benefit of this is helping developers work on latest versions. Personally I have never been able to keep up with versions... not written `npm update` once in my life. With "major version" bumping we would be able to notify about breaking changes to any package, including Cerebral itself. With "individual version" we can only notify update to the debugger itself.

### Handling multiple Cerebral version in same debugger
So this one is very difficult to handle. We did handle this in Cerebral 1 debugger, but we only handled one app at a time. Now we handle multiple apps, meaning that we can not reload the entire debugger when some Cerebral app connects that requires a different version.

The fact that the debugger is used by function-tree in isolation as well does not make things easier. Because some functionality is Cerebral specific, while other is function-tree specific.

### My reasoning
I am just pushing hard on the developer experience and I do not think "independent mode" makes Cerebral a better developer experience. It makes it harder to do support and understand how packages relate to each other for the users. I totally see that bumping major on a related package causing bump on Cerebral itself and debugger is unnecessary from a technical standpoint, but from a developer experience standpoint I think it makes a lot of sense. Because we drive updates from debugger that way and major numbers always fit.

The debugger has a general API for sending and receiving messages now. Making changes to these messages and the UI of the debugger can be handled with feature checking, rather than lazy loading complete instances of the debugger. Basically what I means is:

Cerebral sends its version to debugger. The debugger evaluates what features are available for that version and activates components. We could state the version number on TAB and you would know also there what version all the other packages should be.

I understand the argument of independent mode, but I do not see the gain in developer experience? Or is there something I am missing here? :)

**Comment by christianalfoni** [comment]
@Guria Did not see your answer before now :) Moving debugger out to own repo is also a way to go, though do you mean devs with different protocol versions, due to older Cerebral apps, should install multiple debugger apps?

**Comment by Guria** [comment]
Yeah. I think it could be a fair tradeoff between our efforts an developer experience. Though I haven't yet read your comment.

**Comment by Guria** [comment]
So let me know what you think about my suggestion and I will try to summarize my suggestions with reasoning too.

**Comment by christianalfoni** [comment]
Yeah, I could support moving out debugger to own repo :-) Though with following suggestions:

- We implement feature checking in debugger based on version passed in by Cerebral. This will allow us to make breaking changes in Cerebral (Like changing messages passed to debugger) using the same debugger for older versions
- We can bump major on debugger, creating a new build, if we need to change the protocol (Which I think is unlikely in the foreseeable future as it is very generic now)... but good to have backup plan!
- We use my fallback "self updater" implementation to check for new versions of Cerebral itself, give a notification about that as well in the debugger
- Ideally we should have some "system" in place, other than peer dependency, to make it easier for developers and us supporting them, what version of related packages fits with their selected Cerebral version. Something like all packages passes their peer dependency entry to the Cerebral instance in development where it shows a warning about not matching dependency ... or something similar

**Comment by gaspard** [comment]
So my own summary:

A. We try as hard as possible to have a debugger API stable so that core and debugger can evolve without coupling. Maybe we should create a package to describe this API and have semver on it.

B. To ease user experience, we can use peerDependencies.

C. We manage releases so that all latest @cerebral packages always work together = in doubt, upgrade all.

But if we do not go crazy with breaking API changes, people will simply install the latest of everything and this should always work.

**Comment by christianalfoni** [comment]
Okay, so to try out a conclusion summary here :-)

**This is required for release:**

1. Merge in "self update" feature to debugger (@reflog has done really amazing work here)
2. Implement Cerebral and Function-Tree sending their version numbers to the debugger
3. Move debugger to own repo

**After release:**

1. Debugger protocol is really just websocket messages with these props, as example: `{version: '1.0.0', source: 'c', type: 'execution', data: {}}` This is unlikely to change, but if it does a completely new build of debugger will be required

2. Changes to messages sent from Cerebral/FT to debugger all contain version, meaning that we can feature check when necessary inside Debugger, making it backwards compatible

3. We depend on NPM/Yarn peerDependency information, but if developers starts getting into trouble or we have problems giving support, we need to take some measures. I might be colored by our experiences running alpha, cause NPM had a hard time understanding the versions there

4. At any time the latest set of packages should be compatible with each other

5. To help moving people to latest version of Cerebral we can use current fallback update implementation to rather check Cerebral for new version and give a "Hey, did you know Cerebral has been updated?" type of thing

**Comment by gaspard** [comment]
Yes, this is good. Experience with alpha was hard but as things settle down it will be easier.

**Comment by abalmos** [comment]
Hey everyone, it has been quite while since I have contributed. Cerebral Beta looks great and I look forward to using it again soon.

Now to this issue (which seems to be a reoccurring problem)

1. I agree with just moving the debugger out. It is a nice self contained project thay has a strong data contract with Cerebral but no code contract.

2. Why not just package the addons with the `cerebral` node module?  Then there are no concerns about which version of this goes with what version of that. The only thing a developer needs to worry about is what version of cerebral as a whole they are using. Webpack and the like will drop any addons not used when making the bundle. 

From what I can tell this simplifies the release cycle, the developer overhead, and the projects code structure. I also don't, at least immediately, see any disadvantages (although I am sure there are some :) ). Under the new plan above, the addon node modules are already strongly connected to Cerebral's (to the point of making new releases that don't even have code change). 

Food for thought at least?

**Comment by henri-hulski** [comment]
@abalmos For our recent concept for publishing take a look at #989.

**Comment by abalmos** [comment]
@henri-hulski thank you for the link.

I believe that the concept only further confirms that addons should be part of the `cerebral` node module. The publishing rules bump versions of addons when there are related changes (could be a change in Cerebral that effects the semantic guarantees of the addon but does not actually change the addon code, and so the addon is in fact compatible with older versions of Cerebral still). My understanding is that the rule is mainly for developer convenience, that is, it offers a clear way to decide what addons have to update to upgrade Cerebral. However, that is still a two-step process for the developer. They have to check both Cerebral for overall compatibility with their app as well as other unrelated changes made directly on the add-on.

If the addons shipped as part of Cerebral under one version number the process of upgrading is one step regardless if the change was on Cerebral or the addon. That is, one just needs to check Cerebral's change log for relevant changes. If those changes are compatible then they can upgrade Cerebral and have the newest version of everything else in one shot. As a result, no one ever has to worry about version compatibility between Cerebral and addons (at least for official addons).

**Comment by christianalfoni** [comment]
@abalmos I can totally see how this would simplify everything. The problem though is that it is very likely that after release the addons will have a lot more updates than the core. Also we are very likely to add more addons. This would mean that people using just a few, or even just core of Cerebral, would very often get new versions, breaking and major, where there really is no breaking or major to the core itself. I think it would be very confusing :-)

In the `repo-cooker` thingy we are building now the versioning will be correct, where packages related to each other are bumped when they affect each other etc.

Personally I would go with your idea in a heartbeat, cause I am super tired of having the release itself as a blocker for release ;-) But at the same time we are building a tool now that should be super useful for other projects and versioning will be what people would expect.
