### ISSUE TITLE
Improve website documentation navigation

### ISSUE THREAD

**Issue by gaspard** [cerebral/cerebral#897]
I think we need a discussion on documentation organisation for the website. For me, the way things are currently laid out is very confusing and I have an incredibly hard time finding stuff.

The most important aspect of a good documentation is to divide things in as few as possible "conceptual" chunks. Above 4 or 5, everyone gets lost. It's easy to think "ah OK, this thing is about state, view and mutations", it is much harder if you have "State, Components, Signals, Action, Operators, Factories, Paths, Compute, Routing, etc".

So here is a proposition that everyone is welcome to edit and alter.

## Conceptual structure

```
+ cerebral documentation (single entry at the top)
  + [themes] (getting started, state, view, mutations) <=== not more the 4 or 5 entries here !!
    - starts with written presentation (no deep detail, not exhaustive api)
    - api for each element in them (Signal, Action, operators for "mutations" for example).
      this means that if I go to "state", I should find everything, not missing information on state paths, etc
    - themes are presented trying to avoid introducing too many concepts at a time = simplest things first
  + guide
    + chapter
      - should have next and previous buttons
      - should have links to precise docs in [themes]
  + other packages (≠ cerebral)
```

## Actual structure

(work in progress: edited from feedback)

```
+ Guide
  + Get started <====== Can go here
  + Setup and tooling
    - install
    - we see how to setup controller without too many details
    - short intro du developer tools
    - present controller, modules
  + State and mutations
    - we present what the state is and what a state path is
    - we present how mutations are handled, introducing operators
    - Signal, Action, operators, providers
  + Views
    - we present how views depend on state and how they update
    - connect, tags
+ API
  - single page with elements organised with chapters similar to "guide"
  + packages <===== Can go here
```

**Comment by henri-hulski** [comment]
I think to have a separate API section with an entry for each concept like controller, signals, actions, operators, tags,  computed erc is good to have a reference for the exact API.

**Comment by gaspard** [comment]
@henri-hulski I think we should avoid having documentation for one thing it two places. For what you want, we should create a searchable index and point it to the corresponding entries in the documentation.

And I think for the api entries, we should use some specific CSS like [devloper.mozilla.org docs](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify). It makes 'api' style docs really easy to read.

**Comment by christianalfoni** [comment]
In my opinion documentation should be two things:

1. New to the concept (Conceptual with examples combining concepts)
2. Lookup for existing developers (Technical with isolated examples)

This is what we have been improving for every iteration, where the current concept now is:

1. New to the concept -> Get started
2. Lookup for existing developers -> API

Even though I agree that website can always be better, I do not think we should change structure yet again. The reason is:

1. Our website rocks. Look at Redux page, Mobx, Cycle JS... our website is way better than those and people are still super happy with Redux, Mobx and Cycle JS
2. We have been down the path of structuring by concept with API intertwined before, people did not like it
3. This is the only version where we have not gotten complaints, even though number of users has increased... until now ;-)

That said, I do think "Get started" is introducing things too fast etc... but that is my fault. I really should not write those docs, I know it too well :)

So in my opinion I think structure is really good. We should rather focus on improving content and writing articles that explains "bigger concepts". Like routing, forms, firebase etc. More important I think.

**Comment by christianalfoni** [comment]
But sorry, do not mean to be discouraging... I just feel website is way passed "good enough" and making it even better now requires an insane amount of effort :-)

**Comment by psypersky** [comment]
I actually like a lot how is structured
Get started -> For new guys
Developer guide -> My first App and examples of stuff
Api -> Regular reference

I think we could make the API better and with more examples, but i like it now, i normally just use API and packages tabs

**Comment by henri-hulski** [comment]
I like it also! 😊

**Comment by gaspard** [comment]
I'm sorry guys. I disagree. I was trying to find out how state paths work for `score.**`. This is what I found:

1. Could not find the information I was looking for (missing docs can happen, not that bad)
2. Did not know if I had looked correctly (=very bad: no clue if docs are missing or if I'm just dumb)

Solving (2) is very important.

I have the luck of not having looked at the website for nearly 6 months and my fresh eyes on this are completely lost.

OK for two top-levels but not more: "guide" and "api" (like Vue.js does, not 5 like we do now). People are free to organise the "guide" as they wish but it's totally confusing how it is now.

And then api should have **no sub-menu** !! We don't care here if we have to scroll, on the contrary: we want to see it all and be able to use the page search to find things. I'm a super fan of how Vue presents the api: https://vuejs.org/v2/api.

**Comment by psypersky** [comment]
Now that you put it that way I guess
"getStared", and "Developer guide" and "migration" could fit into "Guide"
and "API" and "Packages" into "Documentation"

**Comment by gaspard** [comment]
@psypersky yes.

PS: sorry for the tone, I'm just tired from lots of work, nothing to do with what is said here.

**Comment by psypersky** [comment]
Hahaha don't worry 😉

**Comment by christianalfoni** [comment]
@gaspard @psypersky Hehe ;-)

I agree that current main sections are not explicit about "your experience as a developer", but if we do a simple change:

"Get started"
"Beginners guide"
"API"
"Packages"

There is no confusion what and who these sections are for, imo. Doing this tiny change and focusing on the missing content I believe gives most value right now :-)

Vue2 API guide is really awesome, but it is a super mature framework with a guy working 100% on it, it SHOULD be better than ours... at least for now :-)

Happy to see improvement on API docs though!

**Comment by gaspard** [comment]
@christianalfoni I really think "Get started" should go into "Guide" (we can drop the beginner, some very senior people may go through a guide). As for "packages", this looks like "api" and is confusing. As a newcomer, I have no clue if "router" is in "packages" or "api". So I think "packages" should be in "api" this way you look at current entries and scroll until you stumble on "router" inside packages for example.

I'm not comparing Cerebral to Vue.js, just stealing as many good ideas from them as possible. As Picasso might have said:

"Good artists borrow, great artists steal"

**Comment by christianalfoni** [comment]
Hehe, good point :)

Yeah, I see packages really is API. Though do you mean having `cerebral` and current content of API under that, or just list packages at the bottom of current API?

I think also a confusion is having "guide and API", like the idea of current "Developer guide" is: "The first time you go to the site and dive into Cerebral". If we call it "Developer guide" or just "Guide", you would be tempted to look there later... which I think was one of your frustrations?

What about this, summarized:

- Introduction
  - The architecture
  - Install
  - Choosing a view type
  - Debugger
  - ... the rest in "Developer guide"
- API
  - Cerebral
    - What is now in API
  - ... rest of what is in "packages"
- Resources
  - In detail articles
  - Projects
  - Videos
  - Example 1
  - Example 2

?

**Comment by christianalfoni** [comment]
@gaspard You feel that would be a good next iteration, taking care of some painpoints? It is a quick fix :)

**Comment by christianalfoni** [comment]
Hm, I am seeing some issues with putting packages under API... they have more content than just their API. They have install instructions and a description as well. Does not really fit.

I have added a PR for updates to the docs. It is definitely an iteration in the right direction, imo :-)

https://github.com/cerebral/cerebral/pull/899

**Comment by hipertracker** [comment]
I was thinking about something like that:

Home page

1st Page should contain very little, high level information. Similar to Inferno/Vue home pages. Just a title, a short, catchy motto sentence, and a small dashboard with list of few main features

title: Cerebral v.2.0 
motto, eg: Simple declarative solution for very complex React state management (or something like that) 

Main features

* Simple ...
* Declarative ... 
* Predictable ... (no magic comparing to Mobx, less verbose comparing to Redux, pipelined actions etc)
* Consistent... (one design for sync and async logic
* Modular ... (UI components decoupled from the UI state, etc)
* Powerful Isomorphic Debugger ... (standalone, for every browser, the best)
* UI agnostic (React, Inferno)

Main links (like Vue and Inferno home pages)

	[ Get started  | Github ]


Differences from Mobx [shortly in points]
Differences from Redux [shortly in points]
Differences from Vue [shortly in points]
More: link to: http://www.christianalfoni.com/articles/2017_03_19_Cerebral-2

Used by: x, y, z

end of the Home page

-------------------------

"About" page, menu: [ Home | About (current)| Docs | Community]

* About
  - Objective
  - Why Cerebral?
  - History
  etc

-------------------------

"Get started" page, menu: [ Home | About | Docs (current) | Community ]

* Installation

* Architecture [about design, code organization, it should also contain some charts)
  - State
  - Debugger
  - Components [ React, Inferno, connect]
  - Modules
  - Signals [function tree, not an event]
  - Actions
  - Factories
  - Providers

* Debugger
  - on the client
  - on the server

* API
  - Cerebral
  - Cerebral-router
  providers
  - Cerebral-provider-http
  - Cerebral-provider-storage
  - Cerebral-provider-forms
  - Cerebral-provider-firebase
  modules
    Cerebral-module-useragent
    Cerebral-module-useragent
  - Function-tree

* Migration from Cerebral 1

* Examples

* Who is using Cerebral?

* Resources

-------------------------

"Community page"

* Twitter
* Discord channel
* Github
* Contributors

**Comment by christianalfoni** [comment]
@hipertracker Hi and thanks for writing up your thoughts :-)

I really like this structure, though we are lacking the resources to make the design real and also right now people are starting to burn out a bit getting Cerebral released.

I think we should keep this as a reference for when we ever get a hold of a webdesigner and we have built up some new energy after release to put efforts into restructuring and writing more docs :)
