### ISSUE TITLE
I can't get the tutorial to work

### ISSUE THREAD

**Issue by dennisbrandenberger** [cerebral/cerebral#901]
So load a BIN on Webpackbin. Then I see the project on webpackbin.com.
I then start the Cerebral debugger, click "ADD TUTORIAL" and select "STATE-TREE".
Finally I add the initial state to the controller (in the Webpackbin editor) and klikk save.

Then: Nothing happens: No update in the STATE-TREE Pane.

How is the communication between the app and debugger supposed to happen ?

Am I missing something ?

**Comment by fopsdev** [comment]
@Kjetil#9485 which chapter are you refering to? is the first one? then move on to the next and it will work :wink:

**Comment by edgesoft** [comment]
@dennisbrandenberger Could you post the bin url here that you've edited?

**Comment by edgesoft** [comment]
Closing this for now. @dennisbrandenberger reopen if it still is an issue.
