### ISSUE TITLE
@cerebral/forms@next package not installing

### ISSUE THREAD

**Issue by kongdigital** [cerebral/cerebral#903]
Hey guys,

I just tried to install forms module and it keeps failing to find a valid target:
```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/opt/nvm/versions/node/v6.9.4/bin/node" "/usr/local/opt/nvm/versions/node/v6.9.4/bin/npm" "install" "@cerebral/forms@next" "--save" "--save-exact"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: @cerebral/forms@next
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.0-beta.2, 0.0.0-beta.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gusdsnail/npm-debug.log
```

**Comment by kongdigital** [comment]
I'm guessing it's related to https://github.com/cerebral/cerebral/pull/902

**Comment by henri-hulski** [comment]
Yeah everything moving atm. 
Try `npm i @cerebral/forms --save`. 
I think @next is wrong here. 
If not the old way should still work. 
`npm install cerebral-provider-forms --save --save-exaxt` if I remember well. 

@Guria should know more details.

**Comment by Guria** [comment]
Yes, sorry. We are just in process of updating of publishing.
All scoped packages were published under latest tag which can be ommited and aliased with beta tag as well.
--save-exact flag is not neccessary anymore

**Comment by Guria** [comment]
I will alias with next tag as well to avoid confusion until website updated.
