### ISSUE TITLE
[cerebral/firebase-provider] How to Query? (startAt, endAt, limit)

### ISSUE THREAD

**Issue by magisters-org** [cerebral/cerebral#909]
Hello! First of all, thank you for awesome tool!
I have some questions about firebase provider package. How to create Queries and filter or limiting them?
Thank You!

**Comment by edgesoft** [comment]
@magisters-org Do you mean like this?

```js
function someAction({ firebase }) {
  firebase.onChildAdded('posts', 'posts.postAdded', {
    payload: {}, // Merged with the payload passed on new data
    limitToFirst: 5, // Read Firebase docs
    limitToLast: 5, // Read Firebase docs
    startAt: 5, // Read Firebase docs
    endAt: 5, // Read Firebase docs
    equalTo: 5, // Read Firebase docs
    orderByChild: 'count', // Read Firebase docs
    orderByKey: true, // Read Firebase docs
    orderByValue: true // Read Firebase docs
  });
}
```

**Comment by edgesoft** [comment]
Or do you mean on  another function for firebase?

**Comment by magisters-org** [comment]
Seems like what i needed, thx! But why in onChildAdded event, or i can use this options with function like value('posts',... etc)? Docs says i can't.

**Comment by edgesoft** [comment]
@magisters-org Yeah you are right. The docs should be updated but I believe you can pass in options to value as well.

**Comment by magisters-org** [comment]
Okey! Thanks a lot, i'l keep trying :)

**Comment by edgesoft** [comment]
@magisters-org I will have a go and look into this.

**Comment by edgesoft** [comment]
@magisters-org Here is a working example
https://www.webpackbin.com/bins/-KkkI94Tk1DiSiGDoW71

**Comment by magisters-org** [comment]
Thanks a lot one more time :). You doing great job!
