### ISSUE TITLE
Docs: Duplication on firebase addon page

### ISSUE THREAD

**Issue by k15a** [cerebral/cerebral#913]
It looks like this has something to do with how the markdown files are rendered.

http://cerebraljs.com/docs/addons/firebase.html

![bildschirmfoto 2017-05-23 um 10 53 13](https://cloud.githubusercontent.com/assets/20357450/26346342/280abfbc-3fa6-11e7-99b6-5a961b362e03.jpg)

**Comment by edgesoft** [comment]
@k15a Thanks for reporting! Do you want to fix this? Just hit edit on github. If you don't find the time just shout out and we will fix this.

**Comment by k15a** [comment]
Yeah, I tried that but it is not the problem. It seems to me that this is an issue with the markdown rendering. I will take a look if I can fix it.

**Comment by edgesoft** [comment]
CC: @christianalfoni

**Comment by edgesoft** [comment]
@k15a Thanks for reporting. Updating to latest marksy will fix the issue.

**Comment by christianalfoni** [comment]
https://github.com/cerebral/cerebral/pull/915

**Comment by edgesoft** [comment]
We can close this when next release is done and we can verify
