### ISSUE TITLE
website: expose all demos on website

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#918]
we have cool demos and 2 of them even published, but have no links to them for now

**Comment by christianalfoni** [comment]
I suggest the todomvc should be moved to codesandbox.io. If anyone wants to create it, please do!

**Comment by Guria** [comment]
Codesandbox is able to sync with github repo.
We could keep todomvc in monorepo and just publish to separte repo on release just like we do with gh-pages.
We can also use new jest support on codesandbox.

**Comment by christianalfoni** [comment]
It would work, but I have a feeling this will stop as it is too complicated for contributors :) We should get it on codesandbox first I think

**Comment by christianalfoni** [comment]
Okay, closing this as TodoMVC is now on Codesandbox. Will add fluent there after release as well. Please create a new issue with a suggested approach to the syncing stuff so we can get a PR on it... if you still feel it is necessary :)
