### ISSUE TITLE
Address issue found in packages/website/builder/builder/utils.js [Opened by bitHound]

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#935]
bitHound discovered 1 DuplicateFunction in [packages/website/builder/builder/utils.js](https://github.com/cerebral/cerebral/blob/f14fb89e605e8c8e13048c18e1e4672e4730f0cb/packages/website/builder/builder/utils.js). For details go to [bitHound](https://www.bithound.io/github/cerebral/cerebral/blob/f14fb89e605e8c8e13048c18e1e4672e4730f0cb/packages/website/builder/builder/utils.js).

**Comment by christianalfoni** [comment]
Guess not an issue?
