### ISSUE TITLE
How to integrate CerebralJS with Svelte ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [cerebral/cerebral#954]
Recently, I dabbled with CerebralJS and thinking to integrate it with Svelte. CerebralJS doesn't have any documentation of how we can integrate with Svelte ? or maybe a doc for integrating it with plain Javascript .

**Comment by yusufsafak** [comment]
I think, it is similar to vue integration. At the moment, you can check https://github.com/cerebral/cerebral/tree/master/packages/node_modules/cerebral/src/views/vue and also other view layers integration https://github.com/cerebral/cerebral/tree/master/packages/node_modules/cerebral/src/views

**Comment by piyushchauhan2011** [comment]
Cool @yusufsafak will try the above

**Comment by edgesoft** [comment]
@piyushchauhan2011 Can we close this? Did you have any luck in trying out Svelte?

**Comment by piyushchauhan2011** [comment]
Hi @edgesoft  Currently I think Cerebral doesn't SSR hence probably is not working with Svelte or Nuxt.js ( Vue + SSR + PWA ) . Might give it a try later. You can close this as I haven't spend much time on this probably won't be as should be okay after server side rendering is merged in Cerebral

**Comment by edgesoft** [comment]
@piyushchauhan2011 Cerebral does do SSR.

**Comment by edgesoft** [comment]
```js
import { renderToString } from 'react-dom/server'
import React from 'react'
import App from '../../../app/App'
import { Container } from 'cerebral/react'
import { UniversalController } from 'cerebral'
import GraphQLProvider from '../../tasks/providers/GraphQLProvider'
import bootstrap from '../../../app/modules/App/chains/bootstrap'

const serve = (req, res) => {
  const jsFiles = req.javascriptFiles.reduce((acc, file) => {
    acc += `<script src="${file}"></script>\n`
    return acc
  }, '')

  const context = {
    user: req.user
  }

  const controller = new UniversalController({
    state: {
      node: {
        nodes: {}
      },
      app: {
        user: {},
        client: {}
      }
    },
    signals: {
      test: {}
    },
    providers: [GraphQLProvider(context)]
  })

  return controller
    .run(bootstrap, {
      user: req.user
    })
    .then(() => {
      const application = renderToString(
        <Container controller={controller}><App /></Container>
      )
      res.send(
        `<!DOCTYPE html>
         <html>
           <head>
             <meta charset="UTF-8">
             <title>${req.user.currentClient.name}</title>
             ${controller.getScript()}
           </head>
           <body>
             <div id="root">${application}</div>
             ${jsFiles}
           </body>
         </html>`
      )
    })
}

module.exports = serve
```

**Comment by piyushchauhan2011** [comment]
Hi @edgesoft I'll try the above, 💯  didn't realise the above. Cheers for the example
