### ISSUE TITLE
[cerebral/firebase-provider] signInWithCustomToken is not a function

### ISSUE THREAD

**Issue by magisters-org** [cerebral/cerebral#961]
Hi, devs! I need to use signInWithCustomToken function on firebase provider, but i can't :(.

**Comment by christianalfoni** [comment]
@magisters-org Yeah, this has not been implemented. Do you want to create a PR for it? If not I can make a quick fix... just trying to recruit some Firebase people ;-)

**Comment by magisters-org** [comment]
I would be happy to help, but I do not have enough skills for this yet :-(.

**Comment by christianalfoni** [comment]
No worries, fixing it now :)

**Comment by christianalfoni** [comment]
Hi man! Quick question:

After signing in with custom token successfully, what do you expect to happen? You just want to move on or should it resolve with the user? For example `signInWithEmailAndPassword` actually resolves with the user by checking `authchange` after successful login... can do the same with token, if it makes sense?

**Comment by magisters-org** [comment]
Yes, it makes sense to check authchange for debuging custom tokens, developers can have some troubles with generating custom tokens.

**Comment by christianalfoni** [comment]
https://github.com/cerebral/cerebral/pull/977
