### ISSUE TITLE
[cerebral/firebase-provider] Something wrong with orderByChild in firebase.value()

### ISSUE THREAD

**Issue by magisters-org** [cerebral/cerebral#964]
Hi, friends! I have some problem with using orderByChild option in firebase.value(). If you use it or not results are the same, order has no changes. Why? I trying to order by 'dateStart' with value() from `tasks.${uid}`, but order dose not change... help me pls.
```
{
  "tasks" : {
    "sEpHecL847R9GNGTA1wjGwX69mr1" : {
      "-KmUEua881J4vCfM5G-2" : {
        "complete" : false,
        "dateStart" : 2,
        "taskText" : "11111111111111111111"
      },
      "-KmUEwZNSWH2pPXhV8kG" : {
        "complete" : false,
        "dateStart" : 1,
        "taskText" : "222222222222222222222"
      }
    }
  }
}
```
PS.
in console i got warning when using limitToLast: Using an unspecified index. Consider adding ".indexOn": "dateStart" at /tasks/sEpHecL847R9GNGTA1wjGwX69mr1 to your security rules for better performance 
It's normal, but order does not change. I just want to order of items with my key 'dateStart', so simple action, but so many troubles :\.
PPS.
onValue() have the same problem, or i use this feature wrong.

**Comment by christianalfoni** [comment]
@magisters-org Hi there! Sorry about late response here, but could you give example of the code itself? It should be:

```js
.value(`tasks.${uid}`, {
  orderByChild: 'dateStart'
})
```

It does not work?

**Comment by magisters-org** [comment]
@christianalfoni The problem itself is how to javascript sorts keys of result object. For example:
```
.value(`tasks.${uid}`, {
  ...
})
```
... this code return data (example):
```
{
  we2Aye2yGfe: {...},
  ooprpewr231ugh: {...},
  ... (items)
}
```
In this case any type of sorting will be ignored by JS, keys have another sorting rules, which replace your sorting. I hope you understand what i mean.
How Firebase solve this in latest version: 
```
db.ref(`tasks/${uid}`)
      .orderByChild('dateStartDesc')
      .once(
            'value',
            (snapshot) => {
                //Here is magic for sorting
                snapshot.forEach(
                    (child) => {
                        //here we have loop with right sorting
                        tasks.push(child.val());
                        console.log(child.key);
                    }
                );

                state.set('tasks.data', tasks);
            }
      );
```
Thanks for your time.

**Comment by christianalfoni** [comment]
@magisters-org Oh, this is great info :) Hm... though what would one expect like:

```js
value(`tasks/${uid}`) // Should this be an array? or object?
value(`tasks/${uid}`, {
  orderByChild: 'datetime'
}) // Should this be an array because you used "orderBychild"?
```

I would suggest the latter. Using sorting options will return an array.

**Comment by magisters-org** [comment]
@christianalfoni If we can use sorting with objects, we must use arrays (maybe inject keys in items). Without sorting we can use object, but from another side, for better predictability i advice use arrays and inject firebase item keys somehow.

**Comment by christianalfoni** [comment]
@magisters-org Yeah... you know, for backwards compatability we should probably rather add an option here:

```js
value(`tasks/${uid}`, {
  asArray: true,
  orderByChild: 'datetime'
})

/*
  Value would now be:
  [{
    key: '',
    value: {}
  }, {
    key: '',
    value: {}
  }]
*/
```

You feel okay on that? :-)

**Comment by magisters-org** [comment]
I completely agree with you :-).

**Comment by christianalfoni** [comment]
Great! I will get this in later this evening :)

**Comment by christianalfoni** [comment]
https://github.com/cerebral/cerebral/pull/976
