### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#971]
My point of view on release process:
* We should have 3 main branches:
  * **master** - "production" branch. Automatically released as `@latest` to npm
  * **next** - "pre-master" branch to batch changes before getting into release. Automatically released as `@next` to npm
  * **canary** - "experimental" branch to battle test experiments. Automatically released as `@canary` to npm
* all npm releases under `@latest` tag should be represented as github-release with appropriate changelog
* PRs by default should point to **next** branch
* **next** branch accepts only ready features / fixes. no WIP or experimental
* **next** and **canary** branches allowed to be rebased
* Ideally no one package.json should contain current package version, like it was with [semantic-release setup](https://github.com/cerebral/cerebral/blob/v1/package.json#L3)
* Once **next** branch is ready it should be rebased into **master** which triggers CI workflow:
  * run prepublish scripts
  * run tests & coverage
  * determine which packages were changed and should be released (gh-releases, tags)
  * determine which version should be used for each changed package by analyzing commit messages related to them (for example, using changed files path)
  * add appropriate tags to current commit: changed-package@new-version and push tags to repo
  * create and publish release notes for each released package by analyzing commit messages related to them
  * temporary set calculated versions into `package.json` of packages to be released
  * release changed packages to `npm`
  * publish website+demos

I realize that it is pretty complicated setup and requires a lot of work that can't be done in one step.
So we should brake it down into smaller steps. For instance, we can manually set up package versions in **next** branch before rebasing it into **master** and prepare release notes by hands as well.

Also such setup most likely have some cons and flaws which I would be glad to hear and discuss.
So I invite you guys to discuss it or maybe put forward your great and valuable suggestions.

**Comment by christianalfoni** [comment]
Thanks for a great overview @Guria!

I think when we put this much effort into a release flow we should probably make it generic... for others to use as well. Does that seem reachable?

In the meantime... what are critical scripts for release and what can be done manually until we find time to get the rest done?

**Comment by Guria** [comment]
I'd like to have list of updated packages with related commits as first.
It will simplify manual release a lot.

**Comment by gaspard** [comment]
@Guria For the semantic release part, I propose that we use commitizen. We should only allow `scope` to be package names like `cerebral`, `router`, `function-tree` or `monorepo`.

```
feat(cerebral): some new feature /// Minor version bump in cerebral

BREAKING CHANGE: /// Major version bump
API xyz
```

Parsing the commit messages is not too hard. And I agree with @christianalfoni: we should work on this as a reusable thing.

To get started, I propose to create two repositories: `publisher` and `publisher-test`. We work on this thing in `publisher` repo and use the `publisher-test` for testing, creating dummy commit messages and such.

**Comment by Guria** [comment]
What about commits that has changes in several packages? Sometimes we do atomic change that requires edits in at least two packages.
And also we should have still pretty low entry level for newcomers to make PRs. For now I try to rebase PRs with multiple commits that conforms with our guidelines. Or just fixing commit message myself on github using squash&merge button.
That's why I think it's better to inspect changed file path in commit.

> Parsing the commit messages is not too hard.

Yeah. There are already some notable count of solutions to parse commit message format we use.

> we should work on this as a reusable thing.

I also wondered if using `function-tree` here is a good idea. What I didn't liked in `lerna` it's too opinionated and really hard to configure. It seems to me that it's much better to provide lego-blocks "actions" to combine it in desired workflow.

> I propose to create two repositories

👍

**Comment by christianalfoni** [comment]
Just for anyone following this issue, we are having a hangout on Thursday 29th, from the morning. We will focus on the script needed to parse the commit messages to identify what to release.

**Comment by gaspard** [comment]
function-tree is a great idea !

@Guria reading file changes to detect changed packages is fine but how do we know if this is a `patch`, `minor` or `major` change ?

One solution would be to have an `api_test.js` file in every package. This thing contains a test (as complete as possible) with API usage. If API changes, this file has to change. A `minor` change means added stuff, a `major` change means removed stuff.

Let's continue brainstorming...

**Comment by christianalfoni** [comment]
@gaspard Was this not to be based on commitizen? We just check FEATURE, BUG etc. in commit message? 

Function-tree for the win :-D

**Comment by henri-hulski** [comment]
Yeah I think if there is a 'BREAKING CHANGE'  in the commit message it should be a major version change. And such a commit should only include one package to make it easy to determine which package should upgrade major version. 

'feat'  commit messages are minor version upgrades and 'fix' a patch version upgrade. 

In general this kind of commits should only affect one package. 

For 'chore' and similar commits we need to decide manually which packages has to upgrade.

**Comment by Guria** [comment]
Exactly. Changed path to determine packages. Commit messages to decide on version change.

**Comment by gaspard** [comment]
And discipline for "feat" and "BREAKING CHANGE": these two can only affect one package (+docs+demos) at a time. We could event have pre-commit test for this.

**Comment by christianalfoni** [comment]
Okay, so let us sum up the current scope for publishing:

- Script that extracts packages changed, what kind of change and commit messages to the terminal
- Pre-commit script that blocks commits causing a feat/breaking in two different packages

Does that seem correct?

**Comment by Guria** [comment]
follow-up #989
