### ISSUE TITLE
@cerebral/http documentation is confusing

### ISSUE THREAD

**Issue by user1736** [cerebral/cerebral#978]
Hello!
I'm new to cerebral and documentation for ``@cerebral/http`` makes me so dejected.

According to [doc](http://cerebraljs.com/docs/addons/http.html), I can use it like this:
```
import {set} from 'cerebral/operators'
import {httpGet} from '@cerebral/http/operators'
import {state, props} from 'cerebral/tags'

export default [
  httpGet(`/items/${props`itemKey`}`),
  set(state`app.currentItem`, props`result`)
]
```

But if I do so, I'll get the following error:
```
Uncaught TypeError: Cannot read property 'get' of undefined
    at Object.httpGet [as function] (httpGet.js:17)
```
Which says nothing to me.

So there're two problems:
1. Unclear error message If use http operators without adding ``HttpProvider``
2. Gap in documentation, since there's no even word about I should instantiate it first in controller section.

**Comment by Guria** [comment]
Thanks for reporting. It is a very important issues on my mind. We must check docs of all modules to avoid such confusion and put prerequisites at first place.
Informative error messages when operators used without required providers is also must have for every package.
Cc @christianalfoni @edgesoft @henri @reflog

**Comment by user1736** [comment]
Some update here:

In my issue, I've used this code with dynamic url

```
import {set} from 'cerebral/operators'
import {httpGet} from '@cerebral/http/operators'
import {state, props} from 'cerebral/tags'

export default [
  httpGet(`/items/${props`itemKey`}`),
  set(state`app.currentItem`, props`result`)
]
```

which isn't working without adding a ``string`` tag at the url template beginning, like so:
 ```
import {set} from 'cerebral/operators'
import {httpGet} from '@cerebral/http/operators'
import {state, props, string} from 'cerebral/tags'

export default [
  httpGet(string`/items/${props`itemKey`}`), //see string tag before the url template? it's so easy so miss it
  set(state`app.currentItem`, props`result`)
]
```
I'd suggest to highlight this feature in documentation, and add more examples with dynamic urls.

**Comment by fvgoto** [comment]
Also worth rewording in [docu](http://cerebraljs.com/docs/addons/http.html):
```
// Any options defined in "Custom request"
```
What does `Custom request` mean? It's not "defined" anywhere... (I know it means options like for `HttpProvider` instantiation in the controller...).

**Comment by edgesoft** [comment]
@fvgoto Do you want to make a PR for this?

**Comment by christianalfoni** [comment]
Check this issue for hints on what to improve on the http documentation

**Comment by henri-hulski** [comment]
The http documentation needs also an example of using `resolveObject`.
`resolveObject` should also be documented in other places like Cerebral tags, firebase docs and http guide.

**Comment by henri-hulski** [comment]
See #1280.

**Comment by christianalfoni** [comment]
Housekeeping!
