### ISSUE TITLE
UniversalController: Module with Router throws error

### ISSUE THREAD

**Issue by sladiri** [cerebral/cerebral#979]
I created a module with a Router sub-module. When I pass it to the UniversalController on the server, it throws an error:
Inside `Router.onSignalStart`, the `urlMapper.stringify` throws an error, because `payload` is undefined.

I can fix it by deleting the router in the module before creating the UniversalController instance.

**Comment by christianalfoni** [comment]
Thanks @sladiri , I though router was compatible with node due to tests, but it seems it is not. This needs to be fixed :)

**Comment by sladiri** [comment]
It looks like the Router calls `UniversalController.run` with three parameters, but only two are expected. The following code fixes it, but I am not sure what the best way to deal with it is.
```js
// UniversalController.js
run(sequence, payload, foo) {
    if (typeof foo === 'object') {
      sequence = payload
      payload = foo
    }
    return super.run('UniversalController.run', sequence, payload)
  }
```

**Comment by christianalfoni** [comment]
@sladiri Oh, I see... I believe router should rather call `runSignal`, not `run` :)

**Comment by sladiri** [comment]
@christianalfoni As far as I understand, this is a name clash because `UniversalController.run` has a different signature from its superclass. I just guessed that Router called it before, but I cannot see any better way than to check inside `UniversalController.run`, since it deviates from `Controller.run`.
