### ISSUE TITLE
Larger examples

### ISSUE THREAD

**Issue by danmartinez101** [cerebral/cerebral#98]
Great work here @christianalfoni!

Can you point me to any larger open-source applications or demos(larger than todomvc) that use Cerebral? I want to get a feel for how to go about building something bigger than the todos app in cerebral.

**Comment by danmartinez101** [comment]
For reference, something the size of John Papa's code camper http://cc-ng-z.azurewebsites.net/

**Comment by christianalfoni** [comment]
Hi @danmartinez101! Actually Cerebral is in part a tool to handle the logic needed in a  project I started last year. I have actually applied for some funding to finish that project and it is a really good example of how to structure an application and what really cool stuff you can do with Cerebral.

I will be working almost 100% on this project from October 1st and will share a lot of that with the project as I move on.

I am also working on on a new web page for Cerebral that will have a lot more information on how to structure apps, best practices etc. I hope to get that done by the weekend :-)

Thanks for the example, it certainly is a better than the TodoMVC app. Currently I have a bit too much on my plate to work on that, so will start out with more documentation, but it is a really great idea to build something like that as a reference app!

**Comment by idream3** [comment]
@danmartinez101 you can check outthe post by  @saulshanabrook here:
http://www.saulshanabrook.com/organizing-cerebral-code/

We are using a similar structure to this by separating domains into modules.

**Comment by danmartinez101** [comment]
@christianalfoni Thanks for the timeline; I'm looking forward to seeing more.

@idream3 Thanks for that link! I'll definitely give it a read :)

**Comment by jolafrite** [comment]
I want to add a +1 on this one.
I think what is also important for a great framework is to have real use examples.
There is common pieces of code we will all have to use when we are designing serious projets.
So why not proposing one way to implement that (I'm talking about Authentication, Acl, Datatable, ...)
It will all save us time and give us real use cases

**Comment by bfitch** [comment]
@jolafrite I've been working on auth with an Oauth 2 redirect flow and I'd be happy to share. But, I also think this is a place where `cerebral-addons` can really shine. In my view `cerebral` gives us the building blocks to make stuff like auth easy, but it should not go so far as to *prescribe* a cerebral auth solution. I think that would take the project in a different direction and it would feel very different to use.

I like @christianalfoni's commitment to a more React-style ["minimal api surface area"](https://www.youtube.com/watch?v=4anAwXYqLG8) and smaller packages that are composed together. Any boilerplate or patterns we find as a community can be shared through addons or just npm packages, IMO. The beauty is that it mostly boils down to functions and a pretty small api for wiring them together. :smile:

**Comment by jolafrite** [comment]
Actually I was not thinking about directly into cerebral 
but into different repos like cerebral-auth, cerebral-acl ,...

**Comment by bfitch** [comment]
Ah cool! That is more what I had in mind too. More of an addon thing.

**Comment by christianalfoni** [comment]
Just closing this. There will be a Cerebral hangout next wednesday, https://docs.google.com/spreadsheets/d/1nWQ97AOGWw24dQIZfSXgprs220Wfcc4WA7b7DudecxY/edit?usp=sharing and I made this small video with a large project: https://www.youtube.com/watch?v=ngLbZTVZO3A
