### ISSUE TITLE
IE: devtools fails on websocket creation

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#988]
Steps to reproduce:
* open http://cerebraljs.com/todomvc/ in ie11

Console has error: `SCRIPT5022: SecurityError`
Nothing rendered.

**Comment by christianalfoni** [comment]
I guess IE11 does not like localhost websocket connection... https://github.com/qzind/qz-print/issues/39

Read initial issue there

**Comment by Guria** [comment]
I guess it must not prevent rendering at all

**Comment by christianalfoni** [comment]
I hate IE... develop apps on modern browsers
